'use client';
import {useEffect,useState} from 'react';
import {QualityBadge,QualityLegend} from '@/components/quality-badge';
type Installer={canEdit?:boolean;id:string;name:string;quality_score:number|null;quality_updated_at:string|null};
export function InstallerQuality({editable=false}:{editable?:boolean}){
 const [items,setItems]=useState<Installer[]>([]),[drafts,setDrafts]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[scope,setScope]=useState(false),[query,setQuery]=useState('');
 async function load(){try{const r=await fetch('/api/installer/quality',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setItems(d.installers);setScope(d.canScoreAll===true);setError('');}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{load();const refresh=()=>{if(document.visibilityState==='visible')load()};document.addEventListener('visibilitychange',refresh);const timer=setInterval(refresh,60000);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',refresh)}},[]);
 async function save(id:string){setBusy(true);setMessage('');try{const r=await fetch('/api/installer/quality',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,score:Number(drafts[id])})}),d=await r.json();if(!r.ok)throw Error(d.error);setDrafts(v=>{const next={...v};delete next[id];return next});setMessage('Quality score saved.');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="installer-quality" aria-label="Guild Quality Scores"><div><h2>{editable?'Guild Quality Scores':'My Guild Quality Score'}</h2><p>{editable?(scope?'You can update any active installer.':'All installer scores are visible. You can update installers assigned to you.'):'Updated by an authorized field supervisor or administrator.'}</p></div><QualityLegend/>{loading&&<p>Loading score…</p>}{error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!loading&&!error&&items.length===0&&<p>{editable?'No installers assigned to you.':'Not rated yet.'}</p>}{editable&&<label className="quality-search">Find installer<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name"/></label>}{items.filter(item=>item.name.toLowerCase().includes(query.toLowerCase())).map(item=><div className="quality-row" key={item.id}>{editable&&<strong>{item.name}</strong>}<QualityBadge score={item.quality_score}/>{item.quality_updated_at&&<small>Updated {new Date(item.quality_updated_at).toLocaleDateString()}</small>}{editable&&item.canEdit&&<form onSubmit={e=>{e.preventDefault();save(item.id)}}><label>Quality score for {item.name}<input type="number" min="0" max="4" step="0.01" required value={drafts[item.id]??(item.quality_score?.toFixed(2)||'')} onChange={e=>setDrafts(v=>({...v,[item.id]:e.target.value}))}/></label><button disabled={busy||drafts[item.id]===undefined||drafts[item.id]===''}>{busy?'Saving…':'Save score'}</button></form>}</div>)}</section>
}
