import {env} from '@/lib/server-env';
import {database} from '@/db/raw';
import webpush from 'web-push';
export function validPushEndpoint(value:string){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&(!u.port||u.port==='443')&&(u.hostname==='fcm.googleapis.com'||u.hostname==='updates.push.services.mozilla.com'||u.hostname.endsWith('.push.apple.com')||u.hostname==='web.push.apple.com'||u.hostname.endsWith('.notify.windows.com'))}catch{return false}}
export async function deliverPush(id:string){const db=database();const n:any=await db.prepare('SELECT * FROM notifications WHERE id=?').bind(id).first();if(!n||n.push_status==='sent')return;const recipient:any=await db.prepare("SELECT id,role FROM members WHERE id=? AND active=1").bind(n.recipient_id).first();if(!recipient){await db.prepare("UPDATE notifications SET push_status='recipient_inactive' WHERE id=?").bind(id).run();return;}const subs=await db.prepare('SELECT endpoint,payload FROM push_subscriptions WHERE member_id=?').bind(n.recipient_id).all();if(!subs.results.length){await db.prepare("UPDATE notifications SET push_status='not_enabled' WHERE id=?").bind(id).run();return;}
 let sent=0;
 for(const row of subs.results as any[]){try{if(!validPushEndpoint(row.endpoint))continue;const details=webpush.generateRequestDetails(JSON.parse(row.payload),JSON.stringify({title:'Production Desk update',body:n.message,url:recipient.role==='installer'?'/installers':'/?job='+encodeURIComponent(n.job_id),tag:n.id}),{TTL:86400,vapidDetails:{subject:env.VAPID_SUBJECT||env.APP_URL!,publicKey:(env as any).VAPID_PUBLIC_KEY,privateKey:(env as any).VAPID_PRIVATE_KEY}});const response=await fetch(details.endpoint,{method:'POST',headers:details.headers,body:details.body,redirect:'error',signal:AbortSignal.timeout(8000)});if(response.ok)sent++;else if(response.status===404||response.status===410)await db.prepare('DELETE FROM push_subscriptions WHERE endpoint=?').bind(row.endpoint).run();}catch{/* Record failure below; retain in-app notification. */}}
 await db.prepare('UPDATE notifications SET push_status=? WHERE id=?').bind(sent?'sent':'failed',id).run();
}
