import test from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {createServer} from 'vite';
const pg=new PGlite();
for(const file of ['001_initial','002_installer_quality','003_account_permissions','004_account_profiles','005_account_theme','006_more_themes','007_customer_records','008_live_operations','008_live_operations'])await pg.exec(readFileSync(`supabase/migrations/${file}.sql`,'utf8'));
const wrap=c=>({query:async(sql,args)=>{const r=await c.query(sql,args);return {rows:r.rows,changes:r.affectedRows??r.rows.length}},transaction:fn=>c.transaction(tx=>fn(wrap(tx)))});
const vite=await createServer({configFile:false,resolve:{alias:{'@':resolve('.')}},plugins:[{name:'live-test',enforce:'pre',resolveId(id){if(id==='@/db/raw'||/\/db\/raw(?:\.ts)?$/.test(id))return '\0db';if(/(?:\/|^)server-env(?:\.ts)?$/.test(id)||id==='./server-env')return '\0env';if(id==='./push'||id==='@/lib/push')return '\0push'},load(id){if(id==='\0db')return 'export const database=()=>globalThis.__liveDb';if(id==='\0env')return 'export const env={BUCKET:{head:async key=>({customMetadata:{jobId:globalThis.__jobId,uploadedBy:globalThis.__installerId,sha256:key}})}}';if(id==='\0push')return 'export async function deliverPush(){}'}}],server:{middlewareMode:true,hmr:false}});
const {createDatabase}=await vite.ssrLoadModule('/db/adapter.ts');globalThis.__liveDb=createDatabase(wrap(pg));
const {operation,operationsData}=await vite.ssrLoadModule('/lib/operations-store.ts');
const {localDay,addDays,aging,bonusPeriod,bonusMetrics}=await vite.ssrLoadModule('/lib/operations.ts');
const {requiredReportKinds,reportError}=await vite.ssrLoadModule('/lib/installer-workflow.ts');
const admin={id:'owner',name:'Admin',role:'admin',email:'admin@example.com',active:1};
const fs={id:crypto.randomUUID(),name:'Supervisor',role:'supervisor',can_edit_jobs:1,active:1};
const pa={id:crypto.randomUUID(),name:'Assistant',role:'production_assistant',can_edit_jobs:1,active:1};
const installer={id:crypto.randomUUID(),name:'Installer',role:'installer',active:1};globalThis.__installerId=installer.id;
for(const m of [admin,fs,pa,installer])await pg.query('INSERT INTO production.members(id,name,email,role,active,can_edit_jobs) VALUES($1,$2,$3,$4,1,$5)',[m.id,m.name,m.id+'@example.com',m.role,m.can_edit_jobs||0]);
const today=localDay();let j;
async function reload(){j=(await operationsData(admin)).jobs[0];globalThis.__jobId=j.id;return j}
async function act(m,action,data={}){await operation(m,{action,jobId:j?.id,version:j?.version,data});return reload()}
test('live approvals, persistence, scopes and money',async()=>{
 await act(pa,'create',{number:'LEGACY-1',customer:'Test Customer',address:'123 Test Street',amount:1000,contractAmount:5000,supervisorId:fs.id});assert.equal(j.stage,'Ordered');
 await assert.rejects(()=>act(pa,'schedule',{date:today,period:'AM',installerId:installer.id,stop:1}),/RCVD/i);
 await assert.rejects(()=>act(pa,'receive',{received:today,materials:[{bay:'D-1',brand:'Thermatru',materialType:'Entry Door'}]}),/separate accounts/i);
 await act(pa,'receive',{received:addDays(today,-31),materials:[{bay:'A-12',brand:'Simonton',materialType:'Window'},{bay:'A-13',brand:'CWS',materialType:'SPD'}]});assert.equal(j.stage,'Received');assert.equal(j.materials.length,2);
 await assert.rejects(()=>act(pa,'schedule',{date:today,period:'AM',installerId:installer.id,stop:1}),/permit/i);
 await act(pa,'permit',{received:true,number:'PERMIT-100'});
 await assert.rejects(()=>act(pa,'schedule',{date:today,period:'AM',installerId:installer.id,stop:1}),/payment/i);
 await act(pa,'payment',{amount:0,reference:'Receipt #1'});
 await act(pa,'schedule',{date:today,period:'AM',installerId:installer.id,stop:1,paymentReference:'Receipt #1'});
 assert.equal(j.install,'');assert.ok(j.operations.pendingSchedule);assert.equal((await operationsData(installer)).jobs.length,0);
 await assert.rejects(()=>act(pa,'approveSchedule'),/approval required/);
 await act(fs,'approveSchedule');assert.equal(j.install,today);assert.equal(aging(j,today).aged,true);
 assert.equal((await pg.query("SELECT count(*)::integer AS count FROM production.notifications WHERE recipient_id=$1 AND message LIKE '%added to your calendar%'",[installer.id])).rows[0].count,1);
 const paData=await operationsData(pa);assert.equal(paData.config,null);assert.equal('estimate' in paData.metrics,false);
 const installerData=await operationsData(installer);assert.equal(installerData.jobs[0].amount,undefined);assert.equal(installerData.jobs[0].contractAmount,undefined);
 await act(fs,'start');assert.equal(j.stage,'Production');
 const kinds=['front','rear','left','right','completion'];const attachments=kinds.map(kind=>({key:`jobs/${j.id}/${kind}/${crypto.randomUUID()}`,name:kind+'.jpg',kind}));
 for(const a of attachments)await pg.query("INSERT INTO production.attachment_uploads(key,staging_key,job_id,kind,member_id,name,expires,status,sha256) VALUES($1,$1,$2,$3,$4,$5,0,'ready',$1)",[a.key,j.id,a.kind,installer.id,a.name]);
 await act(installer,'report',{id:crypto.randomUUID(),status:'Complete',reason:'',notes:'Done',installed:today,attachments});assert.equal(j.stage,'Production');assert.equal(j.operations.report.pending,true);
 assert.equal((await pg.query("SELECT count(*)::integer AS count FROM production.notifications WHERE recipient_id=$1 AND message LIKE '%Field supervisor review required%'",[fs.id])).rows[0].count,1);
 await assert.rejects(()=>act(pa,'reviewReport',{approve:true}),/approval required/);
 await act(fs,'reviewReport',{approve:true});assert.equal(j.stage,'Closed');assert.equal(j.operations.report.confirmed,true);
 await act(fs,'edit',{notes:'New notes'});assert.equal(j.notes,'New notes');
 await assert.rejects(()=>act(fs,'edit',{amount:10}),/protected/);
 await act(fs,'request',{type:'ACCRF',details:'Extra trim',amount:5100});const req=j.operations.requests[0];
 await assert.rejects(()=>act(fs,'reviewRequest',{id:req.id,approve:true}),/Administrator/);
 await act(admin,'reviewRequest',{id:req.id,approve:true});assert.equal(j.contractAmount,5100);assert.equal(j.amount,100);
 await assert.rejects(()=>operation(admin,{action:'edit',jobId:j.id,version:j.version-1,data:{notes:'stale'}}),/changed/);
 assert.ok(j.history.some(h=>h.text.includes('approved')));
 await act(pa,'request',{type:'Service',details:'Adjust lock',serviceDate:addDays(today,2),installerId:installer.id,period:'PM'});let service=j.operations.requests[0];assert.equal(j.operations.services?.length||0,0);assert.equal(service.status,'Pending');
 await assert.rejects(()=>act(fs,'reviewRequest',{id:service.id,approve:true}),/Administrator/);
 await act(admin,'reviewRequest',{id:service.id,approve:true});assert.equal(j.operations.services.length,1);assert.equal(j.stage,'SVC');
 await act(pa,'payment',{amount:0,reference:'Final payment'});
 await act(fs,'request',{type:'UTI',details:'Customer unavailable',paymentReference:'Final payment'});
 const uti=j.operations.requests[0];await assert.rejects(()=>act(pa,'reviewRequest',{id:uti.id,approve:true}),/Administrator/);
 await act(admin,'reviewRequest',{id:uti.id,approve:true});assert.equal(j.stage,'UTI');assert.equal(aging(j,today).aged,false);
 const survey={externalId:'guild-survey-1',installerId:installer.id,completedOn:today,ratings:[5,5,5,5]};
 await operation(fs,{action:'survey',data:survey});await assert.rejects(()=>operation(fs,{action:'survey',data:survey}),/already/);
 assert.equal((await operationsData(fs)).metrics.score,4);
 await assert.rejects(()=>operation(installer,{action:'configure',data:{}}),/Administrator/);
 await assert.rejects(()=>operation(installer,{action:'create',data:{}}),/permission/);
 await operation(fs,{action:'crewColors',data:{[installer.id]:'#123abc'}});assert.equal((await operationsData(fs)).crewColors[installer.id],'#123abc');assert.deepEqual((await operationsData(admin)).crewColors,{});
});
test('supervisor status controls and administrator deletion',async()=>{
 await act(pa,'create',{number:'LEGACY-DELETE',customer:'Delete Customer',address:'456 Test Street',amount:0,contractAmount:1000,supervisorId:fs.id});
 await assert.rejects(()=>act(pa,'status',{target:'Production',reason:''}),/supervisor or administrator/i);
 await act(pa,'receive',{received:today,bay:'B-2',brand:'CWS',materialType:'SPD'});await act(pa,'permit',{received:true,number:'PERMIT-200'});await act(pa,'schedule',{date:today,period:'AM',installerId:installer.id,stop:2,additionalInstructions:'Side gate'});
 await act(fs,'status',{target:'Production'});assert.equal(j.stage,'Production');
 await act(fs,'status',{target:'InProgress'});assert.equal(j.stage,'InProgress');assert.equal(aging(j,today).kind,'Production');
 const incKinds=['front','rear','left','right','issue','incomplete'];const incAttachments=incKinds.map(kind=>({key:`jobs/${j.id}/${kind}/${crypto.randomUUID()}`,name:kind+'.jpg',kind}));
 for(const a of incAttachments)await pg.query("INSERT INTO production.attachment_uploads(key,staging_key,job_id,kind,member_id,name,expires,status,sha256) VALUES($1,$1,$2,$3,$4,$5,0,'ready',$1)",[a.key,j.id,a.kind,installer.id,a.name]);
 await act(installer,'report',{id:crypto.randomUUID(),status:'Incomplete',reason:'Damaged sash',notes:'Return needed',installed:today,attachments:incAttachments});
 await assert.rejects(()=>act(fs,'reviewReport',{approve:true}),/reorder information/i);await act(fs,'edit',{reorder:'Order replacement sash'});await act(fs,'reviewReport',{approve:true});assert.equal(j.stage,'Incomplete');
 const id=j.id;await assert.rejects(()=>act(fs,'delete'),/Administrator/);await act(admin,'delete');
 assert.equal((await pg.query('SELECT id FROM production.jobs WHERE id=$1',[id])).rows.length,0);
});
test('period and aging boundaries',()=>{
 assert.deepEqual(bonusPeriod('2026-09-15'),{start:'2026-08-26',end:'2026-09-29'});
 assert.deepEqual(bonusPeriod('2026-09-30'),{start:'2026-09-30',end:'2026-10-27'});
 assert.equal(aging({stage:'Received',received:addDays(today,-30),install:today},today).aged,false);
 assert.equal(aging({stage:'Received',received:addDays(today,-31),install:today},today).aged,true);
 assert.equal(aging({stage:'Incomplete',incompleteSince:addDays(today,-45)},today).aged,true);
 assert.equal(aging({stage:'UTI',received:addDays(today,-90)},today).aged,false);
 const m=bonusMetrics([],[{completed_on:today,ratings:[5,5,5,5]}],null,today);assert.equal(m.score,4);assert.equal(m.estimate,null);
});
test('completion and incomplete evidence requirements',()=>{
 assert.deepEqual(requiredReportKinds('Complete'),['front','rear','left','right','completion']);
 assert.deepEqual(requiredReportKinds('Incomplete'),['front','rear','left','right','issue','incomplete']);
 const files=kinds=>kinds.map((kind,i)=>({kind,key:'file-'+i}));
 assert.equal(reportError({status:'Complete',reason:'',attachments:files(requiredReportKinds('Complete'))}),'');
 assert.equal(reportError({status:'Incomplete',reason:'Broken glass',attachments:files(requiredReportKinds('Incomplete'))}),'');
 assert.match(reportError({status:'Incomplete',reason:'',attachments:files(requiredReportKinds('Incomplete'))}),/Explain/);
 assert.match(reportError({status:'Incomplete',reason:'Broken glass',attachments:files(['front','rear','left','right','incomplete'])}),/photos of the issue/i);
});
test.after(async()=>{await vite.close();await pg.close()});
