'use client';
import {useEffect,useState} from 'react';
import {roleLabels} from '@/lib/account-roles';
import {QualityBadge} from '@/components/quality-badge';
type Details={jobTitle:string;startDate:string;address:string;emergencyContact:string;emergencyPhone:string;skills:string;notes:string;additional:{label:string;value:string}[]};
const emptyDetails:Details={jobTitle:'',startDate:'',address:'',emergencyContact:'',emergencyPhone:'',skills:'',notes:'',additional:[]};
type Profile={id:string;name:string;email:string;role:string;phone:string;active:number;installer_code?:string;quality_score:number|string|null;profile_details:Partial<Details>;can_edit_jobs?:number;can_score_all_installers?:number};
export function AccountProfile({id}:{id:string}){
 const [member,setMember]=useState<Profile|null>(null),[name,setName]=useState(''),[phone,setPhone]=useState(''),[details,setDetails]=useState<Details>(emptyDetails),[canEdit,setCanEdit]=useState(false),[self,setSelf]=useState(false),[manage,setManage]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let live=true;setLoading(true);setError('');setMessage('');fetch('/api/team/profile?id='+encodeURIComponent(id),{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(live){setMember(d.member);setName(d.member.name);setPhone(d.member.phone||'');setDetails({...emptyDetails,...d.member.profile_details});setCanEdit(d.canEdit);setSelf(d.isSelf);setManage(d.canManage)}}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[id]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/team/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,name,phone,details})}),d=await r.json();if(!r.ok)throw Error(d.error);setMember(m=>m?{...m,name,phone,profile_details:details}:m);setMessage('Profile saved.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const update=(key:keyof Details,value:string)=>setDetails(d=>({...d,[key]:value}));
 if(loading)return <p role="status">Loading profile…</p>;
 if(!member)return <p className="error" role="alert">{error||'Account not found.'}</p>;
 return <section className="full-account-profile"><header className="profile-header"><span className="profile-avatar" aria-hidden="true">{member.name.split(' ').map(w=>w[0]).slice(0,2).join('')}</span><div><p>{self?'My profile':'Account profile'}</p><h1>{member.name}</h1><span>{member.id==='owner'?'Owner':roleLabels[member.role]} · {member.active?'Active':'Inactive'}{member.installer_code?' · '+member.installer_code:''}</span></div>{member.role==='installer'&&<QualityBadge score={member.quality_score===null?null:Number(member.quality_score)}/>}</header><div className="profile-actions">{manage&&<a href={'/accounts?edit='+encodeURIComponent(member.id)}>Edit account & permissions</a>}{self&&<a href="/change-password">Change password</a>}<a href="/accounts">Account directory</a></div>
 <form onSubmit={save}><fieldset disabled={!canEdit||busy}><section className="profile-section"><h2>Contact & work details</h2><div className="account-form-grid"><label>Name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Sign-in email<input readOnly value={member.email}/></label><label>Phone<input type="tel" maxLength={50} value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Job title<input maxLength={100} value={details.jobTitle} onChange={e=>update('jobTitle',e.target.value)}/></label><label>Start date<input type="date" value={details.startDate} onChange={e=>update('startDate',e.target.value)}/></label><label>Address<textarea maxLength={500} rows={2} value={details.address} onChange={e=>update('address',e.target.value)}/></label></div></section>
 <section className="profile-section"><h2>Emergency contact</h2><div className="account-form-grid"><label>Name & relationship<input maxLength={150} value={details.emergencyContact} onChange={e=>update('emergencyContact',e.target.value)}/></label><label>Phone<input type="tel" maxLength={50} value={details.emergencyPhone} onChange={e=>update('emergencyPhone',e.target.value)}/></label></div></section>
 <section className="profile-section"><h2>Skills & notes</h2><label>Skills, certifications & training<textarea rows={3} maxLength={2000} value={details.skills} onChange={e=>update('skills',e.target.value)}/></label><label>Profile notes<textarea rows={5} maxLength={5000} value={details.notes} onChange={e=>update('notes',e.target.value)}/></label><p className="muted">Profile information is available to administrators.</p></section>
 <section className="profile-section"><h2>Additional information</h2><p>Add fields for details you want to keep with this account.</p>{details.additional.map((field,index)=><div className="custom-profile-field" key={index}><label>Field name<input required maxLength={80} placeholder="For example, shirt size" value={field.label} onChange={e=>setDetails(d=>({...d,additional:d.additional.map((f,i)=>i===index?{...f,label:e.target.value}:f)}))}/></label><label>Value<input maxLength={500} value={field.value} onChange={e=>setDetails(d=>({...d,additional:d.additional.map((f,i)=>i===index?{...f,value:e.target.value}:f)}))}/></label><button type="button" aria-label={'Remove field '+(field.label||index+1)} onClick={()=>setDetails(d=>({...d,additional:d.additional.filter((_,i)=>i!==index)}))}>Remove</button></div>)}{canEdit&&<button type="button" disabled={details.additional.length>=20} onClick={()=>setDetails(d=>({...d,additional:[...d.additional,{label:'',value:''}]}))}>+ Add information field</button>}</section></fieldset>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}{canEdit?<div className="profile-save"><button className="primary-action" disabled={busy}>{busy?'Saving…':'Save profile'}</button></div>:<p>Only the owner or this administrator can edit this profile.</p>}</form></section>
}
