'use client';
import {useState} from 'react';
import {aging} from '@/lib/operations';
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
export function AgingReport({jobs,today,onOpen}:any){
 const [day,setDay]=useState(today),[group,setGroup]=useState('All');
 const rows=jobs.map((job:any)=>({job,...aging(job,day)})).filter((r:any)=>r.kind);
 const known=rows.filter((r:any)=>r.aged),unknown=rows.filter((r:any)=>r.missing);
 const totals=known.reduce((sum:number,r:any)=>sum+(r.job.amount??0),0);
 return <section className="op-panel"><h2>Aging reports</h2><label>Age current job statuses as of<input type="date" value={day} max={today} onChange={e=>setDay(e.target.value||today)}/></label><p>This recalculates the current records at the selected date; it is not a historical status snapshot. RCVD ages after 30 days, PROD after 7 days, and INC at 45 days from entering INC. Dollars use the remaining balance due.</p><h3>{known.length} confirmed aged jobs · {money(totals)} known aged balance</h3>{(unknown.length>0||known.some((r:any)=>r.job.amount==null))&&<p className="op-callout">Incomplete total: {unknown.length} jobs have unconfirmed aging dates; {known.filter((r:any)=>r.job.amount==null).length} aged jobs have unknown balances. Do not use this as the final bonus total until these are resolved.</p>}<div className="op-schedule-actions">{['All','Received','Production','Incomplete'].map(g=><button key={g} aria-pressed={group===g} onClick={()=>setGroup(g)}>{({All:'All',Received:'RCVD',Production:'PROD',Incomplete:'INC'} as any)[g]}</button>)}</div>{['Aged','Needs date review','Not aged'].map(section=>{const list=rows.filter((r:any)=>(group==='All'||r.kind===group)&&(section==='Aged'?r.aged:section==='Needs date review'?r.missing:!r.aged&&!r.missing)).sort((a:any,b:any)=>(b.days??-1)-(a.days??-1));return <div key={section}><h3>{section} ({list.length})</h3><div className="live-import-scroll"><table className="op-aging-table"><thead><tr><th>Customer</th><th>Status</th><th>Days</th><th>Amount due</th></tr></thead><tbody>{list.map((r:any)=><tr key={r.job.id}><td><button className="live-button" onClick={()=>onOpen(r.job.id)}>#{r.job.number} · {r.job.customer}</button></td><td>{({Received:'RCVD',Production:'PROD',Incomplete:'INC'} as any)[r.kind]}</td><td>{r.days??'Unconfirmed'}</td><td>{r.job.amount==null?'Unknown':money(r.job.amount)}</td></tr>)}</tbody></table></div></div>})}</section>
}
