'use client';
import {useState} from 'react';
import {aging} from '@/lib/operations';

export function AgingDateEditor({jobs,today,save,onOpen}:any){
 const [draft,setDraft]=useState<Record<string,{date:string,version:number,key:string}>>({}),[missingOnly,setMissingOnly]=useState(true),[query,setQuery]=useState(''),[reference,setReference]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const eligible=jobs.map((job:any)=>({job,...aging(job,today)})).filter((r:any)=>r.kind);
 const rows=eligible.filter((r:any)=>(!missingOnly||r.missing)&&[r.job.customer,r.job.number].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a:any,b:any)=>Number(b.missing)-Number(a.missing)||String(a.job.customer).localeCompare(String(b.job.customer)));
 const keyFor=(j:any)=>j.stage==='Received'?'received':j.stage==='Incomplete'?'incompleteSince':'installed';
 const changed=eligible.filter((r:any)=>draft[r.job.id]?.date&&draft[r.job.id].date!==String(r.job[keyFor(r.job)]||'').slice(0,10));
 return <section className="op-panel"><h2>Correct aging dates</h2><p>Enter verified dates for multiple jobs here. RCVD uses the original received date, PROD uses the production start date, and INC uses the Reorder Date. Corrections update aging totals and are recorded in job history.</p><p>{eligible.filter((r:any)=>r.missing).length} jobs need dates · {changed.length} changes ready</p>
 <form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{if(!changed.length)throw Error('Enter at least one changed date.');if(changed.length>100)throw Error('Save up to 100 corrections at a time.');await save({reference,rows:changed.map((r:any)=>({id:r.job.id,version:draft[r.job.id].version,key:draft[r.job.id].key,date:draft[r.job.id].date}))});setDraft({});setMessage('Dates saved. Aging totals have been refreshed.');}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}>
 <fieldset disabled={busy}><div className="op-filters"><input aria-label="Find jobs needing dates" placeholder="Customer name or ID" value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={missingOnly} onChange={e=>setMissingOnly(e.target.checked)}/>Missing dates only</label></div>
 <div className="live-date-editor"><table><thead><tr><th>Customer</th><th>Status / date needed</th><th>Current date</th><th>Correct date</th></tr></thead><tbody>{rows.map(({job,kind}:any)=>{const key=keyFor(job);return <tr key={job.id}><td><button type="button" className="live-button" onClick={()=>onOpen(job.id)}>#{job.number} · {job.customer}</button></td><td>{kind==='Received'?'RCVD — Received':kind==='Incomplete'?'INC — Reorder':'PROD — Production start'}</td><td>{String(job[key]||'Not recorded').slice(0,10)}</td><td><input aria-label={'Correct date for '+job.number} type="date" max={today} value={draft[job.id]?.date??''} onChange={e=>setDraft({...draft,[job.id]:{date:e.target.value,version:job.version,key}})}/></td></tr>})}</tbody></table>{!rows.length&&<p>No jobs match this filter.</p>}</div>
 <label>Source / reason for these corrections<input required maxLength={500} placeholder="Example: verified against Leads received report" value={reference} onChange={e=>setReference(e.target.value)}/></label><button className="op-primary" disabled={!changed.length}>{busy?'Saving…':`Save ${changed.length} date corrections`}</button></fieldset><p role="status">{message}</p></form></section>;
}
