'use client';
import {useState} from 'react';
import {ReportImport} from './report-import';
const categories=[['dollars','Aged dollars · 40%'],['jobs','Aged jobs · 20%'],['quality','Guild Quality · 40%']] as const;
function blank(period:string){return {period,pool:0,dollars:[0,0,0,0],jobs:[0,0,0,0],quality:[4,3.8,3.7,3.6,3.5],payouts:{dollars:[0,0,0,0,0,0],jobs:[0,0,0,0,0,0],quality:[0,0,0,0,0,0]}}}
function editable(c:any,period:string){if(!c)return blank(period);return {...c,payouts:c.payouts||Object.fromEntries(categories.map(([key])=>[key,[1.2,1,.75,.5,.25,0].map(n=>Math.round(c.pool*(key==='jobs'?.2:.4)*n*100)/100)]))}}
const money=(value:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(value)||0);
function threshold(config:any,key:string,index:number){
 if(key==='quality')return index<5?`Score ${Number(config.quality[index]).toFixed(2)} or higher`:`Below ${Number(config.quality[4]).toFixed(2)}`;
 if(index===0)return 'Zero aged';
 if(index===5)return `Above ${Number(config[key][3]).toLocaleString()}`;
 return `Up to ${Number(config[key][index-1]).toLocaleString()}`;
}
export function BonusThresholds({config,period,onEdit}:any){
 if(!config)return <section className="live-bonus-thresholds"><p>No thresholds are configured for the bonus period ending {period}.</p>{onEdit&&<button className="op-primary" onClick={onEdit}>Edit bonus settings</button>}</section>;
 return <section className="live-bonus-thresholds"><div className="op-section-head"><div><h2>Bonus tiers</h2><p>Read-only thresholds for the bonus period ending {config.period}.</p></div>{onEdit&&<button className="op-primary" onClick={onEdit}>Edit bonus settings</button>}</div><p>Base regional bonus pool: <strong>{money(config.pool)}</strong></p>{categories.map(([key,title])=><section key={key}><h3>{title}</h3><div className="live-import-scroll"><table><thead><tr><th>Tier</th><th>Threshold</th><th>Category payout</th></tr></thead><tbody>{[0,1,2,3,4,5].map(i=><tr key={i}><td>{i+1}</td><td>{threshold(config,key,i)}</td><td>{money(config.payouts?.[key]?.[i])}</td></tr>)}</tbody></table></div></section>)}</section>
}
export function BonusSettings({data,change,onImported}:any){
 const [draft,setDraft]=useState<any>(()=>editable(data.config,data.metrics.period.end)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const update=(key:string,index:number,value:string,payout=false)=>{setDraft((old:any)=>{if(payout){const values=[...old.payouts[key]];values[index]=value===''?'':Number(value);return {...old,payouts:{...old.payouts,[key]:values}}}const values=[...old[key]];values[index]=value===''?'':Number(value);return {...old,[key]:values}})};
 return <section className="op-panel live-bonus-settings"><h2>Bonus & Threshold Settings</h2><p>Administrator controls for each bonus month. Enter the actual dollar payout for each category; the total bonus estimate adds the three applicable payouts.</p><ReportImport kind="bonus" onBonus={v=>{setDraft(v);setMessage('Imported values are not saved yet. Review below.')}}/><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{await change('configure',draft);setMessage('Bonus targets and category payouts saved.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><fieldset disabled={busy}><div className="op-form"><label>Bonus period ending Tuesday<input type="date" required value={draft.period} onChange={e=>{const period=e.target.value;setDraft(editable(data.bonusConfigs?.find((c:any)=>c.period===period),period))}}/></label><label>Base regional bonus pool ($)<input type="number" min="0" step=".01" required value={draft.pool} onChange={e=>setDraft({...draft,pool:Number(e.target.value)})}/></label></div><p>Changing the base pool does not overwrite your category payouts. Update those amounts below to match the approved report.</p>{categories.map(([key,title])=><section key={key}><h3>{title}</h3><div className="live-import-scroll"><table><thead><tr><th>Threshold</th><th>Category payout ($)</th></tr></thead><tbody>{[0,1,2,3,4,5].map(i=><tr key={i}><td>{key==='quality'?(i<5?<label>Score at least <input aria-label={`${title} minimum tier ${i+1}`} type="number" step=".01" min="0" max="4" required value={draft.quality[i]} onChange={e=>update(key,i,e.target.value)}/></label>:<>Below {draft.quality[4]}</>):i===0?'Zero aged':i===5?<>Above {draft[key][3]}</>:<label>Up to <input aria-label={`${title} maximum tier ${i}`} type="number" min="0" step={key==='jobs'?'1':'.01'} required value={draft[key][i-1]} onChange={e=>update(key,i-1,e.target.value)}/></label>}</td><td><input aria-label={`${title} payout tier ${i+1}`} type="number" min="0" step=".01" required value={draft.payouts[key][i]} onChange={e=>update(key,i,e.target.value,true)}/></td></tr>)}</tbody></table></div></section>)}<p>September’s source form lists a $0 GQ payout for 3.50–3.59, despite a 0.25 multiplier. Imported payouts preserve the printed amounts. Individual service-level adjustments are excluded.</p>{error&&<p role="alert" className="op-red">{error}</p>}{message&&<p role="status">{message}</p>}<button className="op-primary" disabled={busy}>{busy?'Saving…':'Save bonus settings'}</button></fieldset></form><h3>Guild Quality report imports</h3><ReportImport kind="guild" onImported={onImported}/></section>
}
