'use client';
import {recordFields,profileFields,historyDateFields,type CustomerRecord} from '@/lib/customer-record';
import {formatPhone} from '@/lib/phone';
type Props={job:any;record:CustomerRecord;editing:boolean;onChange:(record:CustomerRecord)=>void};
const labels=Object.fromEntries([...recordFields,...profileFields,...historyDateFields]);
export function CustomerProfileOverview({job,record,editing,onChange}:Props){
 function field(key:keyof CustomerRecord){const value=String(record[key]??''),label=labels[key]||key;return <div className="customer-fact" key={key}><label htmlFor={'customer-'+key}>{label}</label>{editing?<input id={'customer-'+key} type={key.toLowerCase().includes('phone')?'tel':key==='email'?'email':'text'} maxLength={2000} value={value} onChange={e=>onChange({...record,[key]:key.toLowerCase().includes('phone')?formatPhone(e.target.value):e.target.value})}/>:<span>{value||'—'}</span>}</div>}
 function fact(label:string,value:any){return <div className="customer-fact" key={label}><span className="fact-label">{label}</span><span>{value||'—'}</span></div>}
 return <><div className="customer-overview-grid"><section className="customer-panel"><h2>Customer information</h2><div className="customer-facts">{field('customerId')}{fact('Customer',job.customer)}{fact('Job address',job.address)}{fact('Phone 1',formatPhone(job.phone||''))}{field('alternatePhone')}{field('thirdPhone')}{field('email')}{field('mailingAddress')}{field('zone')}{field('region')}{field('productType')}{field('units')}</div></section><section className="customer-panel"><h2>Job information <span className="customer-stage">{job.stage}</span></h2><div className="customer-facts">{fact('Job number',job.number)}{field('legacyJobId')}{fact('Contract amount',job.amount==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(job.amount))}{field('balanceDue')}{field('warehouseBay')}{field('loadId')}{field('salesRep')}{field('salesRepPhone')}{field('contractor')}{field('contractorPhone')}{field('completionContractor')}{fact('Field supervisor',job.supervisor)}{fact('Installer',job.crew)}{field('windowBrand')}{field('doorBrand')}{fact('Payment method',job.paymentMethod||record.paymentMethod)}{field('productDetails')}{field('callbackContractor')}{field('warrantyStatus')}</div></section></div><section className="customer-panel customer-date-panel"><h2>Date history</h2><div className="customer-dates">{fact('Materials received',job.received)}{fact('Installation scheduled',[job.install,job.installPeriod].filter(Boolean).join(' '))}{historyDateFields.map(([key,label])=><div className="customer-fact" key={key}><label htmlFor={'customer-'+key}>{label}</label>{editing?<input id={'customer-'+key} type="date" value={record[key]||''} onChange={e=>onChange({...record,[key]:e.target.value})}/>:<span>{record[key]||'—'}</span>}</div>)}</div></section></>
}
