'use client';
import {GuildQualitySummary} from '@/components/guild-quality-summary';
import {ScheduledVisits} from '@/components/scheduled-visits';
import {SignOutButton} from '@/components/auth-forms';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
export type TeamMember={id:string;email:string;name:string;role:string;supervisor_id:string|null;installer_code?:string|null;can_edit_jobs?:number;phone?:string;invitation_status?:string;active:number;login_ready?:number;must_change?:number};
async function data(url:string,options?:RequestInit){const response=await fetch(url,options),result=await response.json();if(!response.ok)throw Error(result.error||'Request failed');return result}
const post=(value:unknown)=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});
export function DeskTools({onTeam,onJob}:{onTeam:(members:TeamMember[])=>void;onJob:(id:string)=>void}){
 const [me,setMe]=useState<any>(null),[alerts,setAlerts]=useState<any[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[pushEnabled,setPushEnabled]=useState(false);
 async function loadAlerts(){try{setAlerts((await data('/api/notifications')).notifications)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{data('/api/me').then(d=>setMe(d.member)).catch(e=>setError(e.message));data('/api/team').then(d=>onTeam(d.members)).catch(e=>setError(e.message));loadAlerts();const timer=setInterval(loadAlerts,30000);return()=>clearInterval(timer)},[]);
 async function enablePush(){setError('');setMessage('');if(!('serviceWorker' in navigator)||!('PushManager' in window)||!('Notification' in window)){setError('On iPhone, add Production Desk to your Home Screen and open it there to enable notifications. Other devices need a browser that supports push notifications.');return;}setBusy(true);try{const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('Notifications are not enabled. Allow notifications in your browser or device settings, then try again.');const registration=await navigator.serviceWorker.register('/sw.js',{scope:'/',updateViaCache:'none'});await navigator.serviceWorker.ready;const {publicKey}=await data('/api/push');if(!publicKey)throw Error('Phone notifications are not configured yet.');const key=Uint8Array.from(atob(publicKey.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));const subscription=await registration.pushManager.getSubscription()||await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});await data('/api/push',post(subscription.toJSON()));setPushEnabled(true);setMessage('Phone notifications enabled on this device.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function action(id:string,action:string){try{await data('/api/notifications',post({id,action}));await loadAlerts()}catch(e){setError((e as Error).message)}}
 return <section className="desk-tools">{(me?.role==='admin'||me?.role==='supervisor')&&<nav className="guild-tabs" aria-label="Production Desk sections"><a href="/" aria-current="page">Dashboard</a><a href="/quality">Guild Quality Scores</a>{me.role==='admin'&&<a href="/accounts">Account management</a>}</nav>}<div className="desk-tools-bar">{(me?.role==='supervisor'||me?.role==='admin')&&<ScheduledVisits/>}{me?.role!=='supervisor'&&<a href="/installers/" className="app-link">Open Installer Desk ↗</a>}<Button variant="outline" disabled={busy} onClick={enablePush}>{pushEnabled?'Refresh phone notification setup':'Enable phone notifications'}</Button>{me&&['office','production_assistant'].includes(me.role)&&<a href="/change-password" className="app-link">Change password</a>}<SignOutButton/></div>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="notice" role="status">{message}</p>}{(me?.role==='supervisor'||me?.role==='admin')&&<GuildQualitySummary/>}<div className="supervisor-alerts"><h2>Installer reports {alerts.filter(n=>!n.read_at).length>0&&<span>({alerts.filter(n=>!n.read_at).length} unread)</span>}</h2>{alerts.length===0?<p>No installer reports yet.</p>:alerts.map(n=><div key={n.id} className={'supervisor-alert'+(!n.read_at?' unread':'')}><button onClick={()=>{onJob(n.job_id);action(n.id,'read')}}><strong>{n.message}</strong><span>{n.recipient_name||'Field supervisor'} · {new Date(n.created).toLocaleString()}</span><small>{n.push_status==='sent'?'Push accepted by notification service':n.push_status==='not_enabled'?'Supervisor has not enabled phone notifications':n.push_status==='failed'?'Phone push failed — in-app alert saved':'Push pending'}</small></button>{['failed','pending','not_enabled'].includes(n.push_status)&&<Button variant="outline" onClick={()=>action(n.id,'retry')}>Retry push</Button>}</div>)}</div></section>
}
