'use client';
import {useEffect,useState} from 'react';
import {qualityTone} from '@/lib/installer-quality';
type Installer={id:string;name:string;quality_score:number|null;quality_updated_at:string|null};
export function InstallerQuality({editable=false}:{editable?:boolean}){
 const [items,setItems]=useState<Installer[]>([]),[drafts,setDrafts]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/installer/quality',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setItems(d.installers);setError('');}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{load();const refresh=()=>{if(document.visibilityState==='visible')load()};document.addEventListener('visibilitychange',refresh);const timer=setInterval(refresh,60000);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',refresh)}},[]);
 async function save(id:string){setBusy(true);setMessage('');try{const r=await fetch('/api/installer/quality',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,score:Number(drafts[id])})}),d=await r.json();if(!r.ok)throw Error(d.error);setDrafts(v=>{const next={...v};delete next[id];return next});setMessage('Quality score saved.');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="installer-quality" aria-label="Installer quality scores"><div><h2>{editable?'My installers · Quality scores':'My quality score'}</h2><p>{editable?'Set the current score for each installer assigned to you.':'Updated by your assigned field supervisor.'}</p></div>{loading&&<p>Loading score…</p>}{error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!loading&&!error&&items.length===0&&<p>{editable?'No installers assigned to you.':'Not rated yet.'}</p>}{items.map(item=><div className="quality-row" key={item.id}>{editable&&<strong>{item.name}</strong>}<div className={'quality-value '+qualityTone(item.quality_score)}><strong>{item.quality_score===null?'Not rated':item.quality_score.toFixed(2)}</strong><span>{item.quality_score===null?'Awaiting supervisor score':item.quality_score<3.60?'Below 3.60':'3.60 or above'}</span></div>{item.quality_updated_at&&<small>Updated {new Date(item.quality_updated_at).toLocaleDateString()}</small>}{editable&&<form onSubmit={e=>{e.preventDefault();save(item.id)}}><label>Quality score for {item.name}<input type="number" min="0" max="100" step="0.01" required value={drafts[item.id]??(item.quality_score?.toFixed(2)||'')} onChange={e=>setDrafts(v=>({...v,[item.id]:e.target.value}))}/></label><button disabled={busy||drafts[item.id]===undefined||drafts[item.id]===''}>{busy?'Saving…':'Save score'}</button></form>}</div>)}</section>
}
