'use client';
import {SignaturePad} from './signature-pad';
import {useState} from 'react';
import {leadStatements} from '@/lib/lead-form';
import {printLeadRenovation} from '@/lib/print-lead-renovation';
export function LeadRenovation({j,me,profile,save}:any){
 const record=j.operations?.leadRenovation;
 const [answers,setAnswers]=useState<boolean[]>(record?.answers||Array(13).fill(true)),[signatureDataUrl,setSignatureDataUrl]=useState(record?.signatureDataUrl||profile?.savedDrawnSignature||''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <>{record&&<div className="op-section-head"><strong>Lead Renovation · Signed</strong><button className="live-button" type="button" onClick={()=>{try{printLeadRenovation(record)}catch(e){setError((e as Error).message)}}}>Print Lead Reno Sheet</button></div>}<details className="op-disclosure" open={!record}><summary>Lead Renovation Procedures Record {record?'✓ Signed':'— Required'}</summary><p>{j.customer} · #{j.number} · {j.address}, {j.city} {j.state} {j.zip}</p>{record&&<><p>Signed by {record.signature} · EPA #{record.epaCertification}</p></>}{error&&<p role="alert" className="op-red">{error}</p>}{me.role==='installer'?<form className="op-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);setBusy(true);setError('');try{if(!signatureDataUrl)throw Error('Draw your signature before saving.');await save('leadRenovation',{answers,signature:profile?.renovatorName||me.name,signatureDataUrl,confirmed:f.has('confirmed'),saveSignature:f.has('saveSignature')});form.reset()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><fieldset disabled={busy}><p>Renovator: {profile?.renovatorName||me.name} · Renovator ID #: {profile?.renovatorId||'Not recorded'}</p><p>EPA Certification #: {profile?.epaCertification||'Add in your installer profile before signing.'}</p><p>Answers start at Yes. Review each answer and change it where necessary before signing.</p>{leadStatements.map((t,i)=><div key={t}>{i===0?<h3>EPA Credentials</h3>:i===1?<h3>Determination of Renovation Procedures</h3>:i===2?<h3>Renovation Procedure Check List</h3>:i===12?<h3>Customer Copy</h3>:null}<p>{t}</p>{i===1&&<p className="op-muted">The home and work areas were inspected by a Certified EPA Lead-Safe Renovator. If Yes, answer every checklist item below. If No, you certify that standard installation procedures will not disturb potential lead paint.</p>}<div style={{display:'flex',gap:20}}>{[true,false].map(v=><label key={String(v)} className="op-check"><input type="radio" name={'lead-answer-'+i} checked={answers[i]===v} onChange={()=>setAnswers(a=>a.map((x,n)=>n===i?v:x))}/>{v?'Yes':'No'}</label>)}</div></div>)}<SignaturePad value={signatureDataUrl} onChange={setSignatureDataUrl}/ ><label className="op-check"><input type="checkbox" name="saveSignature" defaultChecked/>Save my signature for future forms</label><label className="op-check"><input type="checkbox" name="confirmed" required/>I reviewed these answers, certify this form is truthful and accurate, and apply my electronic signature to this job.</label><button className="op-primary">{busy?'Saving…':'Sign and save form'}</button></fieldset></form>:!record?<p>Awaiting the assigned installer’s signed form.</p>:null}</details></>;
}
