'use client';
import {useState} from 'react';
import {leadStatements} from '@/lib/lead-form';
const escapeHtml=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function printForm(r:any){
 const w=window.open('','_blank');if(!w)throw Error('Allow pop-ups to print this form.');
 const field=(l:string,v:any)=>'<p><b>'+l+'</b> '+escapeHtml(v)+'</p>';
 w.document.write('<!doctype html><html><head><title>Lead Renovation Procedures Record</title><style>@page{size:letter portrait;margin:0}*{box-sizing:border-box}body{margin:0;font:11pt Arial;color:#000}.sheet{padding:.6in .65in}h1{text-align:center;font-size:21pt}h2{font-size:14pt;margin-top:20px}p{margin:8px 0}.answer{margin:9px 0;break-inside:avoid}button{margin:12px}@media print{button{display:none}}</style></head><body><button onclick="window.print()">Print / Save PDF</button><main class="sheet"><h1>Lead Renovation Procedures Record</h1>'+field('Customer ID #:',r.customerId)+field('Customer Name:',r.customerName)+field('Street Address:',r.address)+field('City / State / Zip:',[r.city,r.state,r.zip].join(' '))+field('Renovator Name:',r.renovatorName)+field('Renovator ID #:',r.renovatorId)+field('EPA Certification #:',r.epaCertification)+leadStatements.map((t,i)=>(i===0?'<h2>EPA Credentials</h2>':i===1?'<h2>Determination of Renovation Procedures</h2><p>The home and work areas were inspected by a Certified EPA Lead-Safe Renovator.</p>':i===2?'<h2>Renovation Procedure Check List</h2>':i===12?'<h2>Customer Copy</h2>':'')+'<div class="answer">'+(r.answers[i]?'☑ Yes ☐ No':'☐ Yes ☑ No')+' &nbsp; '+escapeHtml(t)+'</div>').join('')+'<p>I certify that I have completed this form truthfully and accurately.</p>'+field('Renovator electronic signature:',r.signature)+field('Signed:',new Date(r.signedAt).toLocaleString('en-US',{timeZone:'America/New_York'}))+'</main></body></html>');w.document.close();
}
export function LeadRenovation({j,me,profile,save}:any){
 const record=j.operations?.leadRenovation;
 const [answers,setAnswers]=useState<boolean[]>(record?.answers||Array(13).fill(true)),[signature,setSignature]=useState(record?.signature||profile?.savedSignature||''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <details className="op-disclosure" open={!record}><summary>Lead Renovation Procedures Record {record?'✓ Signed':'— Required'}</summary><p>{j.customer} · #{j.number} · {j.address}, {j.city} {j.state} {j.zip}</p>{record&&<><p>Signed by {record.signature} · EPA #{record.epaCertification}</p><button className="live-button" type="button" onClick={()=>{try{printForm(record)}catch(e){setError((e as Error).message)}}}>Print / Save PDF</button></>}{error&&<p role="alert" className="op-red">{error}</p>}{me.role==='installer'?<form className="op-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);setBusy(true);setError('');try{await save('leadRenovation',{answers,signature,confirmed:f.has('confirmed'),saveSignature:f.has('saveSignature')});form.reset()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><fieldset disabled={busy}><p>Renovator: {profile?.renovatorName||me.name} · Renovator ID #: {profile?.renovatorId||'Not recorded'}</p><p>EPA Certification #: {profile?.epaCertification||'Add in your installer profile before signing.'}</p><p>Answers start at Yes. Review each answer and change it where necessary before signing.</p>{leadStatements.map((t,i)=><div key={t}>{i===0?<h3>EPA Credentials</h3>:i===1?<h3>Determination of Renovation Procedures</h3>:i===2?<h3>Renovation Procedure Check List</h3>:i===12?<h3>Customer Copy</h3>:null}<p>{t}</p>{i===1&&<p className="op-muted">The home and work areas were inspected by a Certified EPA Lead-Safe Renovator. If Yes, answer every checklist item below. If No, you certify that standard installation procedures will not disturb potential lead paint.</p>}<div style={{display:'flex',gap:20}}>{[true,false].map(v=><label key={String(v)} className="op-check"><input type="radio" name={'lead-answer-'+i} checked={answers[i]===v} onChange={()=>setAnswers(a=>a.map((x,n)=>n===i?v:x))}/>{v?'Yes':'No'}</label>)}</div></div>)}<label>Renovator electronic signature — type your full name<input required minLength={2} maxLength={150} value={signature} onChange={e=>setSignature(e.target.value)}/></label><label className="op-check"><input type="checkbox" name="saveSignature" defaultChecked/>Save my signature for future forms</label><label className="op-check"><input type="checkbox" name="confirmed" required/>I reviewed these answers, certify this form is truthful and accurate, and apply my electronic signature to this job.</label><button className="op-primary">{busy?'Saving…':'Sign and save form'}</button></fieldset></form>:!record?<p>Awaiting the assigned installer’s signed form.</p>:null}</details>;
}
