'use client';
import {useCallback,useEffect,useState} from 'react';
import {Clock,UsersRound,LayoutDashboard,CalendarDays,FolderOpen,ClipboardCheck,MapPin,Star,Plug,Settings,ChevronLeft,ChevronRight,LogOut,Plus,X} from 'lucide-react';
import {aging,addDays,localDay,dayDifference,allowedMaterials} from '@/lib/operations';
import {datesFor,moveCalendar,type ScheduleViewMode} from '@/app/operations-preview/schedule-view';
import {useSessionTheme} from './account-theme';
import {AccountSettings} from './account-settings';
import AccountManagement from './account-management';
import {JobVisits} from './job-visits';
import {uploadAttachment} from '@/lib/upload-client';
import {requiredReportKinds,reportLabels} from '@/lib/installer-workflow';
import {installAppointments,hourLabel} from '@/lib/install-calendar';
import {AgingReport} from './aging-report';
import {InstallerDirectory} from './installer-directory';
import {SurveyDetails} from './survey-details';
import {BonusSettings} from './bonus-settings';
import {ReportImport} from './report-import';
import {formatPhone} from '@/lib/phone';
import {LeadsScan} from './leads-scan';
import {recordFields,profileFields,historyDateFields} from '@/lib/customer-record';
import '@/app/operations-preview/preview.css';
import './live-operations.css';

const currency=(n:any)=>n==null?'Not recorded':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const labels:Record<string,string>={Received:'RCVD',Production:'PROD',InProgress:'IN PROGRESS',Incomplete:'INC',Closed:'COMP',Ordered:'ORD',UTI:'UTI',COLL:'COLL',SVC:'SVC'};
const paymentMethods=[{id:'FNC',name:'Finance (FNC)'},{id:'CHK',name:'Check (CHK)'},{id:'CC',name:'Credit Card (CC)'},{id:'AQUA',name:'Aqua Financing (AQUA)'},{id:'PO',name:'Purchase Order (PO)'}];
const brands=['Simonton','Plygem','Wincore','Thermatru','Diamond Screens','AMI','CWS'];
const materialTypes=['Window','SPD','Entry Door','Diamond Screen'];
const themeMarks:Record<string,[string,string]>={gators:['/florida-gators-logo.png','Florida Gators'],fsu:['/fsu-logo.png','Florida State Seminoles'],mexico:['/flag-mx.svg','Mexico'],brazil:['/flag-br.svg','Brazil'],cuba:['/flag-cu.svg','Cuba'],usa:['/flag-us.svg','United States']};
export async function liveApi(path:string,body?:any){const response=await fetch(path,body===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed.');return data}
const field=(form:FormData,key:string)=>String(form.get(key)||'');
const jobDate=(j:any)=>String(j.stage==='Incomplete'?j.incompleteSince:['Production','InProgress'].includes(j.stage)?j.installed:j.received||j.install||'9999-12-31').slice(0,10);
function Form({onSave,children}:{onSave:(v:FormData)=>Promise<void>;children:React.ReactNode}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <form className="op-form" onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);setError('');setBusy(true);try{await onSave(data)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><fieldset disabled={busy}>{children}{error&&<p className="op-red" role="alert">{error}</p>}<button className="op-primary" disabled={busy}>{busy?'Saving…':'Save'}</button></fieldset></form>}
function Input({name,label,value='',type='text',required=false,...rest}:any){return <label>{label}<input name={name} type={type} defaultValue={value??''} required={required} {...rest}/></label>}
function Select({name,label,value='',items,required=true}:any){return <label>{label}<select name={name} defaultValue={value} required={required}><option value="">Select…</option>{items.map((v:any)=><option key={v.id??v} value={v.id??v}>{v.name??v}</option>)}</select></label>}
function Text({name,label,value=''}:any){return <label>{label}<textarea name={name} defaultValue={value}/></label>}
function QualityValue({score}:any){return <span className={score!=null&&score<3.6?'op-red':'live-green'}>{score==null?'Not recorded':score.toFixed(2)}{score===4?' ★':''}<small>{score==null?'':score<3.6?'Poor':score<3.7?'Fair':score<3.8?'Good':'Outstanding'}</small></span>}

export default function LiveOperations(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[tab,setTab]=useState('Overview'),[selected,setSelected]=useState<string|null>(null),[adding,setAdding]=useState(false),[collapsed,setCollapsed]=useState(false),[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState('ALL'),[notices,setNotices]=useState<any[]>([]),[saving,setSaving]=useState(false);
 const {theme}=useSessionTheme(),mark=themeMarks[theme];
 const load=useCallback(async()=>{try{const [d,n]=await Promise.all([liveApi('/api/operations'),liveApi('/api/notifications')]);setData(d);setTab(prev=>d.me.role==='installer'&&!['Overview','Schedule','Settings'].includes(prev)?'Overview':prev==='Connections'&&d.me.role!=='admin'?'Overview':prev);setNotices(n.notifications);setError('')}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const initial=params.get('tab');if(['Overview','Schedule','Jobs','Aging reports','Approvals','Job visits','Quality','Installers','Connections','Settings'].includes(initial||''))setTab(initial!);if(params.get('job'))setSelected(params.get('job'));load();const id=setInterval(()=>{if(!document.hidden)load()},60000);return()=>clearInterval(id)},[load]);
 const change=async(action:string,values:any,job?:any)=>{setSaving(true);try{await liveApi('/api/operations',{action,data:values,jobId:job?.id,version:job?.version});await load()}finally{setSaving(false)}};
 const clickAction=async(action:string,values:any,j:any)=>{try{await change(action,values,j)}catch(e){setError((e as Error).message)}};
 if(!data)return <main className="workspace"><h1>Production Desk</h1><p role="status">{error||'Loading your workspace…'}</p>{error&&<button onClick={load}>Try again</button>}</main>;
 const {me,jobs,team,today,metrics}=data,installer=me.role==='installer',review=data.canReview;
 const current=jobs.find((j:any)=>j.id===selected),filtered=jobs.filter((j:any)=>[j.customer,j.number,j.address,j.crew].join(' ').toLowerCase().includes(query.toLowerCase()));
 const nav:any[]=[['Overview',LayoutDashboard],['Schedule',CalendarDays],...(!installer?[['Jobs',FolderOpen],['Aging reports',Clock],['Approvals',ClipboardCheck],['Job visits',MapPin],['Quality',Star],['Installers',UsersRound]]:[]),...(me.role==='admin'?[['Connections',Plug]]:[]),['Settings',Settings]];
 const approvals=jobs.filter((j:any)=>j.operations?.pendingSchedule||j.operations?.report?.pending||j.operations?.requests?.some((r:any)=>r.status==='Pending'));
 return <div className={'op live-operations '+(collapsed?'op-collapsed':'')}>
  <aside className="op-sidebar"><a className="op-brand" href="/"><img className="op-ww-logo" src="/ww-round-logo.png" alt="Window World"/><div>PRODUCTION DESK<small>WINDOW WORLD · TAMPA BAY</small></div></a>{mark&&<div className="op-team-mark"><img src={mark[0]} alt={mark[1]}/><span>{mark[1]}</span></div>}<button className="op-collapse" onClick={()=>setCollapsed(!collapsed)} aria-label={collapsed?'Expand navigation':'Collapse navigation'}>{collapsed?<ChevronRight size={18}/>:<ChevronLeft size={18}/>}</button><div className="op-side-label">FIELD OPERATIONS</div><nav>{nav.map(([name,Icon])=><button key={name} className={tab===name?'active':''} title={name} onClick={()=>setTab(name)}><Icon size={19}/><span className="op-nav-label">{name}</span></button>)}</nav><div className="op-sidebar-bottom">{me.name}<br/>{me.email}</div><button className="op-collapse" onClick={async()=>{await liveApi('/api/auth/logout',{});location.href='/login'}}><LogOut size={16}/> <span className="op-nav-label">Sign out</span></button></aside>
  <div className="op-main"><header className="op-toolbar"><span>Tampa Bay / <b>{tab}</b></span><span>{me.name} · {installer?'Installer':me.role==='admin'?'Administrator':me.role==='supervisor'?'Field Supervisor':'Production Assistant'}</span></header><main className="op-content">
   {error&&<div className="op-notice op-red" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
   <div className="op-heading"><h1>{tab==='Overview'?'Field Operations':tab}</h1><button className="live-button" onClick={load}>Refresh</button></div>
   {tab==='Overview'&&<>
    {!!notices.length&&<details className="op-disclosure"><summary>Job alerts ({notices.length})</summary>{notices.map(n=><div className="live-alert" key={n.id}><button onClick={()=>setSelected(n.job_id)}>{n.message}</button><button onClick={async()=>{try{await liveApi('/api/notifications',{id:n.id,action:'read'});await load()}catch(e){setError((e as Error).message)}}}>Read</button></div>)}</details>}
    {!installer&&<>{review&&<section className="op-score"><div><h2>Bonus Metrics</h2><p>Bonus Period: {metrics.period.start} – {metrics.period.end}</p></div><div><span>Bonus Pool · Current estimate</span><strong>{metrics.estimate==null?'Not available':currency(metrics.estimate)}</strong><small>{metrics.estimate==null?'Configure targets and resolve missing metrics.':'Before individual payout adjustments'}</small></div></section>}<div className="op-metrics"><button onClick={()=>setTab('Jobs')}><span>Aged amount due{review?' · 40%':''}</span><strong>{currency(metrics.amount)}</strong><small>{metrics.missing?`${metrics.missing} missing balances excluded`:'Known balances'}{metrics.unknownDates?` · ${metrics.unknownDates} missing aging dates`:''}</small></button><button onClick={()=>setTab('Jobs')}><span>Aged jobs{review?' · 20%':''}</span><strong>{metrics.count}</strong><small>Includes jobs with $0 due</small></button><button onClick={()=>setTab('Quality')}><span>Guild Quality{review?' · 40%':''}</span><strong><QualityValue score={metrics.score}/></strong><small>{metrics.surveys} surveys in period</small></button></div></>}
    {installer?<Calendar jobs={jobs} installer today={today} onOpen={setSelected}/>:<>{data.canEdit&&<div className="live-pipeline-action"><button className="op-primary" onClick={()=>setAdding(true)}><Plus size={16}/> Add Customer</button></div>}<JobList jobs={filtered} today={today} query={query} setQuery={setQuery} onOpen={setSelected} pipeline/></>} 
   </>}
   {tab==='Schedule'&&<Calendar jobs={jobs} team={team} crewColors={data.crewColors} saveCrewColors={(colors:any)=>change('crewColors',colors)} installer={installer} today={today} onOpen={setSelected}/>} 
   {tab==='Jobs'&&<>{data.canEdit&&<div className="live-pipeline-action"><button className="op-primary" onClick={()=>setAdding(true)}><Plus size={16}/> Add Customer</button></div>}<JobList jobs={filtered} today={today} query={query} setQuery={setQuery} onOpen={setSelected} statusFilter={statusFilter} setStatusFilter={setStatusFilter}/></>} 
   {tab==='Approvals'&&<section className="op-panel"><h2>Awaiting review</h2>{!approvals.length&&<p className="op-empty">No pending requests.</p>}{approvals.map((j:any)=><button className="op-appointment" key={j.id} onClick={()=>setSelected(j.id)}><strong>{j.customer}</strong><span>#{j.number} · Open to review</span></button>)}</section>}
   {tab==='Job visits'&&<Visits onOpen={setSelected}/>}
   {tab==='Quality'&&<Quality data={data} change={change} reload={load} onOpenJob={setSelected}/>}{tab==='Installers'&&!installer&&<InstallerDirectory onSaved={load}/>}
   {tab==='Aging reports'&&!installer&&<AgingReport jobs={jobs} today={today} onOpen={setSelected}/>}
   {tab==='Connections'&&me.role==='admin'&&<Connections/>}
   {tab==='Settings'&&<section className="op-panel live-settings">{me.role==='admin'?<><AccountManagement me={me}/><BonusSettings data={data} change={change} onImported={load}/></>:<><AccountSettings id={me.id} name={me.name} email={me.email} installer={installer} onSaved={load}/><a className="live-button" href="/change-password">Change password</a></>}</section>}
  </main></div>
  {adding&&<Drawer title="Add Customer" onClose={()=>setAdding(false)}><CustomerForm team={team} onSave={async (v:any)=>{await change('create',v);setAdding(false)}}/></Drawer>}
  {current&&<Drawer title={current.customer} onClose={()=>setSelected(null)}><JobFile key={current.id} j={current} data={data} change={change} clickAction={clickAction} saving={saving}/></Drawer>}
 </div>;
}
function Drawer({title,onClose,children}:any){useEffect(()=>{const before=document.body.style.overflow;document.body.style.overflow='hidden';const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=before;document.removeEventListener('keydown',key)}},[onClose]);return <div className="op-overlay"><section className="op-detail" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button aria-label="Close job file" onClick={onClose}><X/></button></header><div className="op-detail-body">{children}</div></section></div>}
function JobList({jobs,today,query,setQuery,onOpen,pipeline=false,statusFilter='ALL',setStatusFilter}:any){const statuses:Record<string,string>={ORD:'Ordered',RCVD:'Received',PROD:'Production','IN PROGRESS':'InProgress',INC:'Incomplete',COMP:'Closed',COLL:'COLL',UTI:'UTI',SVC:'SVC'};const rows=jobs.filter((j:any)=>(!pipeline||j.stage!=='Closed')&&(statusFilter==='ALL'||j.stage===statuses[statusFilter])).sort((a:any,b:any)=>jobDate(a).localeCompare(jobDate(b))||String(a.number).localeCompare(String(b.number)));return <section className="op-panel"><div className="op-section-head"><h2>{pipeline?'Production Pipeline':'Jobs'}</h2><span>{rows.length} jobs</span></div><div className="op-filters"><input aria-label="Search jobs" placeholder="Customer, customer ID, address or installer…" value={query} onChange={e=>setQuery(e.target.value)}/>{!pipeline&&<select aria-label="Filter jobs by status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="ALL">All statuses</option>{Object.keys(statuses).map(s=><option key={s}>{s}</option>)}</select>}</div>{rows.map((j:any)=>{const a=aging(j,today);return <button className={'op-job live-job '+(!pipeline&&a.aged?'live-aged':'')} key={j.id} onClick={()=>onOpen(j.id)}><div><small>#{j.number}</small><strong>{j.customer}</strong><small>{j.address}</small></div><div><span className={'op-badge '+(a.aged?'danger':a.remaining!=null&&a.remaining<8?'warn':'')}>{a.aged?`${labels[j.stage]} · ${a.days} days`:a.remaining!=null?`${a.remaining} days to Aged`:labels[j.stage]||j.stage}</span><small>{j.operations?.report?.pending?'Report awaiting approval':labels[j.stage]||j.stage}</small></div><div><strong>{currency(j.amount)}</strong><small>Amount due</small></div><div><span>{j.crew||'Unassigned'}</span><small>{j.install?`${j.install} ${j.installPeriod||''}`:'Not scheduled'}</small></div></button>})}{!rows.length&&<p className="op-empty">No jobs match this view.</p>}</section>}
function Calendar({jobs,team=[],crewColors={},saveCrewColors,installer,today,onOpen}:any){const [day,setDay]=useState(today),[view,setView]=useState<ScheduleViewMode>('Day'),[colors,setColors]=useState<any>(crewColors);useEffect(()=>setColors(crewColors||{}),[crewColors]);const dates=datesFor(day,installer?'Day':view);const appointments=jobs.flatMap((j:any)=>[...installAppointments(j,dates),...(j.operations?.services||[]).map((s:any)=>({...j,...s,id:j.id,service:true}))]);return <section className="op-panel"><div className="op-section-head"><h2>{installer?'My schedule':'Installation schedule'}</h2>{!installer&&<input aria-label="Calendar date" type="date" value={day} onChange={e=>setDay(e.target.value||today)}/>}</div><div className="op-schedule-actions"><button onClick={()=>setDay(today)}>Today</button><button onClick={()=>setDay(addDays(today,1))}>Tomorrow</button>{!installer&&<>{(['Day','Week','Month'] as ScheduleViewMode[]).map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v}</button>)}<button onClick={()=>setDay(moveCalendar(day,view,-1))}>Previous</button><button onClick={()=>setDay(moveCalendar(day,view,1))}>Next</button></>}</div>{!installer&&<><p className="op-muted">Open any job file → Schedule Work to assign an installer and future date.</p><details className="live-crew-colors"><summary>Crew calendar colors</summary><div>{team.filter((m:any)=>m.role==='installer'&&m.active!==0).map((m:any)=><label key={m.id}><input type="color" value={colors[m.id]||'#2879c8'} onChange={e=>setColors({...colors,[m.id]:e.target.value})}/>{m.name}</label>)}</div><button className="live-button" onClick={()=>saveCrewColors(colors)}>Save my crew colors</button></details></>}<div className={'op-calendar-grid '+(view==='Day'||installer?'':view.toLowerCase())}>{dates.map(d=><section className="op-calendar-day" key={d}><header><strong>{new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(d+'T12:00Z'))}</strong></header>{appointments.filter((j:any)=>j.date===d).sort((a:any,b:any)=>(a.time||(a.period==='PM'?'12:00':'00:00')).localeCompare(b.time||(b.period==='PM'?'12:00':'00:00'))||(a.stop||1)-(b.stop||1)).map((j:any,i:number)=><button key={j.id+i} style={{borderLeftColor:colors[j.installerId]||'#2879c8'}} onClick={()=>onOpen(j.id)}><b>{j.time?hourLabel(j.time):j.period} · {j.service?'Service':`Stop ${j.stop||1}`} · {j.crew}</b><span>{j.customer}</span>{installer&&j.multi&&!j.service&&<strong className="op-multi-day">MULTI-DAY ({j.daysLeft})</strong>}<small>{j.service?j.details:j.instructions}</small></button>)}{!appointments.some((j:any)=>j.date===d)&&<small>No appointments.</small>}</section>)}</div></section>}

function CustomerForm({j,team,onSave,admin=false}:any){const [product,setProduct]=useState(j?.product||'Windows');return <Form onSave={async f=>{const keys=['bay','assignedInstallerId','reorderDate','lastEstimatedShipDate','loadBrands','number','customer','address','city','state','zip','phone','customerEmail','product','supervisorId','salesRep','salesRepPhone','salesRepEmail','notes','instructions','reorder','paymentMethod'];const values:any=Object.fromEntries(keys.map(k=>[k,field(f,k)]));if(!j){delete values.reorder;values.permitNumber=field(f,'permitNumber');values.buildingDepartment=field(f,'buildingDepartment');values.permitExpiration=field(f,'permitExpiration');values.permitReceived=false;}values.reportedUnits=field(f,'reportedUnits')===''?null:Number(field(f,'reportedUnits'));values.phone=formatPhone(values.phone);values.salesRepPhone=formatPhone(values.salesRepPhone);values.screenCount=Number(field(f,'screenCount')||0);values.windowCount=Number(field(f,'windowCount')||0);values.slidingDoors=Number(field(f,'slidingDoors')||0);values.entryDoorCount=Number(field(f,'entryDoorCount')||0);if(!j){values.amount=field(f,'amount')===''?null:Number(field(f,'amount'));values.contractAmount=field(f,'contractAmount')===''?null:Number(field(f,'contractAmount'));values.stage='Ordered';values.received='';values.installed='';values.incompleteSince=''}else values.number=j.number;if(j&&!admin)delete values.paymentMethod;await onSave(values)}}>
 <LeadsScan team={team} customerNumber={j?.number} onApply={(values:any)=>{if(values.product)setProduct(values.product)}}/><Input label="Customer ID (separate IDs for Windows and Entry Doors)" name="number" value={j?.number} required disabled={!!j}/><Input label="Customer name" name="customer" value={j?.customer} required/><Input label="Street address" name="address" value={j?.address} required/><Input label="City" name="city" value={j?.city} required/><Input label="State" name="state" value={j?.state||'FL'} required/><Input label="ZIP code" name="zip" value={j?.zip} pattern="[0-9]{5}(-[0-9]{4})?" required/><Input label="Phone" name="phone" value={j?.phone} type="tel" placeholder="(555)-555-5555" onInput={(e:any)=>e.currentTarget.value=formatPhone(e.currentTarget.value)} onBlur={(e:any)=>e.target.value=formatPhone(e.target.value)}/><Input label="Customer email" name="customerEmail" value={j?.customerEmail} type="email"/><label>Account type<select name="product" value={product} onChange={e=>setProduct(e.target.value)}>{['Windows','Entry Doors','Diamond Screens'].map(v=><option key={v}>{v}</option>)}</select></label>{product==='Windows'&&<><Input label="Number of windows" name="windowCount" value={j?.windowCount||0} type="number" min="0" max="999"/><Input label="Sliding Patio Doors (SPD)" name="slidingDoors" value={j?.slidingDoors||0} type="number" min="0" max="999"/></>}{product==='Entry Doors'&&<Input label="Number of entry doors" name="entryDoorCount" value={j?.entryDoorCount||0} type="number" min="0" max="999"/>}{product==='Diamond Screens'&&<Input label="Number of Screens" name="screenCount" value={j?.screenCount||0} type="number" min="0" max="999"/>}{(!j||admin)?<Select label="Payment method" name="paymentMethod" value={j?.paymentMethod} items={paymentMethods} required={false}/>:<p>Payment method: {j.paymentMethod||'Not recorded'} · Admin only may change this.</p>}<Select label="Field Supervisor" name="supervisorId" value={j?.supervisorId} items={team.filter((m:any)=>['supervisor','admin'].includes(m.role)&&m.active!==0)}/>
 {!j&&<><p className="op-callout">New customer jobs begin in ORD status. Use Material Receipt when the products arrive.</p><Input label="Permit number" name="permitNumber"/><Input label="Building Department" name="buildingDepartment"/><Input label="Permit expiration date" name="permitExpiration" type="date"/><Input label="Amount due" name="amount" type="number" min="0" step=".01"/><Input label="Contract price" name="contractAmount" type="number" min="0" step=".01"/></>}
 <Input label="Material Bay location" name="bay" value={j?.bay}/><Select label="Installer (Contractor in Leads)" name="assignedInstallerId" value={j?.installerId||''} required={false} items={team.filter((m:any)=>m.role==='installer'&&m.active!==0)}/><Input label="Reorder Date (starts INC aging)" name="reorderDate" type="date" max={localDay()} value={j?.reorderDate}/><Input label="Last Estimated Ship Date" name="lastEstimatedShipDate" type="date" value={j?.lastEstimatedShipDate}/><Input label="Brands from Load ID" name="loadBrands" value={j?.loadBrands}/><p>Plygem products are SPD. Simonton and Wincore may be windows or SPD. Confirm individual quantities when receiving.</p><Input label="Reported total units (breakdown unconfirmed)" name="reportedUnits" type="number" min="0" max="999" value={j?.reportedUnits}/><Input label="Sales representative" name="salesRep" value={j?.salesRep}/><Input label="Sales rep phone" name="salesRepPhone" value={j?.salesRepPhone} type="tel" placeholder="(555)-555-5555" onInput={(e:any)=>e.currentTarget.value=formatPhone(e.currentTarget.value)} onBlur={(e:any)=>e.target.value=formatPhone(e.target.value)}/><Input label="Sales rep email (for job alerts)" name="salesRepEmail" value={j?.salesRepEmail} type="email"/><Text label="Sales Notes" name="notes" value={j?.notes}/><Text label="Installer job instructions" name="instructions" value={j?.instructions}/>{j&&<Text label="Reorder information" name="reorder" value={j?.reorder}/>}
 </Form>}
function JobFile({j,data,change,clickAction,saving}:any){const {me,team,today}=data,isInstaller=me.role==='installer',review=data.canReview,o=j.operations||{},[editing,setEditing]=useState(false),[uploadError,setUploadError]=useState(''),[uploading,setUploading]=useState(false);const noOp=useCallback(()=>{},[]);
 const act=(a:string,v:any={})=>clickAction(a,v,j);const save=(a:string,v:any)=>change(a,v,j);
 return <><p>Installer: {j.crew||'Not assigned'}</p><p>Reorder Date: {j.reorderDate||'Not recorded'} · Last Estimated Ship Date: {j.lastEstimatedShipDate||'Not recorded'}</p><p>Load ID brands: {j.loadBrands||'Not recorded'} · Reported units: {j.reportedUnits??'Not recorded'} (confirm window/SPD breakdown)</p><p><span className="op-badge">{labels[j.stage]||j.stage}</span> Customer ID #{j.number}</p><a href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent([j.address,j.city,j.state,j.zip].filter(Boolean).join(', '))} target="_blank" rel="noreferrer">{[j.address,j.city,j.state,j.zip].filter(Boolean).join(', ')} ↗</a><div className="op-detail-status"><div><small>Customer phone</small><a href={'tel:'+j.phone}>{formatPhone(j.phone||'')||'Not recorded'}</a></div><div><small>Sales Rep</small><strong>{j.salesRep||'Not recorded'}</strong><br/><a href={'tel:'+j.salesRepPhone}>{formatPhone(j.salesRepPhone||'')}</a></div><div><small>Field Supervisor</small><strong>{j.supervisor||'Not assigned'}</strong></div><div><small>Products</small><strong>{j.importSource?.unitsUnconfirmed?`Report units: ${j.importSource.units} — window/SPD breakdown not confirmed. `:''}{j.windowCount||0} windows · {j.slidingDoors||0} SPD · {j.entryDoorCount||0} entry doors · {j.screenCount||0} screens</strong><br/><small>{j.materials?.length?j.materials.map((r:any)=>`${r.materialType} · ${r.brand} · Bay ${r.bay}`).join('; '):(j.brand||'Brand not recorded')}</small></div><div><small>Payment method</small><strong>{paymentMethods.find(p=>p.id===j.paymentMethod)?.name||j.paymentMethod||'Not recorded'}</strong></div><div><small>Materials received / Bay</small><strong>{j.received||'Not received'} · {j.bay||'No bay recorded'}</strong></div><div><small>Appointment</small><strong>{j.install?`${j.install}${j.installEnd&&j.installEnd!==j.install?' – '+j.installEnd:''} ${j.installTime?hourLabel(j.installTime):j.installPeriod||''} · Stop ${j.stopNumber||1}`:'Not scheduled'}</strong></div>{!isInstaller&&<div><small>Amount due / Contract price</small><strong>{currency(j.amount)} / {currency(j.contractAmount)}</strong></div>}</div>
 {j.importSource&&<p className="op-callout">Imported from {j.importSource.file}, page {j.importSource.page}. Names and notes may be clipped in the source. Missing address, permit, product breakdown and assignments need review. {j.stage==='Incomplete'&&!j.incompleteSince?'INC entry date is unconfirmed; excluded from aged totals until verified.':''}</p>}{data.canEdit&&<button className="live-button" onClick={()=>setEditing(!editing)}>{editing?'Cancel editing':'Update information'}</button>}{editing&&<CustomerForm key={j.version} j={j} team={team} admin={me.role==='admin'} onSave={async(v:any)=>{await save('edit',v);setEditing(false)}}/>}
 {data.canEdit&&<><details className="op-disclosure"><summary>1. Enter RCVD info {j.received?'✓':''}</summary><ReceiveForm j={j} save={save}/></details></>}<details className="op-disclosure"><summary>2. Permit {j.permitReceived?'✓':''}</summary><PermitDetails j={j}/>{data.canEdit&&<PermitForm j={j} save={save}/>}</details>
  {data.canEdit&&<details className="op-disclosure"><summary>3. Schedule Work {j.install?'✓':''}</summary>{o.pendingSchedule&&<div className="op-callout"><p>Pending: {o.pendingSchedule.date}{o.pendingSchedule.endDate&&o.pendingSchedule.endDate!==o.pendingSchedule.date?' – '+o.pendingSchedule.endDate:''} {o.pendingSchedule.time?hourLabel(o.pendingSchedule.time):o.pendingSchedule.period} · Requested by {o.pendingSchedule.requestedBy}</p>{review&&<div className="op-schedule-actions"><button disabled={saving} onClick={()=>act('approveSchedule')}>Approve schedule</button><button disabled={saving} onClick={()=>act('rejectSchedule')}>Decline</button></div>}</div>}<ScheduleForm j={j} team={team} today={today} save={save}/></details>}
 {review&&<section className="live-status-control"><h3>Production status</h3><p>Move a scheduled RCVD job to PROD to start its timer. Use IN PROGRESS only when installation lasts longer than one day. INC and COMP require an installer submission and Field Supervisor approval.</p><StatusForm j={j} save={save} admin={me.role==='admin'}/></section>}
 {review&&aging(j,today).missing&&<details className="op-disclosure"><summary>Confirm missing aging date</summary><p>Use the actual {j.stage==='Incomplete'?'date the account entered INC':j.stage==='Received'?'materials received date':'date production started'}. Do not substitute a scheduled appointment or reorder date.</p><Form onSave={async f=>save('agingDate',{date:field(f,'date'),reference:field(f,'reference')})}><Input label="Verified aging start date" name="date" type="date" max={today} required/><Input label="Source / verification note" name="reference" required/></Form></details>}
 <h3>Job instructions</h3><p className="op-instructions">{j.instructions||j.specialNotes||'No instructions recorded.'}</p>{j.scheduleInstructions&&<p className="op-instructions"><strong>Schedule instructions:</strong> {j.scheduleInstructions}</p>}
 <h3>Sales Photos</h3><Gallery attachments={(j.attachments||[]).filter((a:any)=>o.salesKeys?.includes(a.key)||(!o.salesKeys&&a.kind==='photos'))}/>{data.canEdit&&<label className="live-upload">{uploading?'Uploading…':'Add missing sales photo or document'}<input aria-label="Add sales photo or document" type="file" disabled={uploading} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);setUploadError('');try{const a=await uploadAttachment(j.id,'photos',file);await save('attach',a)}catch(e){setUploadError((e as Error).message)}finally{setUploading(false)}}}/></label>}{uploadError&&<p role="alert" className="op-red">{uploadError}</p>}<h3>Sales Notes</h3><p className="op-instructions">{j.notes||'No sales notes recorded.'}</p>{data.canEdit&&<details className="op-disclosure"><summary>Add or update Sales Notes</summary><Form onSave={async f=>save('edit',{notes:field(f,'notes')})}><Text name="notes" label="Sales Notes" value={j.notes}/></Form></details>}
 {!!o.issues?.length&&<section className="live-issues"><h3>! Reported issues</h3>{o.issues.map((i:any)=><p key={i.id}>{i.text}<small>{i.by} · {new Date(i.at).toLocaleString()}</small></p>)}</section>}
 {isInstaller&&<><details className="op-disclosure"><summary>Report Issue</summary><Form onSave={async f=>save('issue',{text:field(f,'text')})}><Text label="What needs the supervisor’s attention?" name="text"/></Form></details><details className="op-disclosure"><summary>Reorder information and previous job visits</summary><p><strong>Reorder information:</strong> {j.reorder||'None recorded.'}</p><JobVisits jobId={j.id} onBusy={noOp} onEditing={noOp}/></details></>}{(isInstaller||review)&&<section className="live-completion"><h3>Job Completion</h3><p>Select Complete or Incomplete and upload every required photo and certificate. Additional photos are optional.</p>{o.report?.pending?<p className="op-callout">✓ {o.report.status} result sent — your report was submitted and is waiting for Field Supervisor approval.</p>:o.report?.approved?<p className="op-callout">Your report was approved and the official job status was updated.</p>:(j.canReport||review)&&['Production','InProgress'].includes(j.stage)?<InstallerReport j={j} save={save}/>:<p className="op-muted">A Field Supervisor or Administrator must move this scheduled job to PROD before Job Completion becomes available.</p>}</section>}
 {me.role==='admin'&&<details className="op-disclosure"><summary>Admin closeout override · COMP / INC</summary><p>Move this job without the required photos or documents. This exception is recorded in job history.</p><Form onSave={async f=>{if(!window.confirm('Are you sure you want to close this job?'))return;await save('adminResult',{target:field(f,'target'),reason:field(f,'reason'),confirmed:true})}}><Select name="target" label="Result" items={[{id:'Closed',name:'COMP — Close job'},{id:'Incomplete',name:'INC — Mark incomplete'}]}/><Input name="reason" label="Reason for override" required/></Form></details>}<details className="op-disclosure"><summary>Installation photos and report</summary><Gallery attachments={(j.attachments||[]).filter((a:any)=>a.kind!=='visit'&&!o.salesKeys?.includes(a.key))}/>{o.report&&<><p>✓ {o.report.status} result sent · {o.report.pending?'Awaiting supervisor review':o.report.approved?'Approved and status updated':'Returned for correction'}</p><p>{o.report.reason}</p><p>{o.report.notes}</p>{review&&o.report.pending&&<div className="op-schedule-actions"><button disabled={saving} onClick={()=>act('reviewReport',{approve:true})}>Approve and move to {o.report.status==='Complete'?'COMP':'INC'}</button><button disabled={saving} onClick={()=>act('reviewReport',{approve:false})}>Return for correction</button></div>}</>}</details>
 {!isInstaller&&<>
  <details className="op-disclosure"><summary>Reorder information</summary><p className="op-instructions">{j.reorder||'No reorder notes recorded. Use Update information to add notes.'}</p></details>
  <details className="op-disclosure"><summary>Job visits</summary><JobVisits jobId={j.id} onBusy={noOp} onEditing={noOp}/></details>
  <details className="op-disclosure"><summary>Other · UTI, COLL, Service, ACCRF</summary>{data.canEdit&&<RequestForm team={team} save={save}/>}<div className="op-request-list">{(o.requests||[]).map((r:any)=><article key={r.id}><strong>{r.type} · {r.status}</strong><p>{r.details}</p>{r.type==='ACCRF'&&<p>Revised contract price: {currency(r.amount)}</p>}{me.role==='admin'&&r.status==='Pending'&&<><button disabled={saving} onClick={()=>act('reviewRequest',{id:r.id,approve:true})}>Approve and move to {r.type==='Service'?'SVC':r.type}</button><button disabled={saving} onClick={()=>act('reviewRequest',{id:r.id,approve:false})}>Decline</button></>}</article>)}</div>{me.role==='admin'&&<div className="live-danger-zone"><h3>Delete account</h3><p>Permanently remove this customer job and its Production Desk records.</p><button disabled={saving} onClick={()=>{if(window.confirm('Are you sure you want to delete this account?'))act('delete')}}>Delete account</button></div>}</details>
  {me.role==='admin'&&<details className="op-disclosure"><summary>Payments</summary><PaymentForm j={j} save={save}/></details>}
  <details className="op-disclosure"><summary>Customer record and contact notes</summary><ProjectRecord j={j}/></details>
  <details className="op-disclosure"><summary>Job history</summary>{(j.history||[]).map((h:any,i:number)=><p className="op-history" key={i}>{h.text}<small>{h.by} · {new Date(h.at).toLocaleString()}</small></p>)}</details>
 </>}
 </>;
}
function ScheduleForm({j,team,today,save}:any){const [day,setDay]=useState(j.install||today),[multi,setMulti]=useState(!!j.installEnd&&j.installEnd!==j.install),[end,setEnd]=useState(j.installEnd||j.install||today),[files,setFiles]=useState<File[]>([]);const late=(dayDifference(j.received,day)||0)>30;return <Form onSave={async f=>{const salesPhotos=[];for(const file of files)salesPhotos.push(await uploadAttachment(j.id,'photos',file));await save('schedule',{salesPhotos,date:day,endDate:multi?end:day,period:field(f,'time')?(Number(field(f,'time').slice(0,2))<12?'AM':'PM'):field(f,'period'),time:field(f,'time'),installerId:field(f,'installerId'),stop:Number(field(f,'stop')),paymentReference:field(f,'paymentReference'),additionalInstructions:field(f,'additionalInstructions')})}}><label className="op-check"><input type="checkbox" checked={multi} onChange={e=>setMulti(e.target.checked)}/>Multi-day</label>{multi&&<p className="op-muted">Scheduled Monday–Friday only. Weekends are skipped.</p>}<label>{multi?'Start date':'Install date'}<input type="date" required min={today} value={day} onChange={e=>{setDay(e.target.value);if(end<e.target.value)setEnd(e.target.value)}}/></label>{multi&&<label>End date<input type="date" min={day} value={end} required onChange={e=>setEnd(e.target.value)}/></label>}<Select label="AM / PM" name="period" value={j.installPeriod||'AM'} items={['AM','PM']}/><Select required={false} label="Start time (optional)" name="time" value={j.installTime||''} items={[{id:'',name:'Use AM / PM window'},...Array.from({length:24},(_,hour)=>{const id=String(hour).padStart(2,'0')+':00';return {id,name:hourLabel(id)}})]}/><Select label="Installer" name="installerId" value={j.installerId} items={team.filter((m:any)=>m.role==='installer'&&m.active!==0)}/><Input label="Stop number" name="stop" type="number" min="1" max="99" value={j.stopNumber||1} required/><label>Additional sales photos<input type="file" multiple accept="image/*" onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label><Text name="additionalInstructions" label="Additional scheduling instructions" value={j.scheduleInstructions}/>{!j.permitReceived&&<p className="op-red">Permit Received and a permit number are required before scheduling.</p>}{late&&<><p className="op-callout">This appointment is beyond 30 days received and will age. Record payment in full first. Saving sends an approval request to the Field Supervisor; a supervisor may approve their own request.</p><Input label="Full-payment reference" name="paymentReference" required/></>}</Form>}
function StatusForm({j,save,admin}:any){if(j.operations?.report?.pending)return <Form onSave={async()=>save('reviewReport',{approve:true})}><Select name="result" label="Approve installer result" value={j.operations.report.status} items={[{id:j.operations.report.status,name:j.operations.report.status==='Complete'?'COMP — Approve Complete report':'INC — Approve Incomplete report'}]}/><p>✓ Installer result received. Saving approves the submitted result and updates the job status.</p></Form>;const canProd=j.stage==='Received'&&!!j.install,canProgress=['Production','InProgress'].includes(j.stage);if(!canProd&&!canProgress)return <p className="op-muted">Schedule an RCVD job before moving it to PROD.</p>;return <Form onSave={async f=>save('status',{target:field(f,'target')})}><Select name="target" label="New status" value={canProd?'Production':'InProgress'} items={[...(canProd?[{id:'Production',name:'PROD — Start production timer'}]:[]),...(canProgress?[{id:'InProgress',name:'IN PROGRESS — Multi-day installation'}]:[]),...(admin&&j.stage==='Production'?[{id:'Received',name:'RCVD — Return to received'}]:[])]}/></Form>}
function ReceiveForm({j,save}:any){const [rows,setRows]=useState<any[]>(j.materials?.length?j.materials:[{materialType:j.materialType||allowedMaterials(j.product)[0],brand:j.brand||'',bay:j.bay||''}]);return <Form onSave={async f=>save('receive',{received:field(f,'received'),materials:rows})}><Input name="received" label="Materials Received date" type="date" max={localDay()} value={j.received||localDay()} readOnly={!!j.received} required/>{rows.map((row,i)=><div key={i} className="live-receipt-row"><label>Product type<select value={row.materialType} onChange={e=>setRows(rows.map((r,n)=>n===i?{...r,materialType:e.target.value}:r))}>{allowedMaterials(j.product).map(v=><option key={v}>{v}</option>)}</select></label><label>Brand<select required value={row.brand} onChange={e=>setRows(rows.map((r,n)=>n===i?{...r,brand:e.target.value}:r))}><option value="">Select…</option>{brands.map(v=><option key={v}>{v}</option>)}</select></label><label>Bay location<input required value={row.bay} onChange={e=>setRows(rows.map((r,n)=>n===i?{...r,bay:e.target.value}:r))}/></label>{rows.length>1&&<button type="button" onClick={()=>setRows(rows.filter((_,n)=>n!==i))}>Remove product</button>}</div>)}<button type="button" onClick={()=>setRows([...rows,{materialType:allowedMaterials(j.product)[0],brand:'',bay:''}])}>Add product / bay</button></Form>}
function PermitDetails({j}:any){return <dl className="live-record">{[['Permit number',j.permitNumber],['Building Department',j.buildingDepartment],['Expiration date',j.permitExpiration],['Building Department phone',formatPhone(j.buildingDepartmentPhone||'')],['Private Provider',j.privateProvider?'Yes — virtual inspections':'No']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'Not recorded'}</dd></div>)}</dl>}
function PermitForm({j,save}:any){const [received,setReceived]=useState(!!j.permitReceived);return <details><summary>Update permit</summary><Form onSave={async f=>save('permit',{received,number:field(f,'permitNumber'),buildingDepartment:field(f,'buildingDepartment'),expiration:field(f,'permitExpiration'),buildingDepartmentPhone:formatPhone(field(f,'buildingDepartmentPhone')),privateProvider:f.has('privateProvider')})}><Input name="permitNumber" label="Permit number" value={j.permitNumber} required={received}/><Input name="buildingDepartment" label="Building Department" value={j.buildingDepartment}/><Input name="permitExpiration" label="Expiration date" type="date" value={j.permitExpiration}/><Input name="buildingDepartmentPhone" label="Building Department phone number" type="tel" value={formatPhone(j.buildingDepartmentPhone||'')} onInput={(e:any)=>e.currentTarget.value=formatPhone(e.currentTarget.value)}/><label className="op-check"><input name="privateProvider" type="checkbox" defaultChecked={!!j.privateProvider}/>Private Provider — virtual inspections</label><label className="op-check"><input type="checkbox" checked={received} onChange={e=>setReceived(e.target.checked)}/>Permit Received</label></Form></details>}
function RequestForm({team,save}:any){const [type,setType]=useState('UTI');return <Form onSave={async f=>save('request',{type,details:field(f,'details'),paymentReference:field(f,'paymentReference'),refused:f.has('refused'),serviceDate:field(f,'serviceDate'),period:field(f,'period')||'AM',installerId:field(f,'installerId'),...(type==='ACCRF'?{amount:Number(field(f,'amount'))}:{})})}><label>Request type<select value={type} onChange={e=>setType(e.target.value)}>{['UTI','COLL','Service','ACCRF'].map(v=><option key={v}>{v}</option>)}</select></label><Text label="Details / work instructions" name="details"/>{type==='UTI'&&<Input name="paymentReference" label="Payment-in-full reference" required/>}{type==='COLL'&&<label className="op-check"><input name="refused" type="checkbox" required/>Customer refused payment</label>}{type==='Service'&&<><Input label="Service date" name="serviceDate" type="date" min={localDay()} required/><Select label="Period" name="period" value="AM" items={['AM','PM']}/><Select label="Assigned installer" name="installerId" items={team.filter((m:any)=>m.role==='installer'&&m.active!==0)}/></>}{type==='ACCRF'&&<Input label="Revised total contract price" name="amount" type="number" min="0" step=".01" required/>}<small>Administrator approval is required before this changes the job{type==='Service'?' to SVC and adds the service appointment.':'.'}</small></Form>}
function Gallery({attachments}:any){return attachments.length?<div className="op-gallery">{attachments.map((a:any)=><a key={a.key} href={'/api/attachments?key='+encodeURIComponent(a.key)} target="_blank" rel="noreferrer">{a.name}<small>{a.kind}</small></a>)}</div>:<p className="op-muted">No files yet.</p>}
function InstallerReport({j,save}:any){const [status,setStatus]=useState('Complete'),[attachments,setAttachments]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const requirements=requiredReportKinds(status);const upload=async(kind:string,files:File[])=>{if(!files.length)return;setBusy(true);setError('');try{const uploaded:any[]=[];for(const file of files)uploaded.push(await uploadAttachment(j.id,kind,file));setAttachments(old=>['issue','photos'].includes(kind)?[...old,...uploaded]:[...old.filter(v=>v.kind!==kind),uploaded[0]])}catch(e){setError((e as Error).message)}finally{setBusy(false)}};return <><div className="live-requirements"><strong>{status} requires:</strong><span>Front photo</span><span>Back photo</span><span>Left-side photo</span><span>Right-side photo</span><span>{status==='Complete'?'Completion certificate':'Incomplete certificate'}</span>{status==='Incomplete'&&<span>One or more issue photos</span>}</div><Form onSave={async f=>{if(busy)throw Error('Wait for the upload to finish.');const missing=requirements.find(kind=>!attachments.some(a=>a.kind===kind));if(missing)throw Error(`Add ${reportLabels[missing].toLowerCase()} before submitting.`);await save('report',{id:crypto.randomUUID(),status,reason:field(f,'reason'),notes:field(f,'notes'),installed:field(f,'installed'),attachments})}}><label>Job result<select value={status} onChange={e=>{setStatus(e.target.value);setAttachments(old=>old.filter(a=>!['completion','incomplete','issue'].includes(a.kind)))}}><option>Complete</option><option>Incomplete</option></select></label><Input name="installed" label="Installation date" type="date" value={localDay()} max={localDay()} required/>{status==='Incomplete'&&<><Text label="Reason incomplete" name="reason"/>{!j.reorder&&<p className="op-callout">Reorder information must be entered by the office before the Field Supervisor can approve this INC result.</p>}</>}<Text label="Installer notes" name="notes"/>{requirements.map(kind=><label key={kind}>{reportLabels[kind]}<input type="file" multiple={kind==='issue'} accept="image/*,.pdf" disabled={busy} onChange={e=>upload(kind,Array.from(e.target.files||[]))}/><small>{attachments.filter(a=>a.kind===kind).map(a=>a.name).join(', ')||'Required'}</small></label>)}<label>Additional Photos (optional)<input type="file" multiple accept="image/*" disabled={busy} onChange={e=>upload('photos',Array.from(e.target.files||[]))}/><small>{attachments.filter(a=>a.kind==='photos').map(a=>a.name).join(', ')||'Optional'}</small></label>{busy&&<p>Uploading…</p>}{error&&<p className="op-red">{error}</p>}</Form></>}
function Quality({data,change,reload,onOpenJob}:any){const [selectedInstaller,setSelectedInstaller]=useState<any>(null);const {team,surveys,metrics,canReview,me,config}=data;return <><section className="op-panel"><h2>Guild Quality Scores</h2>{me.role==='admin'&&<ReportImport kind="guild" onImported={reload}/>}<p>{metrics.period.start} – {metrics.period.end}</p><div className="op-quality">{['Installation Crew','Quality of Workmanship','Clean & Safe','Installation Done Right'].map((c,i)=><div key={c}><span>{c}</span><strong>{metrics.categories[i]?.toFixed(2)??'—'}</strong></div>)}</div>{team.filter((m:any)=>m.role==='installer').map((m:any)=>{const rows=surveys.filter((s:any)=>s.installer_id===m.id&&s.completed_on>=metrics.period.start&&s.completed_on<=metrics.period.end);const avg=[0,1,2,3].map(i=>{const r=rows.map((s:any)=>s.ratings[i]).filter((v:any)=>v!=null);return r.length?r.reduce((sum:number,v:number)=>sum+v-1,0)/r.length:null});const q=avg.every(v=>v!==null)?avg.reduce((s:number,v:any)=>s+v,0)/4:null;return <div className="op-crew-surveys" key={m.id}><button className="op-appointment" onClick={()=>setSelectedInstaller(selectedInstaller?.id===m.id?null:m)} aria-expanded={selectedInstaller?.id===m.id} aria-controls={'surveys-'+m.id} aria-label={'View surveys for '+m.name}><strong>{m.name}</strong><QualityValue score={q}/></button>{selectedInstaller?.id===m.id&&<div id={'surveys-'+m.id}><SurveyDetails installer={m} surveys={surveys} jobs={data.jobs} period={metrics.period} onOpenJob={onOpenJob} onClose={()=>setSelectedInstaller(null)}/></div>}</div>})}</section>{canReview&&<details className="op-disclosure"><summary>Record Guild Quality survey</summary><Form onSave={async f=>change('survey',{externalId:field(f,'externalId'),installerId:field(f,'installerId'),completedOn:field(f,'completedOn'),ratings:[0,1,2,3].map(i=>field(f,'rating'+i)===''?null:Number(field(f,'rating'+i)))})}><Input label="Unique Guild survey reference" name="externalId" required/><Select label="Installer" name="installerId" items={team.filter((m:any)=>m.role==='installer')}/><Input label="Survey completion date" name="completedOn" type="date" max={localDay()} required/>{['Installation Crew','Workmanship','Clean & Safe','Done Right'].map((v,i)=><label key={v}>{v}<select name={'rating'+i}><option value="">No response</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} stars</option>)}</select></label>)}<small>Original 1–5 stars. Each category is converted to 0–4 before averaging.</small></Form></details>}</>}
function Visits({onOpen}:any){const [rows,setRows]=useState<any[]>([]),[q,setQ]=useState(''),[error,setError]=useState('');useEffect(()=>{liveApi('/api/job-visits/recent').then(d=>setRows(d.visits)).catch(e=>setError(e.message))},[]);return <section className="op-panel"><h2>Recent job visits</h2><input aria-label="Search visits" placeholder="Search customer or job ID" value={q} onChange={e=>setQ(e.target.value)}/>{error&&<p className="op-red">{error}</p>}{rows.filter(r=>[r.job.customer,r.job.number].join(' ').toLowerCase().includes(q.toLowerCase())).map(r=><button className="op-appointment" key={r.visit.id} onClick={()=>onOpen(r.job.id)}><strong>{r.job.customer}</strong><span>{r.visit.visitedOn} · Open job visits</span></button>)}{!rows.length&&<p>No visits yet.</p>}</section>}
function Connections(){const [data,setData]=useState<any>(null),[error,setError]=useState('');const load=()=>liveApi('/api/operations/connections').then(setData).catch(e=>setError(e.message));useEffect(()=>{load()},[]);return <section className="op-panel"><h2>Connections</h2>{error&&<p role="alert" className="op-red">{error}</p>}{data&&<><p>Sales system: {data.salesIntegration}</p><p>Guild Quality: {data.guildQuality}</p><p>Email: {data.emailConfigured?'Configured':'Not configured'}</p><p>Phone push: {data.pushConfigured?'Configured':'Not configured'}</p><p>Open Settings → Photo storage to check Supabase uploads.</p><h3>Sales representative email queue</h3>{data.emails.map((e:any)=><div className="op-appointment" key={e.id}><strong>{e.recipient}<small>{e.subject}</small></strong><span>{e.status==='accepted'?'Accepted by email provider':e.status}</span>{e.status!=='accepted'&&<button onClick={async()=>{try{await liveApi('/api/operations',{action:'retryEmail',id:e.id});load()}catch(err){setError((err as Error).message)}}}>Retry</button>}</div>)}</>}</section>}
function ProjectRecord({j}:any){const [data,setData]=useState<any>(null),[editing,setEditing]=useState(false),[error,setError]=useState('');const load=()=>liveApi('/api/customer-records?jobId='+j.id).then(setData).catch(e=>setError(e.message));useEffect(()=>{load()},[j.id]);const fields=[...new Map([...recordFields,...profileFields,...historyDateFields].map(v=>[v[0],v])).values()].filter(([k])=>!k.startsWith('permit')&&k!=='inspectionDate');return <>{error&&<p className="op-red">{error}</p>}{data&&<><p className="op-muted">Imported customer record. Its historical balance fields do not replace the operational amount due.</p>{j.importSource&&<p className="op-callout">Imported from {j.importSource.file}, page {j.importSource.page}. Names and notes may be clipped in the source. Missing address, permit, product breakdown and assignments need review. {j.stage==='Incomplete'&&!j.incompleteSince?'INC entry date is unconfirmed; excluded from aged totals until verified.':''}</p>}{data.canEdit&&<button className="live-button" onClick={()=>setEditing(!editing)}>Update record</button>}{editing?<Form onSave={async f=>{const record={...data.record};fields.forEach(([k])=>record[k]=field(f,k));await liveApi('/api/customer-records',{jobId:j.id,version:data.version,record});await load();setEditing(false)}}>{fields.map(([k,label])=><Input key={k} name={k} label={label} value={data.record[k]}/>)}</Form>:<dl className="live-record">{fields.filter(([k])=>data.record[k]).map(([k,label])=><div key={k}><dt>{label}</dt><dd>{data.record[k]}</dd></div>)}</dl>}{data.canEdit&&<Form onSave={async f=>{await liveApi('/api/customer-records',{jobId:j.id,version:data.version,note:field(f,'note'),kind:'Contact'});await load()}}><Text name="note" label="Add contact note"/></Form>}{data.events.map((e:any)=><p className="op-history" key={e.id}>{e.note}<small>{e.actor_name} · {e.created}</small></p>)}</>}</>}

function PaymentForm({j,save}:any){const [mode,setMode]=useState('payment');return <Form onSave={async f=>save(mode,{...(mode==='payment'?{paymentAmount:Number(field(f,'amount'))}:{amount:Number(field(f,'amount'))}),reference:field(f,'reference'),paymentType:field(f,'paymentType')})}><p>Current balance due: {currency(j.amount)}</p><label>Action<select value={mode} onChange={e=>setMode(e.target.value)}><option value="payment">Record payment</option><option value="balance">Reconcile balance from main system</option></select></label><Input key={mode} name="amount" label={mode==='payment'?'Payment amount':'Correct balance due'} type="number" min={mode==='payment'?'.01':'0'} max={mode==='payment'&&j.amount!=null?j.amount:undefined} step=".01" required/>{mode==='payment'&&<Select name="paymentType" label="Payment type" value={j.paymentMethod} items={paymentMethods}/>}<Input name="reference" label="Payment or source reference" required/></Form>}
