'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
async function data(url:string,options?:RequestInit){const response=await fetch(url,options),result=await response.json();if(!response.ok)throw Error(result.error||'Request failed');return result}
const post=(value:unknown)=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});
export function PhoneNotifications(){const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[pushEnabled,setPushEnabled]=useState(false),[serverConfigured,setServerConfigured]=useState(false),[registeredDevices,setRegisteredDevices]=useState(0);
 useEffect(()=>{if('serviceWorker' in navigator)navigator.serviceWorker.getRegistration('/').then(async r=>{if(r)setPushEnabled(!!await r.pushManager.getSubscription())}).catch(()=>{});data('/api/push').then(d=>{setServerConfigured(d.configured);setRegisteredDevices(d.registeredDevices||0);if(!d.configured)setError('Phone push needs VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY in Vercel, plus VAPID_SUBJECT or APP_URL. Ask your administrator to finish setup.')}).catch(e=>setError(e.message))},[]);
 async function enablePush(){setError('');setMessage('');if(!('serviceWorker' in navigator)||!('PushManager' in window)||!('Notification' in window)){setError('On iPhone, add Production Desk to your Home Screen and open it there to enable notifications. Other devices need a browser that supports push notifications.');return;}setBusy(true);try{const {publicKey,configured}=await data('/api/push');if(!configured)throw Error('Phone push is not configured on the server yet. Ask your administrator to finish setup.');const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('Notifications are not enabled. Allow notifications in your browser or device settings, then try again.');const registration=await navigator.serviceWorker.register('/sw.js',{scope:'/',updateViaCache:'none'});await navigator.serviceWorker.ready;if(!publicKey)throw Error('Phone notifications are not configured yet.');const key=Uint8Array.from(atob(publicKey.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));const subscription=await registration.pushManager.getSubscription()||await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});await data('/api/push',post(subscription.toJSON()));setPushEnabled(true);setRegisteredDevices(v=>Math.max(1,v));setMessage('Phone notifications enabled on this device.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function testPush(){setBusy(true);setError('');setMessage('');try{await data('/api/push',post({action:'test'}));setMessage('Test notification sent. If it did not appear, check this device’s browser notification settings.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
return <section className="profile-section"><h2>Phone notifications</h2><p>Receive job updates on this phone, even when the app is closed. Enable notifications separately on each device.</p><div className="notification-status"><p><strong>Server:</strong> {serverConfigured?'Configured':'Not configured'}</p><p><strong>This device:</strong> {pushEnabled?'Enabled':'Not enabled'}</p><p><strong>Registered devices:</strong> {registeredDevices}</p></div><p>On iPhone, use Safari to add this site to your Home Screen, then open it from that icon.</p><Button disabled={busy} onClick={enablePush}>{pushEnabled?'Refresh phone notification setup':'Enable phone notifications'}</Button>{pushEnabled&&<Button disabled={busy} variant="outline" onClick={testPush}>Send test notification</Button>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</section>}
