'use client';
import {useState} from 'react';
import {uploadAttachment} from '@/lib/upload-client';
import {printReorder} from '@/lib/print-reorder';
const types=['Whole Window','Screen Frame','Sash','Frame','SPD','Entry Door','Other Part'];
const parties=['Factory','Installer','Sales Rep','Customer','Window World'];
const empty=()=>({type:'Whole Window',window:'',quantity:1,orderedSize:'',actualSize:'',reorderSize:'',serial:'',position:'',description:'',photos:[] as any[]});
export function ReorderRequests({j,me,save}:any){
 const review=['admin','supervisor'].includes(me.role),canSubmit=review||me.role==='installer';
 const [draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function run(data:any){setBusy(true);setError('');setNotice('');try{await save('reorderRequest',data);setNotice('✓ Reorder saved.');return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 const editItem=(i:number,k:string,v:any)=>setDraft((d:any)=>({...d,items:d.items.map((x:any,n:number)=>n===i?{...x,[k]:v}:x)}));
 return <details className="op-disclosure"><summary>Digital Reorder Forms ({j.operations?.reorders?.length||0})</summary>
 <p>Customer: {j.customer} · ID #{j.number} · Installer: {j.crew||me.name} · Sales Rep: {j.salesRep||'Not recorded'}</p>
 {canSubmit&&!draft&&<button className="live-button" onClick={()=>setDraft({reason:'',remaining:'',items:[empty()]})}>Create Reorder</button>}
 {error&&<p role="alert" className="op-red">{error}</p>}{notice&&<p role="status" className="op-callout">{notice}</p>}
 {draft&&<form className="op-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await run({command:'submit',...draft,acknowledged:f.has('acknowledged')}))setDraft(null)}}>
 <fieldset disabled={busy}><h3>Contractor Reorder Form</h3><label>Why is this reorder necessary?<textarea required value={draft.reason} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label>
 {draft.items.map((x:any,i:number)=><details key={i} open className="op-disclosure"><summary>Item {i+1} · {x.type} · {x.window||'Window/location'}</summary>
 <label>Item type<select value={x.type} onChange={e=>editItem(i,'type',e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select></label>
 <label>Window number / location<input required value={x.window} onChange={e=>editItem(i,'window',e.target.value)}/></label><label>Quantity<input type="number" min="1" max="999" value={x.quantity} onChange={e=>editItem(i,'quantity',Number(e.target.value))}/></label>
 {(x.type==='Whole Window'?[['orderedSize','Window size written on order form'],['actualSize','Actual size of window being returned'],['reorderSize','Reorder size required to fit opening']]:[['serial','Serial number'],...(x.type==='Sash'?[['position','Sash position']]:[])]).map(([k,label])=><label key={k}>{label}<input required={x.type==='Whole Window'||['Screen Frame','Sash','Frame'].includes(x.type)} value={x[k]} onChange={e=>editItem(i,k,e.target.value)}/></label>)}
 <label>Product / part description<textarea value={x.description} onChange={e=>editItem(i,'description',e.target.value)}/></label>
 <label>Photos (required): issue, product tag and measurements<input type="file" accept="image/*" multiple onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';setBusy(true);setError('');try{const photos=[...x.photos];for(const file of files)photos.push(await uploadAttachment(j.id,'issue',file));editItem(i,'photos',photos)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}/></label>
 {x.photos.map((a:any)=><p key={a.key}>{a.name} <button type="button" onClick={()=>editItem(i,'photos',x.photos.filter((v:any)=>v.key!==a.key))}>Remove photo</button></p>)}
 <button type="button" disabled={draft.items.length===1} onClick={()=>setDraft({...draft,items:draft.items.filter((_:any,n:number)=>n!==i)})}>Remove item</button></details>)}
 <button type="button" className="live-button" onClick={()=>setDraft({...draft,items:[...draft.items,empty()]})}>Add Item</button>
 <p><strong>WINDOW TAG MUST BE RETURNED WITH WINDOW</strong></p>
 <label>Other work remaining<textarea value={draft.remaining} onChange={e=>setDraft({...draft,remaining:e.target.value})}/></label>
 <label className="op-check"><input type="checkbox" name="acknowledged" required/>I certify all remaining work is listed and have checked the fit and accuracy of the reordered items. My name and submission time will be recorded.</label>
 <button className="op-primary">Submit for FS review</button><button type="button" onClick={()=>setDraft(null)}>Cancel</button></fieldset></form>}
 {(j.operations?.reorders||[]).map((r:any)=><details className="op-disclosure" key={r.id}><summary>{r.status} · {r.reason.slice(0,90)} · {r.submittedAt?.slice(0,10)}</summary>
 <p>{r.reason}</p><p>Submitted by {r.submittedName} · {r.submittedAt}</p><p>Other work remaining: {r.remaining||'None'}</p>
 {r.items.map((i:any,n:number)=><div key={n}><strong>{i.type} · {i.window} · Qty {i.quantity}</strong><p>{[i.orderedSize&&'Ordered: '+i.orderedSize,i.actualSize&&'Actual: '+i.actualSize,i.reorderSize&&'Reorder: '+i.reorderSize,i.serial&&'Serial: '+i.serial,i.position,i.description].filter(Boolean).join(' · ')}</p>{i.photos.map((a:any)=><a key={a.key} href={'/api/attachments?key='+encodeURIComponent(a.key)} target="_blank" rel="noreferrer">{a.name} ↗ </a>)}</div>)}
 <p>Charge back to: {(r.chargebacks||[]).join(', ')||'Not assigned'} · {r.chargebackNote}</p><p>{r.comment}</p><p>Vendor: {r.vendor||'Not ordered'} · Order #: {r.reference||'—'} · Ordered: {r.orderedDate||'—'} · Estimated ship: {r.estimatedShipDate||'—'} · Received: {r.receivedDate||'—'} · Bay: {r.bay||'—'}</p>
 <button className="live-button" onClick={()=>{try{printReorder(j,r)}catch(e){setError((e as Error).message)}}}>Print / Save PDF</button>
 {r.status==='Correction requested'&&(review||r.submittedBy===me.id)&&<button className="live-button" onClick={()=>setDraft({id:r.id,reason:r.reason,remaining:r.remaining,items:r.items})}>Correct and resubmit</button>}
 {review&&r.status==='Submitted'&&<form className="op-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await run({command:'review',id:r.id,decision:f.get('decision'),chargebacks:f.getAll('chargebacks'),chargebackNote:f.get('chargebackNote'),comment:f.get('comment'),reviewAcknowledged:f.has('reviewAcknowledged')})}}><fieldset disabled={busy}><h4>FS / Admin Review</h4><p>Charge Back To:</p>{parties.map(p=><label key={p} className="op-check"><input type="checkbox" name="chargebacks" value={p}/>{p}</label>)}<label>Chargeback Notes<textarea name="chargebackNote"/></label><label>Review comments<textarea name="comment"/></label><label>Decision<select name="decision"><option>Approved</option><option>Correction requested</option><option>Declined</option></select></label><label className="op-check"><input type="checkbox" name="reviewAcknowledged" required/>I reviewed this information and determined it is correct and complete, or recorded the corrections needed.</label><button className="op-primary">Save review</button></fieldset></form>}
 {review&&['Approved','Ordered','Received','Scheduled'].includes(r.status)&&<form className="op-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await run({command:'track',id:r.id,...Object.fromEntries(f),tagReturned:f.has('tagReturned')})}}><fieldset disabled={busy}><h4>Order / Return Tracking</h4><input type="hidden" name="status" value={({Approved:'Ordered',Ordered:'Received',Received:'Scheduled',Scheduled:'Resolved'} as any)[r.status]}/>
 {([['vendor','Vendor','text'],['reference','Order / reference number','text'],['orderedDate','Actual order date','date'],['estimatedShipDate','Estimated ship date','date'],['receivedDate','Received date','date'],['bay','Material bay','text'],['returnDate','Window return date','date'],['managerInitials','Manager initials','text']] as const).map(([k,l,t])=><label key={k}>{l}<input name={k} type={t} defaultValue={r[k]||''}/></label>)}
 <label className="op-check"><input type="checkbox" name="tagReturned" defaultChecked={r.tagReturned}/>Window tag returned</label><label>Tracking notes<textarea name="notes" defaultValue={r.notes||''}/></label>{r.status==='Received'&&<p>Add the return visit in Schedule Work first, then mark this request Scheduled.</p>}<button className="op-primary">Mark {({Approved:'Ordered',Ordered:'Received',Received:'Scheduled',Scheduled:'Resolved'} as any)[r.status]}</button></fieldset></form>}
 <details><summary>History and sign-offs</summary>{r.revisions?.map((v:any,n:number)=><details key={'revision-'+n}><summary>Previous submission · {v.at}</summary><p>{v.reason}</p>{v.items.map((i:any,k:number)=><p key={k}>{i.type} · {i.window} · {i.reorderSize||i.serial} · {i.description}</p>)}<p>Previous review: {v.reviewedBy} · {v.comment} · {v.chargebackNote}</p></details>)}{r.events?.map((v:any,n:number)=><p key={n}>{v.at} · {v.by}: {v.message}</p>)}</details></details>)}
 </details>
}
