'use client';
import {useState} from 'react';
import {uploadAttachment} from '@/lib/upload-client';
import {printReorder} from '@/lib/print-reorder';
const types=['Whole Window','Screen Frame','Sash','Frame','SPD','Entry Door','Other Part'];
const parties=['Factory','Installer','Sales Rep','Customer','Window World'];
const empty=()=>({type:'Whole Window',window:'',quantity:1,orderedSize:'',actualSize:'',reorderSize:'',serial:'',position:'',panelSide:'',panelOperation:'',specialShape:false,orderedLegHeight:'',actualLegHeight:'',reorderLegHeight:'',description:'',photos:[] as any[]});
export function ReorderRequests({j,me,save}:any){
 const review=['admin','supervisor'].includes(me.role),canSubmit=review||me.role==='installer';
 const [draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function run(data:any){setBusy(true);setError('');setNotice('');try{await save('reorderRequest',data);setNotice('✓ Reorder saved.');return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 const editItem=(i:number,k:string,v:any)=>setDraft((d:any)=>({...d,items:d.items.map((x:any,n:number)=>n===i?{...x,[k]:v}:x)}));
 return <details className="op-disclosure"><summary>Digital Reorder Forms ({j.operations?.reorders?.length||0})</summary>
 <p>Customer: {j.customer} · ID #{j.number} · Installer: {j.crew||me.name} · Sales Rep: {j.salesRep||'Not recorded'}</p>
 {canSubmit&&!draft&&<button className="live-button" onClick={()=>setDraft({reason:'',remaining:'',items:[empty()]})}>Create Reorder</button>}
 {error&&<p role="alert" className="op-red">{error}</p>}{notice&&<p role="status" className="op-callout">{notice}</p>}
 {draft&&<form className="op-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await run({command:'submit',...draft,...(review?{chargebacks:f.getAll('chargebacks'),chargebackNote:f.get('chargebackNote')}:{}),acknowledged:f.has('acknowledged')}))setDraft(null)}}>
 <fieldset disabled={busy}><h3>Contractor Reorder Form</h3><label>Why is this reorder necessary?<textarea required value={draft.reason} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label>
 {draft.items.map((x:any,i:number)=><details key={i} open className="op-disclosure"><summary>Item {i+1} · {x.type} · {x.window||'Window/location'}</summary>
 <label>Item type<select value={x.type} onChange={e=>editItem(i,'type',e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select></label>
 <label>Window number / location<input required value={x.window} onChange={e=>editItem(i,'window',e.target.value)}/></label><label>Quantity<input type="number" min="1" max="999" value={x.quantity} onChange={e=>editItem(i,'quantity',Number(e.target.value))}/></label>
 {x.type==='Whole Window'&&<label className="op-check"><input type="checkbox" checked={!!x.specialShape} onChange={e=>editItem(i,'specialShape',e.target.checked)}/>Special Shape (arch window)</label>}
 {x.type==='Whole Window'?(['orderedSize','actualSize','reorderSize'] as const).map((k,n)=><WindowSize key={k} label={['Window size written on order form','Actual size of window being returned','Reorder size required to fit opening'][n]} value={x[k]} onChange={(v:string)=>editItem(i,k,v)} specialShape={!!x.specialShape} legHeight={x[['orderedLegHeight','actualLegHeight','reorderLegHeight'][n]]||''} onLegChange={(v:string)=>editItem(i,['orderedLegHeight','actualLegHeight','reorderLegHeight'][n],v)}/>):<label>Serial number<input required={['Screen Frame','Sash','Frame'].includes(x.type)} value={x.serial} onChange={e=>editItem(i,'serial',e.target.value)}/></label>}
 {x.type==='Sash'&&<label>Sash position<select required value={x.position} onChange={e=>editItem(i,'position',e.target.value)}><option value="">Select…</option>{['Top','Bottom','Left','Right','Middle'].map(v=><option key={v}>{v}</option>)}</select></label>}
 {x.type==='SPD'&&<><label>Patio door panel side<select required value={x.panelSide||''} onChange={e=>editItem(i,'panelSide',e.target.value)}><option value="">Select…</option><option>Left</option><option>Right</option></select></label><label>Patio door panel operation<select required value={x.panelOperation||''} onChange={e=>editItem(i,'panelOperation',e.target.value)}><option value="">Select…</option><option>Inactive</option><option>Active</option></select></label></>}
 <label>Product / part description<textarea value={x.description} onChange={e=>editItem(i,'description',e.target.value)}/></label>
 <label>Photos ({review?'optional':'required'}): issue, product tag and measurements<input type="file" accept="image/*" multiple onChange={async e=>{const files=Array.from(e.target.files||[]);e.target.value='';setBusy(true);setError('');try{const photos=[...x.photos];for(const file of files)photos.push(await uploadAttachment(j.id,'issue',file));editItem(i,'photos',photos)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}/></label>
 {x.photos.map((a:any)=><p key={a.key}>{a.name} <button type="button" onClick={()=>editItem(i,'photos',x.photos.filter((v:any)=>v.key!==a.key))}>Remove photo</button></p>)}
 <button type="button" disabled={draft.items.length===1} onClick={()=>setDraft({...draft,items:draft.items.filter((_:any,n:number)=>n!==i)})}>Remove item</button></details>)}
 <button type="button" className="live-button" onClick={()=>setDraft({...draft,items:[...draft.items,empty()]})}>Add Item</button>
 <p><strong>WINDOW TAG MUST BE RETURNED WITH WINDOW</strong></p>
 <label>Other work remaining<textarea value={draft.remaining} onChange={e=>setDraft({...draft,remaining:e.target.value})}/></label>
 <label className="op-check"><input type="checkbox" name="acknowledged" required/>I certify all remaining work is listed and have checked the fit and accuracy of the reordered items. My name and submission time will be recorded.</label>
 {review&&<><p>Charge Back To:</p>{parties.map(p=><label key={p} className="op-check"><input type="checkbox" name="chargebacks" value={p}/>{p}</label>)}<label>Chargeback Notes<textarea name="chargebackNote"/></label></>}
 <button className="op-primary">{review?'Submit Reorder':'Submit for FS review'}</button><button type="button" onClick={()=>setDraft(null)}>Cancel</button></fieldset></form>}
 {(j.operations?.reorders||[]).map((r:any)=><details className="op-disclosure" key={r.id}><summary>{r.status} · {r.reason.slice(0,90)} · {r.submittedAt?.slice(0,10)}</summary>
 <p>{r.reason}</p><p>Submitted by {r.submittedName} · {r.submittedAt}</p><p>Other work remaining: {r.remaining||'None'}</p>
 {r.items.map((i:any,n:number)=><div key={n}><strong>{i.type} · {i.window} · Qty {i.quantity}</strong><p>{[i.orderedSize&&'Ordered: '+i.orderedSize,i.actualSize&&'Actual: '+i.actualSize,i.reorderSize&&'Reorder: '+i.reorderSize,i.serial&&'Serial: '+i.serial,i.specialShape&&'Special Shape',i.specialShape&&'Leg heights (ordered / actual / reorder): '+[i.orderedLegHeight,i.actualLegHeight,i.reorderLegHeight].join(' / '),i.position,i.panelSide,i.panelOperation,i.description].filter(Boolean).join(' · ')}</p>{i.photos.map((a:any)=><a key={a.key} href={'/api/attachments?key='+encodeURIComponent(a.key)} target="_blank" rel="noreferrer">{a.name} ↗ </a>)}</div>)}
 <p>Charge back to: {(r.chargebacks||[]).join(', ')||'Not assigned'} · {r.chargebackNote}</p><p>{r.comment}</p><p>Reorder date: {r.reorderDate||'Awaiting approval'}</p>
 <button className="live-button" onClick={()=>{try{printReorder(j,r)}catch(e){setError((e as Error).message)}}}>Print / Save PDF</button>
 {me.role==='admin'&&<button type="button" className="live-button" disabled={busy} onClick={async()=>{if(window.confirm('Are you sure you want to delete this reorder?'))await run({command:'delete',id:r.id})}}>Delete reorder</button>}
 {r.status==='Correction requested'&&(review||r.submittedBy===me.id)&&<button className="live-button" onClick={()=>setDraft({id:r.id,reason:r.reason,remaining:r.remaining,items:r.items})}>Correct and resubmit</button>}
 {review&&r.status==='Submitted'&&<form className="op-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await run({command:'review',id:r.id,decision:f.get('decision'),chargebacks:f.getAll('chargebacks'),chargebackNote:f.get('chargebackNote'),comment:f.get('comment'),reviewAcknowledged:f.has('reviewAcknowledged')})}}><fieldset disabled={busy}><h4>FS / Admin Review</h4><p>Charge Back To:</p>{parties.map(p=><label key={p} className="op-check"><input type="checkbox" name="chargebacks" value={p}/>{p}</label>)}<label>Chargeback Notes<textarea name="chargebackNote"/></label><label>Review comments<textarea name="comment"/></label><label>Decision<select name="decision"><option>Approved</option><option>Correction requested</option><option>Declined</option></select></label><label className="op-check"><input type="checkbox" name="reviewAcknowledged" required/>I reviewed this information and determined it is correct and complete, or recorded the corrections needed.</label><button className="op-primary">Save review</button></fieldset></form>}
 <details><summary>History and sign-offs</summary>{r.revisions?.map((v:any,n:number)=><details key={'revision-'+n}><summary>Previous submission · {v.at}</summary><p>{v.reason}</p>{v.items.map((i:any,k:number)=><p key={k}>{i.type} · {i.window} · {i.reorderSize||i.serial} · {i.description}</p>)}<p>Previous review: {v.reviewedBy} · {v.comment} · {v.chargebackNote}</p></details>)}{r.events?.map((v:any,n:number)=><p key={n}>{v.at} · {v.by}: {v.message}</p>)}</details></details>)}
 </details>
}

const fractions=['0','1/16','1/8','3/16','1/4','5/16','3/8','7/16','1/2','9/16','5/8','11/16','3/4','13/16','7/8','15/16'];
function WindowSize({label,value,onChange,specialShape,legHeight,onLegChange}:{label:string,value:string,onChange:(v:string)=>void,specialShape:boolean,legHeight:string,onLegChange:(v:string)=>void}){
 const parse=(v:string)=>{const m=(v||'').trim().match(/^(\d+)(?:\s+(\d+\/\d+))?$/);return m?[m[1],m[2]||'0']:/^\d+\/\d+$/.test((v||'').trim())?['',v.trim()]:['','0']};
 const parts=(value||'').split(/\s*x\s*/i),width=parse(parts[0]),height=parse(parts[1]),leg=parse(legHeight);
 const format=(v:string[])=>v[0]+(v[1]!=='0'?' '+v[1]:'');
 function pair(name:string,vals:string[],save:(v:string[])=>void){return <div style={{minWidth:0,flex:'1 1 0'}}><div style={{fontSize:13,fontWeight:600,marginBottom:5}}>{name}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:5}}>{vals.map((v,i)=><select key={i} aria-label={label+' '+name+(i?' fraction':' inches')} required value={v} style={{minWidth:0,width:'100%',padding:'8px 4px'}} onChange={e=>{const next=[...vals];next[i]=e.target.value;save(next)}}>{i===0&&<option value="">In.</option>}{(i?fractions:Array.from({length:301},(_,n)=>String(n))).map(n=><option key={n} value={n}>{n}</option>)}</select>)}</div></div>}
 return <fieldset style={{minWidth:0,margin:'12px 0',padding:10}}><legend>{label} (inches)</legend><div style={{display:'flex',gap:8,alignItems:'end',flexWrap:'nowrap'}}>{pair('Width',width,v=>onChange(format(v)+' x '+format(height)))}<span style={{fontWeight:700,paddingBottom:10}}>X</span>{pair('Height',height,v=>onChange(format(width)+' x '+format(v)))}</div>{specialShape&&<div style={{maxWidth:220,marginTop:10}}>{pair('Leg Height',leg,v=>onLegChange(format(v)))}</div>}</fieldset>
}
