'use client';
import {useState} from 'react';
import {parseBonusReport,parseGuildReport,type ImportedSurvey} from '@/lib/report-import';
import {bonusPeriod,localDay} from '@/lib/operations';
import {readReport} from '@/lib/read-report';
export function ReportImport({kind,onBonus,onImported}:{kind:'bonus'|'guild';onBonus?:(v:any)=>void;onImported?:()=>Promise<void>}){
 const [text,setText]=useState(''),[rows,setRows]=useState<ImportedSurvey[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');const period=bonusPeriod(localDay());
 function preview(){setError('');try{if(kind==='bonus'){onBonus?.(parseBonusReport(text));setMessage('Values loaded below. Review every threshold and payout, then Save.')}else{setRows(parseGuildReport(text));setMessage('Review the survey rows before importing.')}}catch(e){setError((e as Error).message)}}
 return <details className="op-disclosure"><summary>Scan / import {kind==='bonus'?'bonus targets':'Guild Quality report'}</summary><p>Choose a PDF or a clear photo of the report. Check the extracted text and preview before saving. Scans are read on this device.</p><input aria-label="Choose report" type="file" accept="application/pdf,image/png,image/jpeg,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');setRows([]);setText('');try{setText(await readReport(file,setMessage));setMessage('Report read. Click Preview extracted values.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}/>{text&&<><label>Extracted text — correct any scan errors<textarea className="live-report-text" value={text} onChange={e=>{setText(e.target.value);setRows([])}}/></label><button type="button" disabled={busy} onClick={preview}>Preview extracted values</button></>}{message&&<p role="status">{message}</p>}{error&&<p className="op-red" role="alert">{error}</p>}{!!rows.length&&<><p>{rows.length} surveys · {new Set(rows.map(r=>r.code)).size} installer crews · {rows.filter(r=>r.completedOn>=period.start&&r.completedOn<=period.end).length} surveys in the current bonus period ({period.start} – {period.end}). Scores below are already 0–4.</p><div className="live-import-scroll"><table><thead><tr>{['Installer','Survey date','Customer ID','Crew','Workmanship','Clean / Safe','Done right'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.code} · {r.name}</td><td>{r.completedOn}</td><td>{r.customerId}</td>{r.ratings.map((v,k)=><td key={k}>{v}</td>)}</tr>)}</tbody></table></div><p>Existing installer codes are matched first. New profiles have no login credentials; add their email and supervisor in Account management, then issue a password. Previously imported surveys are skipped; conflicting scores stop the import.</p><button className="op-primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const res=await fetch('/api/operations/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows})}),d=await res.json();if(!res.ok)throw Error(d.error);setMessage(`${d.inserted} surveys imported; ${d.skipped} already present; ${d.created} installer profiles created.`);setRows([]);await onImported?.()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Confirm and import surveys</button></>}</details>
}
