'use client';
import {useEffect,useRef} from 'react';
export function SignaturePad({value,onChange}:{value:string;onChange:(v:string)=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),ink=useRef(false);
 useEffect(()=>{const c=canvas.current,ctx=c?.getContext('2d');if(!c||!ctx)return;let active=true;ctx.clearRect(0,0,c.width,c.height);if(value){const img=new Image();img.onload=()=>{if(active)ctx.drawImage(img,0,0,c.width,c.height)};img.src=value;}return()=>{active=false}},[value]);
 const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const c=e.currentTarget,b=c.getBoundingClientRect();return {x:(e.clientX-b.left)*c.width/b.width,y:(e.clientY-b.top)*c.height/b.height}};
 const finish=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;drawing.current=false;if(ink.current)onChange(e.currentTarget.toDataURL('image/png'));if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)};
 return <div><p><strong>Draw your signature below</strong> — use your finger or mouse.</p><canvas ref={canvas} width={700} height={180} aria-label="Draw installer signature" style={{display:'block',width:'100%',maxWidth:700,height:180,background:'#fff',border:'2px solid #52677b',borderRadius:8,touchAction:'none'}} onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();const ctx=e.currentTarget.getContext('2d')!;const p=point(e);drawing.current=true;ink.current=false;e.currentTarget.setPointerCapture(e.pointerId);ctx.strokeStyle='#111';ctx.lineWidth=2.5;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(p.x,p.y)}} onPointerMove={e=>{if(!drawing.current)return;const p=point(e),ctx=e.currentTarget.getContext('2d')!;ctx.lineTo(p.x,p.y);ctx.stroke();ink.current=true}} onPointerUp={finish} onPointerCancel={finish}/><button type="button" className="live-button" onClick={()=>{drawing.current=false;const c=canvas.current;c?.getContext('2d')?.clearRect(0,0,c.width,c.height);onChange('')}}>Clear signature</button></div>;
}
