'use client';
import {displayDate} from '@/lib/display-date';
import {useState} from 'react';
import {surveyDetails} from '@/lib/survey-details';
export function SurveyDetails({installer,surveys,jobs,period,onOpenJob,onClose,canEdit=false,onSave}:any){
 const [all,setAll]=useState(false),[editing,setEditing]=useState<string|null>(null);const safePeriod=period||{start:'',end:''},rows=(Array.isArray(surveys)?surveys:[]).filter((s:any)=>s?.installer_id===installer?.id&&(all||(String(s?.completed_on||'')>=safePeriod.start&&String(s?.completed_on||'')<=safePeriod.end))).map((s:any)=>surveyDetails(s,jobs)).sort((a:any,b:any)=>String(b.completed_on||'').localeCompare(String(a.completed_on||'')));
 return <section className="op-panel" aria-label="Installer survey details"><div className="op-section-head"><h3>{installer?.name||'Installer'} — Surveys</h3><button type="button" onClick={onClose}>Close surveys</button></div><label className="op-check"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Show all bonus periods</label><p>{all?'All recorded surveys':`${displayDate(safePeriod.start)} – ${displayDate(safePeriod.end)}`} · {rows.length} surveys. Category scores use your 0–4 scale.</p>{rows.map((s:any)=><article className="op-survey" key={s.id||s.external_id}><div className="op-section-head"><strong>{displayDate(s.completed_on)||'Date not recorded'} · Customer #{s.customerId||'Not linked'}</strong><strong className={s.score!==null&&s.score<3.6?'op-red':'live-green'}>{s.score===null?'Unrated':s.score.toFixed(2)}{s.score===4?' ★':''}</strong></div>{s.job?<button type="button" className="live-button" onClick={()=>onOpenJob?.(s.job.id)}>{s.job.customer} — Open customer file</button>:<p>{s.ambiguous?'Multiple customer files have this ID; review the customer records.':'Customer information not loaded yet.'}</p>}<div className="op-quality">{['Installation Crew','Workmanship','Clean & Safe','Done Right'].map((label,i)=><div key={label}><span>{label}</span><strong className={s.ratings[i]!==null&&s.ratings[i]<3.6?'op-red':''}>{s.ratings[i]??'No response'}</strong></div>)}</div><small>Reference: {s.external_id||'Not recorded'}</small>{canEdit&&<button type="button" className="live-button" onClick={()=>setEditing(editing===s.id?null:s.id)}>Edit survey / Resurvey</button>}{canEdit&&editing===s.id&&<SurveyEditor key={s.id} survey={s} onSave={onSave} onDone={()=>setEditing(null)}/>}</article>)}{!rows.length&&<p>No surveys in this period.</p>}</section>
}

function SurveyEditor({survey,onSave,onDone}:any){
 const [ratings,setRatings]=useState<(number|null)[]>(survey.ratings.map((n:number|null)=>n===null?null:n+1));
 const [date,setDate]=useState(survey.completed_on),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <form className="op-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onSave({id:survey.id,completedOn:date,ratings,reason,expectedDate:survey.completed_on,expectedRatings:survey.ratings.map((n:number|null)=>n===null?null:n+1)});onDone()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><fieldset disabled={busy}><legend>Edit Guild Quality survey</legend><p>This updates the existing survey without counting it twice. Changing its date moves it to that date’s bonus period. Previously saved bonus snapshots remain unchanged.</p><label>Survey completion / resurvey date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label>{['Installation Crew','Workmanship','Clean & Safe','Done Right'].map((name,i)=><label key={name}>{name}<select value={ratings[i]??''} onChange={e=>setRatings(ratings.map((n,k)=>k===i?(e.target.value===''?null:Number(e.target.value)):n))}><option value="">No response</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} stars</option>)}</select></label>)}<small>Enter original 1–5 star ratings. Displayed scores use the converted 0–4 scale.</small><label>Reason for change<textarea required value={reason} onChange={e=>setReason(e.target.value)} placeholder="Customer resurvey"/></label>{error&&<p role="alert" className="op-red">{error}</p>}<button className="op-primary" type="submit">Save updated survey</button><button type="button" onClick={onDone}>Cancel</button></fieldset></form>
}
