import {env} from '@/lib/server-env';
import bcrypt from 'bcryptjs';
import {database} from '@/db/raw';
export const SESSION_COOKIE='__Host-production_session';
export const randomToken=()=>{const b=crypto.getRandomValues(new Uint8Array(32));return btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
export async function digest(text:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))).map(n=>n.toString(16).padStart(2,'0')).join('')}
export function sessionToken(request:Request){const value=(request.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(SESSION_COOKIE+'='))?.slice(SESSION_COOKIE.length+1);return value&&/^[A-Za-z0-9_-]{43}$/.test(value)?value:null}
export function sessionCookie(token:string,seconds:number){return `${SESSION_COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${seconds}`}
export function passwordProblem(value:string){return value.length<8?'Use at least 8 characters.':new TextEncoder().encode(value).length>72?'Use a password no longer than 72 bytes (fewer characters for some symbols).':''}
export const hashPassword=(value:string)=>bcrypt.hash(value,12);
export const verifyPassword=(value:string,hash:string)=>bcrypt.compare(value,hash);
export async function currentSession(request:Request){const token=sessionToken(request);if(!token)return null;return database().prepare('SELECT m.*,s.restricted,s.token_hash,s.generation AS session_generation,c.generation,c.must_change,c.password_hash,c.previous_hash FROM sessions s JOIN members m ON m.id=s.member_id JOIN credentials c ON c.member_id=m.id WHERE s.token_hash=? AND s.expires>? AND m.active=1 AND s.generation=c.generation').bind(await digest(token),Date.now()).first() as Promise<any>}
export async function ensureOwner(){const email=(env as any).OWNER_LOGIN_EMAIL?.trim().toLowerCase(),hash=(env as any).OWNER_BOOTSTRAP_PASSWORD_HASH;if(!email||!hash)return;const db=database();await db.batch([db.prepare("INSERT INTO members (id,email,name,role,active) VALUES ('owner',?,'Cory Russell','admin',1) ON CONFLICT DO NOTHING").bind(email),db.prepare("INSERT INTO credentials (member_id,password_hash,must_change,temporary_expires,generation) SELECT 'owner',?,1,?,1 FROM members WHERE id='owner' AND email=? ON CONFLICT DO NOTHING").bind(hash,Date.now()+7*86400000,email)]);}
export async function takeLoginAttempt(email:string,request:Request){const now=Date.now(),expires=now+15*60000,db=database();const ip=request.headers.get('x-vercel-forwarded-for')?.split(',')[0]?.trim()||'unknown';await db.prepare('DELETE FROM login_limits WHERE key IN (SELECT key FROM login_limits WHERE expires<? LIMIT 100)').bind(now).run();for(const entry of [{key:'ip:'+await digest(ip),max:40},{key:'email:'+await digest(email),max:6}]){await db.prepare('INSERT INTO login_limits (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN login_limits.expires<? THEN 1 ELSE login_limits.count+1 END,expires=CASE WHEN login_limits.expires<? THEN excluded.expires ELSE login_limits.expires END').bind(entry.key,expires,now,now).run();const row:any=await db.prepare('SELECT count FROM login_limits WHERE key=?').bind(entry.key).first();if(row.count>entry.max)return false;}return true}
export async function limitedJson(request:Request){const text=await request.text();if(text.length>5000)throw new Error('Invalid input');return JSON.parse(text)}
export function safeNext(value:string|null|undefined){if(!value||!value.startsWith('/')||value.startsWith('//')||value.includes('\\'))return '/';const u=new URL(value,'https://app.local');return u.origin==='https://app.local'&&!['/login','/change-password'].includes(u.pathname)?u.pathname+u.search:'/'}
