import {z} from 'zod';
const text=z.string().trim().max(2000).default('');
const date=z.string().refine(v=>!v||(/^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v)).default('');
export const recordSchema=z.object({customerId:text,legacyJobId:text,thirdPhone:text,zone:text,region:text,productType:text,units:text,loadId:text,completionContractor:text,balanceDue:text,paymentMethod:text,warrantyStatus:text,appointmentDate:date,rtoDate:date,completedDate:date,startDate:date,serviceDate:date,lastPaymentDate:date,reReceivedDate:date,reorderDate:date,callbackDate:date,callbackScheduledDate:date,callbackCompletedDate:date,completionScheduledDate:date,salesCallbackDate:date,salesCallbackCompletedDate:date,callbackContractor:text,email:z.union([z.literal(''),z.string().email()]).default(''),alternatePhone:text,mailingAddress:text,saleDate:date,orderedDate:date,estimatedShipDate:date,warehouseBay:text,salesRep:text,salesRepPhone:text,contractor:text,contractorPhone:text,windowBrand:text,doorBrand:text,productDetails:text,permitNumber:text,permitAuthority:text,permitStatus:text,permitApplied:date,permitIssued:date,inspectionDate:date,permitNotes:text,reorders:z.array(z.object({id:z.string().uuid(),reference:text,description:text,orderedOn:date,expectedOn:date,status:text})).max(100).default([]),additionalWork:z.array(z.object({id:z.string().uuid(),workType:text,materials:text,accessNotes:text,description:text,date:date,period:z.enum(['','AM','PM']).default(''),assignedTo:text,status:text})).max(100).default([]),accrf:z.array(z.object({id:z.string().uuid(),reference:text,requestedOn:date,description:text,status:text})).max(100).default([])}).strict();
export type CustomerRecord=z.infer<typeof recordSchema>;
export const recordFields=[['customerId','Customer ID'],['email','Email'],['alternatePhone','Alternate phone'],['mailingAddress','Mailing address'],['saleDate','Sale date'],['orderedDate','Ordered date'],['estimatedShipDate','Estimated ship date'],['warehouseBay','Warehouse bay'],['salesRep','Sales representative'],['salesRepPhone','Sales rep phone'],['contractor','Contractor'],['contractorPhone','Contractor phone'],['windowBrand','Window brand'],['doorBrand','Door brand'],['productDetails','Window / door details'],['permitNumber','Permit number'],['permitAuthority','Permitting authority'],['permitStatus','Permit status'],['permitApplied','Permit applied'],['permitIssued','Permit issued'],['inspectionDate','Inspection date'],['permitNotes','Permit notes']] as const;

export const profileFields=[['legacyJobId','Original Job ID'],['thirdPhone','Phone 3'],['zone','Zone'],['region','Region'],['productType','Product type'],['units','Units'],['loadId','Load ID'],['completionContractor','Completion contractor'],['balanceDue','Balance due'],['paymentMethod','Payment method'],['warrantyStatus','Labor warranty status'],['callbackContractor','Callback contractor']] as const;
export const historyDateFields=[['appointmentDate','Appointment'],['saleDate','Sale'],['rtoDate','RTO'],['orderedDate','Ordered'],['startDate','Start'],['completedDate','Completed'],['serviceDate','Service scheduled'],['lastPaymentDate','Last payment'],['reReceivedDate','Re-received'],['reorderDate','Reorder'],['callbackDate','Callback'],['callbackScheduledDate','Callback scheduled'],['callbackCompletedDate','Callback completed'],['completionScheduledDate','Completion scheduled'],['salesCallbackDate','Sales callback'],['salesCallbackCompletedDate','Sales callback completed'],['estimatedShipDate','Estimated ship']] as const;
