import {leadStatements} from './lead-form';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function leadRenovationPrintHtml(r:any){
 const field=(label:string,value:unknown)=>'<th>'+label+'</th><td>'+esc(value)+'</td>';
 const answers=(start:number,end:number)=>'<table class="answers"><tbody>'+leadStatements.slice(start,end).map((s,n)=>{const yes=r.answers[start+n];return '<tr><td class="choices"><span class="check">'+(yes?'✓':'')+'</span> Yes <span class="check">'+(!yes?'✓':'')+'</span> No</td><td>'+esc(s)+'</td></tr>'}).join('')+'</tbody></table>';
 const date=new Date(r.signedAt).toLocaleDateString('en-US',{timeZone:'America/New_York',month:'2-digit',day:'2-digit',year:'numeric'}).replaceAll('/','-');
 return '<!doctype html><html><head><meta charset="utf-8"><title>Lead Renovation Procedures Record</title><style>@page{size:letter portrait;margin:0}*{box-sizing:border-box}html,body{margin:0!important;padding:0!important;background:white;color:black;font:10pt Arial,sans-serif}.sheet{width:100%;padding:0.6in 0.65in!important}h1{text-align:center;font-size:20pt;margin:0 0 16px}h2{font-size:13pt;text-decoration:underline;margin:16px 0 6px}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{overflow-wrap:anywhere}table.info th,table.info td{border:1px solid #444;padding:6px;text-align:left}table.info th{width:24%;background:#eee}.info{margin-bottom:10px}.answers td{padding:4px 0;vertical-align:top}.choices{width:104px;white-space:nowrap}.check{display:inline-block;width:14px;height:14px;border:1.5px solid black;line-height:12px;text-align:center;font-weight:bold;font-size:13px;vertical-align:middle}p{margin:7px 0;line-height:1.3}.note{font-size:9pt}.signature{margin-top:18px;break-inside:avoid}tr{break-inside:avoid}button{margin:12px;padding:10px 18px;border:1px solid #333;background:white;border-radius:5px}@media print{button{display:none}h2{break-after:avoid}thead{display:table-header-group}}</style></head><body><button onclick="window.print()">Print / Save PDF</button><main class="sheet"><h1>Lead Renovation Procedures Record</h1><table class="info"><tbody><tr>'+field('Customer ID #:',r.customerId)+'</tr><tr>'+field('Customer Name:',r.customerName)+'</tr><tr>'+field('Street Address:',r.address)+'</tr><tr>'+field('City / State / Zip:',[r.city,r.state,r.zip].join(' '))+'</tr></tbody></table><table class="info"><tbody><tr>'+field('Renovator Name:',r.renovatorName)+'</tr><tr>'+field('Renovator ID #:',r.renovatorId)+'</tr><tr>'+field('EPA Certification #:',r.epaCertification)+'</tr></tbody></table><h2>EPA Credentials</h2>'+answers(0,1)+'<h2>Determination of Renovation Procedures</h2><p class="note">The home and work areas were inspected by a Certified EPA Lead-Safe Renovator who made the following determination:</p>'+answers(1,2)+'<p class="note">If Yes, answer every statement below. If No, you certify that standard installation procedures will not disturb potential lead paint in the home.</p><h2>Renovation Procedure Check List</h2>'+answers(2,12)+'<h2>Customer Copy</h2>'+answers(12,13)+'<div class="signature"><p>I, '+esc(r.renovatorName)+', certify that I have completed this form truthfully and accurately.</p><p><b>Renovator electronic signature:</b> '+(r.signatureDataUrl?'<br><img alt="Renovator signature" style="display:block;max-width:280px;width:100%;height:auto" src="'+esc(r.signatureDataUrl)+'">':esc(r.signature))+'</p><p><b>Date:</b> '+esc(date)+'</p></div><p class="note">Production Desk · Lead Renovation Procedures Record · Safe inset print</p></main></body></html>';
}
export function printLeadRenovation(record:any){const w=window.open('','_blank');if(!w)throw Error('Allow pop-ups to print the lead renovation form.');w.document.open();w.document.write(leadRenovationPrintHtml(record));w.document.close();}
