const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const date=(v:unknown)=>{const m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})/);return m?m[2]+'-'+m[3]+'-'+m[1]:String(v||'')};
const parties=['Factory','Installer','Sales Rep','Customer','Window World'];
export function reorderPrintHtml(j:any,r:any){
 const items:any[]=r.items||[];
 const types=['Whole Window','Screen Frame','Sash','Frame'];
 const groups=Object.fromEntries(types.map(t=>[t,items.filter(i=>i.type===t)]));
 const pages=Math.max(1,...types.map(t=>Math.ceil(groups[t].length/8)));
 const long=(v:unknown,limit:number)=>{const s=String(v||'');return esc(s.length>limit?s.slice(0,limit)+'… (continued in details)':s)};
 const field=(name:string,v:unknown)=>'<span class="field"><b>'+esc(name)+'</b><span class="line">'+esc(v)+'</span></span>';
 const table=(rows:any[],headers:string[],keys:string[],widths?:number[])=>'<table class="items">'+(widths?'<colgroup>'+widths.map(w=>'<col style="width:'+w+'%">').join('')+'</colgroup>':'')+'<thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+Array.from({length:8},(_,n)=>{const i=rows[n];return '<tr>'+keys.map(k=>'<td>'+ (i?long(i[k]||(k==='returnDate'?date(r.returnDate):k==='managerInitials'?r.managerInitials:''),45):'&nbsp;')+'</td>').join('')+'</tr>'}).join('')+'</tbody></table>';
 const sheets=Array.from({length:pages},(_,page)=>'<section class="sheet form-sheet"><div class="page-meta"><span>Form page: '+(page+1)+' of '+pages+'</span><span>Date: '+esc(date(r.submittedAt))+'</span></div><h1>Contractor Reorder Form</h1><div class="header-row">'+field('Customer Name:',j.customer)+field('Contractor Name:',j.crew||r.submittedName)+'</div><div class="header-row secondary">'+field('Cust ID #:',j.number)+field('Sales Rep:',j.salesRep)+field('Contractor ID:',j.contractorId)+'</div><div class="reason"><b>Why is this reorder necessary?</b> '+long(r.reason,260)+'</div><div class="charge-options"><b>Charge Back To:</b>'+parties.map(p=>'<span class="charge-option"><span class="check-box">'+((r.chargebacks||[]).includes(p)?'&#10003;':'')+'</span>'+esc(p)+'</span>').join('')+'</div><p class="charge-note"><b>Chargeback Notes:</b> '+long(r.chargebackNote,140)+'</p><h2>Whole Windows that need to be Reordered</h2>'+table(groups['Whole Window'].slice(page*8,page*8+8),['Window #','Window Size Written on Order Form','Actual Size of Window you are returning','Reorder Size (Size required to fit opening)','Return Date','Mgr Initials'],['window','orderedSize','actualSize','reorderSize','returnDate','managerInitials'],[9,23,23,25,11,9])+'<h2 class="tag">WINDOW TAG MUST BE RETURNED WITH WINDOW !!!</h2><div class="parts-grid">'+[['Screen Frame','Screen Frames Only',['Window #','Serial #'],['window','serial']],['Sash','Sashes Only',['Window #','Serial #','Sash Position'],['window','serial','position']],['Frame','Frames Only',['Window #','Serial #'],['window','serial']]].map(([t,title,headers,keys])=>'<div><h3>'+title+'</h3>'+table(groups[t as string].slice(page*8,page*8+8),headers as string[],keys as string[])+'</div>').join('')+'</div><div class="signoffs"><p>I certify that all other work performed on this job is complete except the items and remaining work recorded with this request. Furthermore, I acknowledge responsibility for the fit of the reordered windows.</p><div class="header-row">'+field('Submitted by:',r.submittedName)+field('Date:',date(r.submittedAt))+'</div><p><b>Other work remaining:</b> '+long(r.remaining||'None',160)+'</p><p>I have reviewed this information in detail and recorded my decision below.</p><div class="header-row">'+field('Reviewing Field Supervisor:',r.reviewedBy)+field('Date:',date(r.reviewedAt))+'</div><p><b>Review decision:</b> '+esc(r.status)+' · '+long(r.comment,120)+'</p></div><footer>Production Desk · Digital Reorder Form · Safe inset print v2</footer></section>').join('');
 const details='<section class="sheet detail-sheet"><h1>Reorder Details</h1><p class="customer-header">'+esc(j.customer)+' · Customer ID #'+esc(j.number)+'</p><p><b>Reason:</b> '+esc(r.reason)+'</p><p><b>Chargeback Notes:</b> '+esc(r.chargebackNote)+'</p><p><b>Other work remaining:</b> '+esc(r.remaining||'None')+'</p>'+items.map((i,n)=>'<article><h3>Item '+(n+1)+' · '+esc(i.type)+' · '+esc(i.window)+' · Qty '+esc(i.quantity)+'</h3><p>'+esc([i.orderedSize&&'Ordered: '+i.orderedSize,i.actualSize&&'Actual: '+i.actualSize,i.reorderSize&&'Reorder: '+i.reorderSize,i.serial&&'Serial: '+i.serial,i.position&&'Sash position: '+i.position,i.panelSide&&'Panel side: '+i.panelSide,i.panelOperation&&'Panel operation: '+i.panelOperation,i.description].filter(Boolean).join(' · '))+'</p></article>').join('')+'<p><b>Review notes:</b> '+esc(r.comment)+'</p><p>Vendor: '+esc(r.vendor)+' · Reference: '+esc(r.reference)+'<br>Ordered: '+esc(date(r.orderedDate))+' · Estimated ship: '+esc(date(r.estimatedShipDate))+'<br>Received: '+esc(date(r.receivedDate))+' · Bay: '+esc(r.bay)+'<br>Return date: '+esc(date(r.returnDate))+' · Manager initials: '+esc(r.managerInitials)+' · Tag returned: '+(r.tagReturned?'Yes':'No')+'</p><p>Submitted: '+esc(r.submittedName)+' · '+esc(r.submittedAt)+'<br>Reviewed: '+esc(r.reviewedBy)+' · '+esc(r.reviewedAt)+'</p></section>';
 const photos=items.flatMap(i=>(i.photos||[]).map((a:any)=>'<section class="sheet photo-sheet"><h2>'+esc(j.customer)+' · '+esc(i.type)+' · '+esc(i.window)+'</h2><p>'+esc(a.name)+'</p><img alt="'+esc(a.name)+'" src="/api/attachments?key='+encodeURIComponent(a.key)+'"/></section>')).join('');
 return '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Contractor Reorder Form</title><style>'+
 '@page{size:letter portrait;margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0;min-width:0;width:100%;font:11px Arial,sans-serif;color:#111;background:white}.toolbar{padding:16px;background:#eee}.toolbar button{padding:10px 18px}.sheet{width:100%;max-width:8.5in;margin:0 auto;padding:0.6in 0.65in;box-decoration-break:clone;-webkit-box-decoration-break:clone;overflow:visible;break-after:page}.sheet:last-child{break-after:auto}.page-meta{display:flex;justify-content:space-between;font-size:11px}h1{text-align:center;font-size:23px;margin:16px 0 20px}h2{text-align:center;font-size:17px;margin:12px 0 5px}h3{text-align:center;font-size:12px;margin:0 0 4px}.header-row{display:flex;gap:24px;margin:12px 0;font-size:14px}.header-row.secondary{font-size:12px;gap:16px}.field{display:flex;flex:1;gap:5px;min-width:0;align-items:baseline}.line{flex:1;border-bottom:1px solid #555;min-height:18px;overflow-wrap:anywhere}.reason{min-height:52px;line-height:1.65;border-bottom:1px solid #555;margin:14px 0 12px;font-size:12px;overflow-wrap:anywhere}.charge-options{display:flex;flex-wrap:wrap;gap:9px;align-items:center;font-size:11px}.charge-option{display:inline-flex;align-items:center;gap:4px}.check-box{display:inline-flex;width:22px;height:22px;align-items:center;justify-content:center;border:2px solid #111;font-size:22px;font-weight:bold;line-height:1;flex-shrink:0}.charge-note{margin:7px 0;font-size:11px}.items{width:100%;table-layout:fixed;border-collapse:collapse}.items th,.items td{border:1px solid #555;padding:3px;overflow-wrap:anywhere;font-size:10px;font-weight:normal}.items td{height:19px}.items tr{break-inside:avoid}.items th{text-align:center}.tag{font-size:16px;margin:13px 0 10px}.parts-grid{display:grid;grid-template-columns:1fr 1.2fr 1fr;gap:12px}.signoffs{margin-top:14px;font-size:10px;line-height:1.4}.signoffs .header-row{font-size:11px;margin:10px 0}.signoffs p{margin:8px 0}footer{margin-top:12px;font-size:8px;color:#555}p{white-space:pre-wrap;overflow-wrap:anywhere}.detail-sheet article{break-inside:avoid;margin:15px 0}.detail-sheet h3{text-align:left}.photo-sheet img{display:block;max-width:100%;max-height:8in;object-fit:contain}.customer-header{font-size:16px;font-weight:bold}@media print{.toolbar{display:none!important}html,body{width:100%!important;margin:0!important;padding:0!important;overflow:visible!important}.sheet{padding:0.6in 0.65in!important;width:100%!important;max-width:8.5in!important;margin:0 auto!important;transform:none!important}}'+
 '</style></head><body><div class="toolbar"><button onclick="window.print()">Print / Save PDF</button><p>Letter · Portrait · Fit to printable area. The form includes its own safety margins.</p></div>'+sheets+details+photos+'</body></html>';
}
export function printReorder(j:any,r:any){const w=window.open('','_blank');if(!w)throw Error('Allow pop-ups to open the reorder form.');w.document.open();w.document.write(reorderPrintHtml(j,r));w.document.close();}
