'use client';
import {useState} from 'react';
import {type Job} from './model';
import {formatPhone} from '@/lib/phone';
export function ManualCustomer({jobs,date,onSave,onCancel}:{jobs:Job[];date:string;onSave:(job:Job)=>void;onCancel:()=>void}){
 const [product,setProduct]=useState<'Windows'|'Entry Doors'>('Windows'),[status,setStatus]=useState<Job['official']>('RCD'),[error,setError]=useState('');
 return <section className="op-panel"><h2>Add Customer</h2><p>Manually enter an active or older job. Windows and Entry Doors require separate customer IDs.</p><form className="op-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),v=(key:string)=>String(f.get(key)||'').trim();if(!v('customer')||!v('customerId')){setError('Enter a customer name and ID.');return}if(jobs.some(j=>j.customerId.toLowerCase()===v('customerId').toLowerCase())){setError('This customer ID already exists. Open that job instead.');return}onSave({id:'MANUAL-'+crypto.randomUUID(),customerId:v('customerId'),customer:v('customer'),address:v('address'),city:v('city'),customerPhone:formatPhone(v('customerPhone')),customerEmail:v('customerEmail'),product,slidingDoors:product==='Windows'?Number(v('slidingDoors')):0,due:v('due')===''?null:Number(v('due')),official:status,received:v('received'),started:v('started'),inc:v('inc'),salesRep:v('salesRep'),salesRepPhone:formatPhone(v('salesRepPhone')),supervisor:v('supervisor'),bay:v('bay'),instructions:v('instructions'),notes:v('notes'),reorder:v('reorder'),date:'',period:'AM',stop:1,crew:'',field:status==='INCOMP'?'Approved incomplete':status==='PROD'?'In progress':status==='RCD'?'Ready to schedule':'Awaiting materials',action:'',owner:'',deadline:'',history:[date+' · Manual customer entry'],evidence:[],submission:''})}}>
 <div className="op-form-grid">{[['customerId','Customer ID'],['customer','Customer name'],['address','Job address'],['city','City'],['customerPhone','Customer phone'],['customerEmail','Customer email'],['salesRep','Sales Rep name'],['salesRepPhone','Sales Rep phone'],['bay','Warehouse bay']].map(([key,label])=><label key={key}>{label}<input name={key} required={['customerId','customer','address','city'].includes(key)} type={key.endsWith('Email')?'email':key.endsWith('Phone')?'tel':'text'} maxLength={300}/></label>)}<label>Product<select value={product} onChange={e=>setProduct(e.target.value as typeof product)}><option>Windows</option><option>Entry Doors</option></select></label>{product==='Windows'&&<label>Sliding doors<input name="slidingDoors" type="number" min="0" max="999" step="1" defaultValue="0" required/></label>}<label>Amount due (blank if unknown)<input name="due" type="number" min="0" step="0.01"/></label><label>Field Supervisor<select name="supervisor" required><option value="">Select supervisor</option><option>Supervisor A</option><option>Supervisor B</option></select></label><label>Current official status<select value={status} onChange={e=>setStatus(e.target.value as Job['official'])}><option value="ORD">Ordered</option><option value="RCD">RCVD</option><option value="PROD">PROD</option><option value="INCOMP">INC</option></select></label>{[['received','Materials received date'],['started','Production start date'],['inc','INC entry date']].map(([key,label])=><label key={key}>{label}<input name={key} type="date" max={date} required={key===({RCD:'received',PROD:'started',INCOMP:'inc'} as Record<string,string>)[status]}/></label>)}</div>
 <label>Job instructions<textarea name="instructions" maxLength={4000}/></label><label>Sales / handoff notes<textarea name="notes" maxLength={4000}/></label><label>Reorder information<textarea name="reorder" maxLength={4000}/></label>{error&&<p role="alert">{error}</p>}<div><button className="op-primary">Add Customer</button> <button type="button" onClick={onCancel}>Cancel</button></div><small>You can schedule work after saving. Dates above preserve the job’s existing aging history.</small></form></section>
}
