export type Job = {id:string;customerId:string;product:'Windows'|'Entry Doors';slidingDoors:number;instructions:string;reorder:string;customer:string;city:string;address:string;due:number|null;official:'ORD'|'RCD'|'PROD'|'INCOMP'|'CLSD';received:string;started:string;inc:string;date:string;period:string;stop:number;crew:string;supervisor:string;field:string;action:string;owner:string;deadline:string;bay:string;notes:string;history:string[];evidence:string[];submission:''|'Complete'|'Incomplete'};
export const today='2026-09-15';
export function days(from:string,to:string){return from?Math.floor((Date.parse(to+'T12:00:00Z')-Date.parse(from+'T12:00:00Z'))/86400000):null}
export function aging(j:Job,date:string){const start=j.official==='RCD'?j.received:j.official==='PROD'?j.started:j.official==='INCOMP'?j.inc:'';const age=days(start,date);const limit=j.official==='INCOMP'?45:j.official==='PROD'?7:30;const aged=age!==null&&(j.official==='INCOMP'?age>=limit:age>limit);return {age,aged,soon:age!==null&&!aged&&limit-age<=7,warning:j.official==='INCOMP'&&age!==null&&age>30,remaining:age===null?null:Math.max(0,limit-age),missing:['RCD','PROD','INCOMP'].includes(j.official)&&age===null}}
export function tier(value:number,kind:'dollars'|'jobs'){if(value===0)return 1.2;const thresholds=kind==='dollars'?[45735,76225,106715,137206]:[6,12,19,25];return [1,.75,.5,.25][thresholds.findIndex(x=>value<=x)]??0}
export function qualityTier(score:number){return score>=3.8?1.2:score>=3.75?1:score>=3.7?.75:score>=3.6?.5:score>=3.5?null:0}
export const surveys=[{id:'S-01',date:'2026-08-27',crew:'Coastal Crew',ratings:[5,5,5,5]},{id:'S-02',date:'2026-09-03',crew:'Bay Crew',ratings:[5,4,5,5]},{id:'S-03',date:'2026-09-10',crew:'Coastal Crew',ratings:[5,5,5,4]},{id:'S-04',date:'2026-09-14',crew:'Bay Crew',ratings:[5,5,5,5]}];
export function quality(asOf:string){const included=surveys.filter(s=>s.date>='2026-08-26'&&s.date<='2026-09-29'&&s.date<=asOf);const categories=[0,1,2,3].map(i=>included.length?included.reduce((sum,s)=>sum+s.ratings[i]-1,0)/included.length:0);return {included,categories,score:categories.reduce((a,b)=>a+b,0)/4}}
const base:Job={id:'',reorder:'',customerId:'',product:'Windows',slidingDoors:0,instructions:'Protect floors and landscaping. Confirm access with the homeowner before starting.',customer:'',city:'St. Petersburg',address:'Sample address · Tampa Bay',due:0,official:'RCD',received:'2026-09-10',started:'',inc:'',date:'',period:'AM',stop:1,crew:'Coastal Crew',supervisor:'Supervisor A',field:'Ready to schedule',action:'Schedule installation',owner:'Production assistant',deadline:'2026-09-18',bay:'A-12',notes:'Sales handoff: protect interior flooring, review window operation with homeowner, and photograph each finished opening.',history:['Sales handoff received · Demo sales system'],evidence:[],submission:''};
export function seed():Job[]{return [
{...base,id:'DEMO-101',customer:'Harbor House',due:12400,received:'2026-08-03',date:'2026-09-18',field:'Scheduled',action:'Confirm permit release before installation'},
{...base,id:'DEMO-102',customer:'Palm Cottage',due:6800,official:'PROD',started:'2026-09-03',date:today,field:'Awaiting supervisor review',submission:'Complete',evidence:['Demo completion certificate.pdf','Demo exterior photos (4)'],action:'Review completion packet',owner:'Supervisor A'},
{...base,id:'DEMO-103',customer:'Bayview Home',due:0,official:'INCOMP',inc:'2026-07-25',started:'2026-07-24',crew:'Bay Crew',supervisor:'Supervisor B',field:'Approved incomplete',action:'Confirm replacement sash delivery',owner:'Supervisor B'},
{...base,id:'DEMO-104',customer:'Sunset Residence',due:9500,received:'2026-08-20',field:'Ready to schedule',action:'Call customer to schedule',deadline:'2026-09-17'},
{...base,id:'DEMO-105',customer:'Gulf Terrace',due:4200,official:'PROD',started:today,date:today,crew:'Bay Crew',supervisor:'Supervisor B',field:'In progress',action:'Upload installation results',owner:'Bay Crew'},
{...base,id:'DEMO-106',customer:'Oak Landing',due:7500,official:'INCOMP',inc:'2026-08-05',field:'Approved incomplete',action:'Schedule return appointment',owner:'Production assistant'},
{...base,id:'DEMO-107',customer:'Pelican Place',due:null,official:'RCD',received:'2026-08-01',field:'Ready to schedule',action:'Verify missing balance with office',owner:'Production assistant'},
{...base,id:'DEMO-108',customer:'Harbor House',product:'Entry Doors',due:8100,official:'ORD',received:'',field:'Awaiting materials',action:'Record product receipt',bay:''}
].map((j,i)=>({...j,customerId:'SAMPLE-'+String(1001+i)})) as Job[]}
