'use client';
import {useState} from 'react';
export type PreviewUser={id:string;name:string;email:string;phone:string;employee:string;address:string;emergency:string;role:string;theme:string};
export const roles=['Administrator','Field Supervisor','Production Assistant','Installer'];
export const demoUsers:PreviewUser[]=roles.map((role,i)=>({id:'USER-'+i,name:'Demo '+role,email:'demo'+i+'@example.com',phone:'',employee:'',address:'',emergency:'',role,theme:'light'}));
export const themes=[['light','Light','Default',''],['dark','Dark','Black, white and blue',''],['gators','Florida Gators','Orange and blue','/florida-gators-logo.png'],['fsu','Florida State Seminoles','Garnet and gold','/fsu-logo.png'],['mexico','Mexico','Green, white and red','/flag-mx.svg'],['brazil','Brazil','Green, yellow and blue','/flag-br.svg'],['cuba','Cuba','Blue, white and red','/flag-cu.svg'],['usa','United States','Red, White, and Blue','/flag-us.svg']];
export function PreviewSettings({role,users,setUsers,onTheme}:{role:string;users:PreviewUser[];setUsers:(users:PreviewUser[])=>void;onTheme:(theme:string)=>void}){
 const ownId=demoUsers.find(u=>u.role===role)!.id,own=users.find(u=>u.id===ownId)!;
 const [tab,setTab]=useState('My profile'),[editing,setEditing]=useState<PreviewUser|null>(null),[message,setMessage]=useState(''),[deleting,setDeleting]=useState('');
 const admin=role==='Administrator';
 function save(user:PreviewUser){if(users.some(u=>u.id!==user.id&&u.email.toLowerCase()===user.email.toLowerCase())){setMessage('That email already belongs to an account.');return}setUsers(users.some(u=>u.id===user.id)?users.map(u=>u.id===user.id?user:u):[...users,user]);setEditing(null);setMessage('Profile saved in this preview session. No account invitation was sent.')}
 return <section className="op-panel"><div className="op-file-nav">{['My profile','Appearance',...(admin?['Account management']:[])].map(t=><button key={t} onClick={()=>{setTab(t);setEditing(null);setMessage('')}} aria-pressed={tab===t}>{t}</button>)}</div>{message&&<p role="status">{message}</p>}
 {tab==='My profile'&&<><h2>My profile</h2><UserForm key={own.id} user={own} onSave={save}/></>}
 {tab==='Appearance'&&<><h2>Profile theme</h2><div className="op-theme-grid">{themes.map(([id,name,description,image])=><button key={id} aria-pressed={own.theme===id} onClick={()=>{setUsers(users.map(u=>u.id===ownId?{...u,theme:id}:u));onTheme(id);setMessage('Theme applied for this preview profile.')}}>{image&&<img src={image} alt="" width="48" height="32"/>}<strong>{name}{own.theme===id?' ✓':''}</strong><span>{description}</span></button>)}</div></>}
 {tab==='Account management'&&admin&&<><h2>Account management</h2><p>Demo accounts only. Adding or deleting here does not change live sign-in access.</p><button className="op-primary" onClick={()=>setEditing({id:crypto.randomUUID(),name:'',email:'',phone:'',employee:'',address:'',emergency:'',role:'Installer',theme:'light'})}>Add user</button>{editing?<UserForm key={editing.id} user={editing} admin locked={demoUsers.some(u=>u.id===editing.id)} onSave={save} onCancel={()=>setEditing(null)}/>:users.map(u=><article className="op-visit" key={u.id}><strong>{u.name}</strong><p>{u.role} · {u.email}<br/>Employee #: {u.employee||'Not entered'}</p><button onClick={()=>setEditing(u)}>Edit information</button>{!demoUsers.some(d=>d.id===u.id)&&<button onClick={()=>setDeleting(u.id)}>Delete account</button>}{deleting===u.id&&<div role="alert"><p>Delete {u.name} from this preview?</p><button onClick={()=>{setUsers(users.filter(x=>x.id!==u.id));setDeleting('')}}>Confirm delete</button><button onClick={()=>setDeleting('')}>Cancel</button></div>}</article>)}<small>The four role-preview accounts are protected so every preview role remains available.</small></>}
 </section>
}
function UserForm({user,admin=false,locked=false,onSave,onCancel}:{user:PreviewUser;admin?:boolean;locked?:boolean;onSave:(user:PreviewUser)=>void;onCancel?:()=>void}){return <form className="op-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({...user,...Object.fromEntries(f) } as PreviewUser)}}><div className="op-form-grid">{[['name','Full name'],['email','Email'],['phone','Phone'],['employee','Employee #'],['address','Mailing address'],['emergency','Emergency contact and phone']].map(([key,label])=><label key={key}>{label}<input name={key} defaultValue={user[key as keyof PreviewUser]} type={key==='email'?'email':key==='phone'?'tel':'text'} required={key==='name'||key==='email'} maxLength={300}/></label>)}{admin&&<label>Role<select name="role" defaultValue={user.role} disabled={locked}>{roles.map(r=><option key={r}>{r}</option>)}</select></label>}</div><button className="op-primary">Save information</button>{onCancel&&<button type="button" onClick={onCancel}>Cancel</button>}</form>}
