'use client';
import {useEffect,useState} from 'react';
import dynamic from 'next/dynamic';
import './tracking.css';
const MapCanvas=dynamic(()=>import('./map-canvas'),{ssr:false});
export default function CustomerMap(){
 const [point,setPoint]=useState<any>(null),[message,setMessage]=useState('Getting ready to welcome your installer…'),[offline,setOffline]=useState(false),[now,setNow]=useState(Date.now());
 useEffect(()=>{const token=location.hash.slice(1);let active=true;const load=async()=>{try{const r=await fetch('/api/location/public?token='+encodeURIComponent(token),{cache:'no-store',referrerPolicy:'no-referrer'});if(!r.ok){if([403,404,410].includes(r.status)&&active)setPoint(null);throw Error((await r.json()).error||'Updates are temporarily unavailable.')}const d=await r.json();if(active){setPoint(d);setOffline(false);setMessage(d.stale?'Updates paused — this is the last known location.':'Your Window World team is on the way!')}}catch(e){if(active){setOffline(true);setMessage((e as Error).message)}}};void load();const t=setInterval(()=>{setNow(Date.now());void load()},15000);return()=>{active=false;clearInterval(t)}},[]);
 useEffect(()=>{if(point&&now>=point.expires){setPoint(null);setMessage('This tracking link has expired.');}},[now,point]);
 const stale=offline||point?.stale||now-Number(point?.observedAt)>120000;
 const time=(value:number)=>new Date(value).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:'America/New_York'});
 return <main className="customer-tracking"><header className="tracking-brand"><img src="/ww-round-logo.png" alt="Window World"/><span>WINDOW WORLD<small>Tampa Bay · A better view is on its way</small></span></header><section className="tracking-welcome"><span className="tracking-pill">Your installation, one step closer</span><h1>{point?'We’re on our way!':'Your Window World visit'}</h1><p role="status">{message}</p></section>{point&&<><section className="tracking-person">{point.photo?<img className="tracking-avatar" src={point.photo} alt={point.name}/>:<span className="tracking-avatar tracking-initials">{String(point.name||'WW').split(' ').map(v=>v[0]).slice(0,2).join('')}</span>}<div><small>Meet your installer</small><h2>{point.name}</h2><p>We look forward to seeing you!</p></div></section><section className="tracking-facts"><div><span>Estimated arrival</span><strong>{point.arrivalAt&&now<=point.arrivalAt+600000?time(point.arrivalAt-300000)+' – '+time(point.arrivalAt+600000):point.arrivalAt?'Awaiting updated ETA':'Estimate pending'}</strong><small>Installer-provided estimate · Eastern time{stale?' · Location updates paused':''}</small></div><div><span>Your scheduled stop</span><strong>{point.stopNumber?'#'+point.stopNumber:'Not assigned'}</strong><small>Your stop on the crew’s schedule</small></div></section><section className="tracking-map"><div className="tracking-map-heading"><h2>{stale?'Last known location':'Follow our progress'}</h2><span className="tracking-pill">{stale?'Updates paused':'Location sharing'}</span></div><MapCanvas points={[{...point,stale}]}/><p>Last location: {new Date(point.observedAt).toLocaleString('en-US',{timeZone:'America/New_York'})} ET · GPS accuracy about {Math.round(point.accuracy)} meters.</p></section><p className="tracking-footer">Arrival times are approximate and may change with traffic. This private link is available only for your current trip.</p></>}{!point&&<section className="tracking-person"><p>{offline?'Please contact the office if you need help with your appointment.':'Your installer’s details will appear here shortly.'}</p></section>}</main>
}
