import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';import {resolve} from 'node:path';import {createServer} from 'vite';import bcrypt from 'bcryptjs';
const sqlite=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));
function prepare(sql){let args=[];return {bind(...a){args=a;return this},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return {results:sqlite.prepare(sql).all(...args)}},async run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}}}}};
const env={OWNER_LOGIN_EMAIL:'owner@example.com',OWNER_BOOTSTRAP_PASSWORD_HASH:await bcrypt.hash('InitialOwnerSecret1!',4),DB:{prepare,async batch(statements){sqlite.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}}}};globalThis.__nativeAuthEnv=env;
const vite=await createServer({configFile:false,resolve:{alias:{'@':resolve('.')}},plugins:[{name:'fake-env',enforce:'pre',resolveId(id){if(id==='cloudflare:workers')return '\0native-env'},load(id){if(id==='\0native-env')return 'export const env=globalThis.__nativeAuthEnv'}}],server:{middlewareMode:true,hmr:false}});
const login=await vite.ssrLoadModule('/app/api/auth/login/route.ts'),change=await vite.ssrLoadModule('/app/api/auth/change-password/route.ts'),logout=await vite.ssrLoadModule('/app/api/auth/logout/route.ts'),team=await vite.ssrLoadModule('/app/api/team/route.ts'),reset=await vite.ssrLoadModule('/app/api/team/reset-password/route.ts'),me=await vite.ssrLoadModule('/app/api/me/route.ts');await vite.close();
function req(path,body,cookie='',origin='https://example.com'){return new Request('https://example.com'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',origin,cookie,'cf-connecting-ip':'192.0.2.5'},body:body?JSON.stringify(body):undefined})}
const cookieOf=r=>r.headers.get('set-cookie')?.split(';')[0]||'';
async function signIn(email,password){return login.POST(req('/api/auth/login',{email,password}))}
async function activate(email,password,newPassword){const r=await signIn(email,password);assert.equal(r.status,200,await r.clone().text());const changed=await change.POST(req('/api/auth/change-password',{password:newPassword},cookieOf(r)));assert.equal(changed.status,200,await changed.clone().text());return cookieOf(changed)}
async function create(cookie,email,role,supervisorId=null,extra={}){const r=await team.POST(req('/api/team',{email,name:email.split('@')[0],role,supervisorId,active:true,...extra},cookie));assert.equal(r.status,200,await r.clone().text());return {...await r.json(),id:sqlite.prepare('SELECT id FROM members WHERE email=?').get(email).id}}
test('one-time login, forced password changes, revocation, and owner-only administrator grants',async()=>{
 assert.equal((await me.GET(new Request('https://example.com/api/me',{headers:{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'owner@example.com'}}))).status,401);
 assert.equal((await login.POST(req('/api/auth/login',{email:'owner@example.com',password:'InitialOwnerSecret1!'},'','https://evil.test'))).status,403);
 const first=await signIn('owner@example.com','InitialOwnerSecret1!');assert.equal(first.status,200);assert.match(first.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Lax/);const restricted=cookieOf(first);assert.equal((await me.GET(req('/api/me',null,restricted))).status,428);assert.equal((await signIn('owner@example.com','InitialOwnerSecret1!')).status,401);
 assert.equal((await change.POST(req('/api/auth/change-password',{password:'1234567'},restricted))).status,400);assert.equal((await change.POST(req('/api/auth/change-password',{password:'InitialOwnerSecret1!'},restricted))).status,400);
 const activated=await change.POST(req('/api/auth/change-password',{password:'Owner8!!'},restricted));assert.equal(activated.status,200);const owner=cookieOf(activated);assert.notEqual(owner,restricted);assert.equal((await me.GET(req('/api/me',null,restricted))).status,401);assert.equal((await me.GET(req('/api/me',null,owner))).status,200);
 assert.equal((await signIn('owner@example.com','InitialOwnerSecret1!')).status,401);const relogin=await signIn('owner@example.com','Owner8!!');assert.equal(relogin.status,200);
 const manager=await create(owner,'manager@example.com','admin');assert.ok(manager.temporaryPassword);const stored=sqlite.prepare('SELECT password_hash FROM credentials WHERE member_id=?').get(manager.id);assert.notEqual(stored.password_hash,manager.temporaryPassword);const managerCookie=await activate(manager.email,manager.temporaryPassword,'ManagerSecretPhrase1!');
 assert.equal((await team.POST(req('/api/team',{email:'escalation@example.com',name:'Escalation',role:'admin',supervisorId:null,active:true},managerCookie))).status,403);
 assert.equal((await reset.POST(req('/api/team/reset-password',{id:'owner'},managerCookie))).status,403);
 const supervisor=await create(managerCookie,'supervisor@example.com','supervisor',null,{phone:'(813) 555-0123'});assert.equal(sqlite.prepare('SELECT phone FROM members WHERE id=?').get(supervisor.id).phone,'(813) 555-0123');assert.equal(supervisor.emailStatus,'not_configured');const assistant=await create(managerCookie,'assistant@example.com','production_assistant');const installer=await create(managerCookie,'installer@example.com','installer',supervisor.id);
 const installerUpdate={id:installer.id,email:installer.email,name:'Installer',role:'installer',supervisorId:supervisor.id,active:true};
 const idSaved=await team.POST(req('/api/team',{...installerUpdate,installerCode:' c001234 '},managerCookie));assert.equal(idSaved.status,200,await idSaved.clone().text());
 assert.equal(sqlite.prepare('SELECT installer_code FROM members WHERE id=?').get(installer.id).installer_code,'C001234');
 for(const invalid of ['A1234','C','C12A','1234'])assert.equal((await team.POST(req('/api/team',{...installerUpdate,installerCode:invalid},managerCookie))).status,400);
 assert.equal((await team.POST(req('/api/team',installerUpdate,managerCookie))).status,200);assert.equal(sqlite.prepare('SELECT installer_code FROM members WHERE id=?').get(installer.id).installer_code,'C001234');
 const installerDirectory=await (await team.GET(req('/api/team',null,owner))).json();assert.equal(installerDirectory.members.find(m=>m.id===installer.id).installer_code,'C001234');
 const assistantCookie=await activate(assistant.email,assistant.temporaryPassword,'AssistantPassphrase1!');assert.equal((await team.POST(req('/api/team',{email:'denied@example.com',name:'Denied',role:'installer',supervisorId:supervisor.id,active:true},assistantCookie))).status,403);
 const listed=await (await team.GET(req('/api/team',null,owner))).json();assert.ok(listed.members.every(m=>!('password_hash' in m)&&!('temporaryPassword' in m)));
 const installerCookie=await activate(installer.email,installer.temporaryPassword,'InstallerPassphrase1!');const resetResponse=await reset.POST(req('/api/team/reset-password',{id:installer.id},managerCookie));assert.equal(resetResponse.status,200);const replacement=await resetResponse.json();assert.notEqual(replacement.temporaryPassword,installer.temporaryPassword);assert.equal((await me.GET(req('/api/me',null,installerCookie))).status,401);assert.equal((await signIn(installer.email,'InstallerPassphrase1!')).status,401);
 const installerCookie2=await activate(installer.email,replacement.temporaryPassword,'ReplacementPhrase123!');const disabled=await team.POST(req('/api/team',{id:installer.id,email:installer.email,name:'Installer',role:'installer',supervisorId:supervisor.id,active:false},managerCookie));assert.equal(disabled.status,200);assert.equal((await me.GET(req('/api/me',null,installerCookie2))).status,401);
 env.RESEND_API_KEY='test-resend-key';env.ACCOUNT_EMAIL_FROM='accounts@example.com';
 const originalFetch=globalThis.fetch;const sent=[];
 globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.resend.com/emails');const message=JSON.parse(options.body);assert.equal(options.headers.Authorization,'Bearer test-resend-key');assert.equal(message.to.length,1);assert.ok(sqlite.prepare('SELECT id FROM members WHERE email=?').get(message.to[0]),'Account must exist before email sends');sent.push(message);return Response.json({id:'test-email-id'})};
 try{
  const emailed=await create(managerCookie,'emailed-installer@example.com','installer','owner');assert.equal(emailed.emailStatus,'accepted');assert.equal(sent[0].to[0],emailed.email);assert.ok(sent[0].text.includes(emailed.temporaryPassword));assert.ok(sent[0].text.includes('/login?next=%2Finstallers'));assert.ok(sent[0].text.includes('7 days'));assert.ok(sent[0].text.includes('8 characters'));
  assert.equal(sqlite.prepare('SELECT invitation_status FROM members WHERE id=?').get(emailed.id).invitation_status,'accepted');assert.equal(sqlite.prepare('SELECT role FROM members WHERE id=?').get('owner').role,'admin');
  const edit=await team.POST(req('/api/team',{id:emailed.id,email:emailed.email,name:'Updated installer',role:'installer',supervisorId:'owner',active:true},managerCookie));assert.equal(edit.status,200);assert.equal(sent.length,1,'Editing must not send another password');
  globalThis.fetch=async()=>Response.json({error:'Rejected'},{status:403});const failed=await create(managerCookie,'failed-mail@example.com','supervisor');assert.equal(failed.emailStatus,'failed');assert.ok(failed.temporaryPassword);assert.equal(sqlite.prepare('SELECT invitation_status FROM members WHERE id=?').get(failed.id).invitation_status,'failed');
  globalThis.fetch=async()=>{throw Error('Must not email inactive account')};const inactive=await create(managerCookie,'inactive-mail@example.com','supervisor',null,{active:false});assert.equal(inactive.emailStatus,'inactive');
 }finally{globalThis.fetch=originalFetch;delete env.RESEND_API_KEY;delete env.ACCOUNT_EMAIL_FROM}
 assert.equal((await change.POST(req('/api/auth/change-password',{password:'AnotherOwnerPhrase1!',currentPassword:'wrong'},owner))).status,400);assert.equal((await logout.POST(req('/api/auth/logout',{},owner))).status,200);assert.equal((await me.GET(req('/api/me',null,owner))).status,401);
 for(let i=0;i<6;i++)assert.equal((await signIn('unknown@example.com','IncorrectPassword1!')).status,401);assert.equal((await signIn('unknown@example.com','IncorrectPassword1!')).status,429);
 assert.ok(sqlite.prepare('SELECT count(*) AS n FROM account_audit').get().n>=8);
});
