import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {randomUUID,createECDH,randomBytes,createHash} from 'node:crypto';
import {createServer} from 'vite';
import webpush from 'web-push';
const sqlite=new DatabaseSync(':memory:');
for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+file,'utf8'));
function stmt(sql){let args=[];return {bind(...a){args=a;return this},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return {results:sqlite.prepare(sql).all(...args)}},async run(){const result=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(result.changes)}}}}}
const bucket=new Map();
const keys=webpush.generateVAPIDKeys();
globalThis.__installerEnv={OWNER_EMAIL:'owner@example.com',VAPID_PUBLIC_KEY:keys.publicKey,VAPID_PRIVATE_KEY:keys.privateKey,DB:{prepare:stmt,async batch(statements){sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}},BUCKET:{async put(key,bytes,metadata){bucket.set(key,{...metadata,body:bytes})},async head(key){return bucket.get(key)||null},async get(key){return bucket.get(key)||null}}};
const vite=await createServer({configFile:false,resolve:{alias:{'@':resolve('.')}},plugins:[{name:'test-cloudflare',enforce:'pre',resolveId(id){if(id==='cloudflare:workers')return '\0test-cloudflare'},load(id){if(id==='\0test-cloudflare')return 'export const env=globalThis.__installerEnv;'}}],server:{middlewareMode:true,hmr:false}});
const jobs=await vite.ssrLoadModule('/app/api/jobs/route.ts');const assigned=await vite.ssrLoadModule('/app/api/installer/jobs/route.ts');const files=await vite.ssrLoadModule('/app/api/attachments/route.ts');const reports=await vite.ssrLoadModule('/app/api/installer/reports/route.ts');const access=await vite.ssrLoadModule('/lib/access.ts');const team=await vite.ssrLoadModule('/app/api/team/route.ts');const {validPushEndpoint}=await vite.ssrLoadModule('/lib/push.ts');
const visits=await vite.ssrLoadModule('/app/api/job-visits/route.ts');const visitJobs=await vite.ssrLoadModule('/app/api/job-visits/jobs/route.ts');const {visitQuestions}=await vite.ssrLoadModule('/lib/job-visits.ts');
await vite.close();
const tokens={};
const supervisor=randomUUID(),installer=randomUUID(),other=randomUUID(),supervisor2=randomUUID();
for(const [id,name,role,sup] of [[supervisor,'Supervisor','supervisor',null],[installer,'Installer','installer',supervisor],[other,'Other installer','installer',supervisor],[supervisor2,'Supervisor two','supervisor',null]])sqlite.prepare('INSERT INTO members (id,email,user_id,name,role,supervisor_id,active) VALUES (?,?,?,?,?,?,1)').run(id,id+'@example.com',id,name,role,sup);
sqlite.prepare("INSERT INTO members (id,email,name,role,active) VALUES ('owner','owner@example.com','Owner','admin',1)").run();
for(const id of ['owner',supervisor,installer,other,supervisor2]){tokens[id]=randomBytes(32).toString('base64url');sqlite.prepare('INSERT INTO credentials (member_id,password_hash,must_change,generation) VALUES (?,?,0,1)').run(id,'unused');sqlite.prepare('INSERT INTO sessions VALUES (?,?,1,0,?)').run(createHash('sha256').update(tokens[id]).digest('hex'),id,Date.now()+3600000)}
function request(path,who='owner',body){const headers={'oai-authenticated-user-id':who,'oai-authenticated-user-email':who==='owner'?'owner@example.com':who+'@example.com','origin':'https://example.com','cookie':'__Host-production_session='+tokens[who]};if(body&&!(body instanceof FormData))headers['Content-Type']='application/json';return new Request('https://example.com'+path,{method:body?'POST':'GET',headers,body:body instanceof FormData?body:body?JSON.stringify(body):undefined})}
async function job(){const j={id:randomUUID(),number:'100',paymentMethod:'Credit Card',customer:'Customer',address:'123 Test Street',phone:'555-0100',supervisor:'',crew:'',stage:'Received',installerId:installer,supervisorId:supervisor,eta:'',install:'2026-09-01',blocker:'',notes:'',version:0,history:[],attachments:[]};let response=await jobs.POST(request('/api/jobs','owner',j));assert.equal(response.status,200);const saved=(await response.json()).job;response=await jobs.POST(request('/api/jobs','owner',{...saved,stage:'Production'}));assert.equal(response.status,200);return (await response.json()).job}
let sequence=0;
async function upload(j,kind,who=installer,bytes){const form=new FormData();form.append('jobId',j.id);form.append('kind',kind);form.append('file',new File([bytes||new Uint8Array([255,216,255,++sequence,1,2,3])],'photo.jpg',{type:'image/jpeg'}));return files.POST(request('/api/attachments',who,form))}
async function attachments(j,status){const result=[];for(const kind of ['front','rear','left','right',...(status==='Incomplete'?['issue','incomplete','reorder']:['completion'])]){const response=await upload(j,kind);assert.equal(response.status,200);result.push((await response.json()).attachment)}return result}
function report(j,status='Complete',attachments=[]){return {id:randomUUID(),jobId:j.id,version:j.version,status,reason:status==='Incomplete'?'Damaged sash requires reorder':'',notes:'Report notes',installed:'2026-09-01',attachments}}
test('installer access, required evidence, atomic transitions, and supervisor push delivery',async()=>{
 assert.equal((await jobs.GET(new Request('https://example.com/api/jobs'))).status,401);
 const j=await job();
 assert.equal((await jobs.GET(request('/api/jobs',installer))).status,403);
 assert.equal((await (await assigned.GET(request('/api/installer/jobs',installer))).json()).jobs.length,1);
 assert.equal((await (await assigned.GET(request('/api/installer/jobs',other))).json()).jobs.length,0);
 const projection=(await (await assigned.GET(request('/api/installer/jobs',installer))).json()).jobs[0];assert.equal(projection.paymentMethod,'Credit Card');assert.equal('amount' in projection,false);assert.equal('history' in projection,false);
 assert.equal((await upload(j,'front',other)).status,403);
 const readOnly=await (await jobs.GET(request('/api/jobs',supervisor))).json();assert.equal(readOnly.jobs.find(row=>row.id===j.id).canEdit,false);assert.equal(readOnly.canCreateJobs,false);
 assert.equal((await jobs.POST(request('/api/jobs',supervisor,{...j,notes:'Unauthorized edit'}))).status,403);assert.equal((await upload(j,'photos',supervisor)).status,403);
 const otherSupervisorView=await (await jobs.GET(request('/api/jobs',supervisor2))).json();
 assert.equal(otherSupervisorView.jobs.some(row=>row.id===j.id&&row.install===j.install),true,'Other supervisors see pipeline and scheduled jobs');
 assert.equal(otherSupervisorView.jobs.find(row=>row.id===j.id).canEdit,false);
 const unassigned={...j,id:randomUUID(),installerId:null,supervisorId:null,install:'',stage:'Received'};
 sqlite.prepare('INSERT INTO jobs (id,payload,version,updated) VALUES (?,?,1,?)').run(unassigned.id,JSON.stringify(unassigned),new Date().toISOString());
 assert.equal((await (await jobs.GET(request('/api/jobs',supervisor2))).json()).jobs.some(row=>row.id===unassigned.id),true,'Unassigned received jobs remain visible');
 sqlite.prepare('DELETE FROM jobs WHERE id=?').run(unassigned.id);
 const permissionJob=await job();
 const supervisorUpdate={id:supervisor,email:supervisor+'@example.com',name:'Supervisor',role:'supervisor',supervisorId:null,active:true};
 assert.equal((await team.POST(request('/api/team',supervisor,{...supervisorUpdate,canEditJobs:true}))).status,403);
 const renew=who=>sqlite.prepare('INSERT OR REPLACE INTO sessions VALUES (?,?,1,0,?)').run(createHash('sha256').update(tokens[who]).digest('hex'),who,Date.now()+3600000);
 assert.equal((await team.POST(request('/api/team','owner',{...supervisorUpdate,canEditJobs:true}))).status,200);renew(supervisor);
 const allowed=await (await jobs.GET(request('/api/jobs',supervisor))).json();assert.equal(allowed.jobs.find(row=>row.id===j.id).canEdit,true);assert.equal(allowed.canCreateJobs,false);
 const edited=await jobs.POST(request('/api/jobs',supervisor,{...permissionJob,notes:'Authorized supervisor update'}));assert.equal(edited.status,200,await edited.clone().text());const updatedJob=(await edited.json()).job;
 assert.equal(updatedJob.notes,'Authorized supervisor update');assert.equal((await jobs.POST(request('/api/jobs',supervisor,{...updatedJob,supervisorId:supervisor2}))).status,403);
 sqlite.prepare('UPDATE members SET can_edit_jobs=1 WHERE id=?').run(supervisor2);assert.equal((await jobs.POST(request('/api/jobs',supervisor2,{...updatedJob,notes:'Wrong job'}))).status,403);
 assert.equal((await (await visitJobs.GET(request('/api/job-visits/jobs',supervisor2))).json()).jobs.find(row=>row.id===j.id).canEdit,false);
 assert.equal((await team.POST(request('/api/team','owner',{...supervisorUpdate,canEditJobs:false}))).status,200);renew(supervisor);
 assert.equal((await jobs.POST(request('/api/jobs',supervisor,{...updatedJob,notes:'Revoked edit'}))).status,403);assert.equal((await upload(j,'photos',supervisor)).status,403);
 assert.equal(JSON.parse(sqlite.prepare('SELECT payload FROM jobs WHERE id=?').get(permissionJob.id).payload).notes,'Authorized supervisor update');sqlite.prepare('DELETE FROM jobs WHERE id=?').run(permissionJob.id);
 const visitPhoto=await upload(j,'visit',supervisor);assert.equal(visitPhoto.status,200);const photo=(await visitPhoto.json()).attachment;
 assert.equal((await upload(j,'visit',installer)).status,403);
 assert.equal((await upload(j,'visit',supervisor2)).status,200);
 const visit={id:randomUUID(),jobId:j.id,visitedOn:'2026-09-02',checks:Object.fromEntries(visitQuestions.map(([key])=>[key,{answer:'yes',notes:'Checked on site'}])),notes:'Customer follow-up recorded',photos:[photo]};
 assert.equal((await visits.POST(request('/api/job-visits',supervisor2,visit))).status,400);
 assert.equal((await visits.POST(request('/api/job-visits',installer,visit))).status,403);
 assert.equal((await visits.POST(request('/api/job-visits',supervisor,{...visit,checks:{}}))).status,400);
 assert.equal((await visits.POST(request('/api/job-visits',supervisor,{...visit,visitedOn:'2026-02-30'}))).status,400);
 assert.equal((await visits.POST(request('/api/job-visits',supervisor,{...visit,photos:[{...photo,key:'jobs/'+j.id+'/visit/'+randomUUID()}]}))).status,400);
 const foreign=(await (await upload(j,'visit','owner')).json()).attachment;
 assert.equal((await visits.POST(request('/api/job-visits',supervisor,{...visit,photos:[foreign]}))).status,400);
 const savedVisit=await visits.POST(request('/api/job-visits',supervisor,visit));assert.equal(savedVisit.status,200,await savedVisit.clone().text());assert.equal((await savedVisit.json()).visit.supervisorId,supervisor);
 assert.equal((await visits.POST(request('/api/job-visits',supervisor,visit))).status,200);assert.equal(sqlite.prepare('SELECT count(*) AS n FROM job_visits').get().n,1);
 const ownerVisits=await (await visits.GET(request('/api/job-visits?jobId='+j.id))).json();assert.equal(ownerVisits.visits[0].checks.damage.notes,'Checked on site');assert.equal(ownerVisits.visits[0].photos[0].key,photo.key);
 assert.equal((await visits.GET(request('/api/job-visits?jobId='+j.id,supervisor2))).status,200);
 assert.equal((await visits.GET(request('/api/job-visits?jobId='+j.id,installer))).status,403);
 assert.equal((await files.GET(request('/api/attachments?key='+encodeURIComponent(photo.key),installer))).status,403);
 assert.equal((await files.GET(request('/api/attachments?key='+encodeURIComponent(photo.key),supervisor))).status,200);
 assert.equal(JSON.parse(sqlite.prepare('SELECT payload FROM jobs WHERE id=?').get(j.id).payload).stage,'Production');
 const secondVisit={...visit,id:randomUUID(),photos:[]};assert.equal((await visits.POST(request('/api/job-visits',supervisor,secondVisit))).status,200);assert.equal(sqlite.prepare('SELECT count(*) AS n FROM job_visits').get().n,2);
 const otherSupervisorPhoto=(await (await upload(j,'visit',supervisor2)).json()).attachment;
 const otherSupervisorVisit={...visit,id:randomUUID(),photos:[otherSupervisorPhoto]};const crossVisit=await visits.POST(request('/api/job-visits',supervisor2,otherSupervisorVisit));assert.equal(crossVisit.status,200);assert.equal((await crossVisit.json()).visit.supervisorId,supervisor2);
 assert.equal((await files.GET(request('/api/attachments?key='+encodeURIComponent(otherSupervisorPhoto.key),supervisor))).status,200);
 const scheduled=(await (await visitJobs.GET(request('/api/job-visits/jobs',supervisor2))).json()).jobs;assert.ok(scheduled.some(row=>row.id===j.id));assert.equal('amount' in scheduled[0],false);assert.equal('history' in scheduled[0],false);
 assert.equal((await visitJobs.GET(request('/api/job-visits/jobs',installer))).status,403);
 const unscheduled={...j,id:randomUUID(),install:''};sqlite.prepare('INSERT INTO jobs (id,payload,version,updated) VALUES (?,?,1,?)').run(unscheduled.id,JSON.stringify(unscheduled),new Date().toISOString());
 assert.equal((await visits.GET(request('/api/job-visits?jobId='+unscheduled.id,supervisor2))).status,403);assert.equal((await upload(unscheduled,'visit',supervisor2)).status,403);assert.equal((await visits.POST(request('/api/job-visits',supervisor2,{...visit,id:randomUUID(),jobId:unscheduled.id,photos:[]}))).status,403);
 assert.equal((await visits.GET(request('/api/job-visits?jobId='+unscheduled.id,supervisor))).status,200);
 assert.equal((await (await visitJobs.GET(request('/api/job-visits/jobs',supervisor2))).json()).jobs.some(row=>row.id===unscheduled.id),false);
 assert.equal((await files.GET(request('/api/attachments?key='+encodeURIComponent('jobs/'+j.id+'/front/'+randomUUID()),supervisor2))).status,404);
 const evidence=await attachments(j,'Complete');
 assert.equal((await files.GET(request('/api/attachments?key='+encodeURIComponent(evidence[0].key),other))).status,403);
 const incomplete=report(j,'Complete',evidence.filter(a=>a.kind!=='rear'));assert.equal((await reports.POST(request('/api/installer/reports',installer,incomplete))).status,400);assert.equal(sqlite.prepare('SELECT count(*) AS n FROM notifications').get().n,0);
 const duplicate=await upload(j,'rear',installer,bucket.get(evidence[0].key).body);const dup=(await duplicate.json()).attachment;assert.equal((await reports.POST(request('/api/installer/reports',installer,report(j,'Complete',evidence.map(a=>a.kind==='rear'?dup:a))))).status,400);
 const subscriber=createECDH('prime256v1');subscriber.generateKeys();const subscription={endpoint:'https://fcm.googleapis.com/fcm/send/test',keys:{p256dh:subscriber.getPublicKey().toString('base64url'),auth:randomBytes(16).toString('base64url')}};sqlite.prepare('INSERT INTO push_subscriptions VALUES (?,?,?)').run(subscription.endpoint,supervisor,JSON.stringify(subscription));
 const originalFetch=globalThis.fetch;let pushCount=0;globalThis.fetch=async(url,options)=>{assert.equal(url,subscription.endpoint);assert.equal(options.method,'POST');assert.ok(options.headers.Authorization||options.headers.authorization);assert.ok(options.body.length>0);pushCount++;return new Response('',{status:201})};
 try{const payload=report(j,'Complete',evidence);assert.equal((await reports.POST(request('/api/installer/reports',other,payload))).status,403);const response=await reports.POST(request('/api/installer/reports',installer,payload));assert.equal(response.status,200,await response.text());assert.equal(JSON.parse(sqlite.prepare('SELECT payload FROM jobs WHERE id=?').get(j.id).payload).stage,'Closed');const alert=sqlite.prepare('SELECT * FROM notifications WHERE id=?').get(payload.id);assert.equal(alert.recipient_id,supervisor);assert.equal(alert.push_status,'sent');assert.equal(pushCount,1);assert.equal((await reports.POST(request('/api/installer/reports',installer,payload))).status,200);assert.equal(pushCount,1);assert.equal(sqlite.prepare('SELECT count(*) AS n FROM installer_reports').get().n,1)}finally{globalThis.fetch=originalFetch}
 const j2=await job();const evidence2=await attachments(j2,'Incomplete');assert.equal((await reports.POST(request('/api/installer/reports',installer,report(j2,'Incomplete',evidence2.filter(a=>a.kind!=='issue'))))).status,400);
 sqlite.prepare('DELETE FROM push_subscriptions').run();const payload2=report(j2,'Incomplete',evidence2);assert.equal((await reports.POST(request('/api/installer/reports',installer,payload2))).status,200);const saved=JSON.parse(sqlite.prepare('SELECT payload FROM jobs WHERE id=?').get(j2.id).payload);assert.equal(saved.stage,'Incomplete');assert.equal(saved.blocker,payload2.reason);assert.ok(saved.incompleteSince);assert.equal(sqlite.prepare('SELECT push_status FROM notifications WHERE id=?').get(payload2.id).push_status,'not_enabled');
 const ownerAssignment=await team.POST(request('/api/team','owner',{id:other,email:other+'@example.com',name:'Other installer',role:'installer',supervisorId:'owner',active:true}));assert.equal(ownerAssignment.status,200,await ownerAssignment.clone().text());
 sqlite.prepare('INSERT OR REPLACE INTO sessions VALUES (?,?,1,0,?)').run(createHash('sha256').update(tokens[other]).digest('hex'),other,Date.now()+3600000);
 const ownerDraft={...j,id:randomUUID(),stage:'Received',version:0,history:[],attachments:[],installerId:other,supervisorId:'owner',installed:''};const ownerCreate=await jobs.POST(request('/api/jobs','owner',ownerDraft));assert.equal(ownerCreate.status,200,await ownerCreate.clone().text());let ownerJob=(await ownerCreate.json()).job;assert.equal(ownerJob.supervisorId,'owner');
 ownerJob=(await (await jobs.POST(request('/api/jobs','owner',{...ownerJob,stage:'Production'}))).json()).job;
 const ownerEvidence=[];for(const kind of ['front','rear','left','right','completion'])ownerEvidence.push((await (await upload(ownerJob,kind,other)).json()).attachment);
 const ownerPayload=report(ownerJob,'Complete',ownerEvidence);assert.equal((await reports.POST(request('/api/installer/reports',other,ownerPayload))).status,200);assert.equal(sqlite.prepare('SELECT recipient_id FROM notifications WHERE id=?').get(ownerPayload.id).recipient_id,'owner');assert.equal(sqlite.prepare('SELECT push_status FROM notifications WHERE id=?').get(ownerPayload.id).push_status,'not_enabled');
 const j3=await job();sqlite.prepare('UPDATE jobs SET version=version+1 WHERE id=?').run(j3.id);assert.equal((await reports.POST(request('/api/installer/reports',installer,report(j3,'Complete',await attachments(j3,'Complete'))))).status,409);
 const r=await team.POST(request('/api/team','owner',{id:installer,email:installer+'@example.com',name:'Installer',role:'installer',supervisorId:supervisor2,active:true}));assert.equal(r.status,200);assert.equal(JSON.parse(sqlite.prepare('SELECT payload FROM jobs WHERE id=?').get(j3.id).payload).supervisorId,supervisor2);
 sqlite.prepare('UPDATE members SET active=0 WHERE id=?').run(installer);assert.equal((await assigned.GET(request('/api/installer/jobs',installer))).status,401);
 assert.equal(validPushEndpoint('https://localhost/test'),false);assert.equal(validPushEndpoint('https://fcm.googleapis.com.evil.test/test'),false);assert.equal(validPushEndpoint('https://fcm.googleapis.com/fcm/send/test'),true);
});
