import {actor,apiError,canSeeJob,isOffice,jobFor,ApiError,canEditJob,canCreateJobs,hasJobEditPermission} from '@/lib/access';
import { env } from '@/lib/server-env';
import { database } from '@/db/raw';
import { jobSchema as schema, normalizeJob, transitionError, incompleteSince, nextIncompleteSince } from '@/lib/job-workflow';
export async function GET(request:Request){try{const member=await actor(request);if(member.role==='installer')throw new ApiError(403,'Use the installer app.');const r=await database().prepare('SELECT payload, version FROM jobs ORDER BY updated DESC').all();return Response.json({jobs:r.results.map((r:any)=>(() => {const job=normalizeJob(JSON.parse(r.payload));return {...job,incompleteSince:incompleteSince(job),version:r.version,canEdit:canEditJob(member,job),canReassign:isOffice(member)};})()).filter((j:any)=>canSeeJob(member,j)),canCreateJobs:canCreateJobs(member)},{headers:{'Cache-Control':'no-store'}});}catch(e){return apiError(e);}}
export async function POST(request:Request){
 if(request.headers.get('origin') && new URL(request.headers.get('origin')!).host!==new URL(request.url).host) return Response.json({error:'Invalid request origin'},{status:403});
 try{const member=await actor(request);if(!hasJobEditPermission(member))throw new ApiError(403,'An administrator must allow job information updates for your account.');const parsed=schema.safeParse(await request.json());if(!parsed.success)return Response.json({error:parsed.error.issues.find(issue=>issue.path[0]==='blocker')?.message||'Check the required fields and dates.'},{status:400});const j=parsed.data;if(!isOffice(member)){await jobFor(member,j.id);}const db=database();const old:any=await db.prepare('SELECT payload, version FROM jobs WHERE id = ?').bind(j.id).first();if(old?!canEditJob(member,JSON.parse(old.payload)):!canCreateJobs(member))throw new ApiError(403,'You do not have permission to update this job.');if((old?.version||0)!==j.version)return Response.json({error:'This job was updated by someone else. Close this window, refresh, and try again.'},{status:409});
 const at=new Date().toISOString();const before=old?normalizeJob(JSON.parse(old.payload)):null;if(!isOffice(member)&&(before?.installerId!==j.installerId||before?.supervisorId!==j.supervisorId))throw new ApiError(403,'Only the office can change assignments.');if(j.installerId){const installer:any=await db.prepare("SELECT * FROM members WHERE id=? AND role='installer' AND active=1").bind(j.installerId).first();if(!installer)throw new ApiError(400,'Select an active installer.');const supervisor:any=await db.prepare("SELECT * FROM members WHERE id=? AND (role='supervisor' OR (id='owner' AND role='admin')) AND active=1").bind(installer.supervisor_id||'').first();if(!supervisor)throw new ApiError(400,'Assign a field supervisor to this installer in Team setup first.');j.supervisorId=supervisor.id;j.supervisor=supervisor.name;j.crew=installer.name;}else{j.supervisorId=null;}const workflowError=transitionError(before?.stage||null,j);if(workflowError)return Response.json({error:workflowError},{status:400});
 for(const a of j.attachments){if(!a.key.startsWith(`jobs/${j.id}/${a.kind}/`))return Response.json({error:'Invalid job attachment.'},{status:400});const file=await env.BUCKET.head(a.key);if(!file||file.customMetadata?.jobId!==j.id||file.customMetadata?.kind!==a.kind)return Response.json({error:'An attachment is missing. Please upload it again.'},{status:400});}
 const by=member.name+' ('+member.email+')';const changes=before?['number','customer','paymentMethod','installerId','supervisorId','address','phone','specialNotes','supervisor','crew','stage','eta','install','received','installed','amount','blocker','notes'].filter(k=>before[k]!==j[k as keyof typeof j]).map(k=>k==='stage'?`Stage: ${before.stage} → ${j.stage}`:`Updated ${k}`).join(' · '):'Job created';
 j.history=[{at,by,text:changes||'Job reviewed'},...(before?.history||[])].slice(0,500);const saved={...before,...j,incompleteSince:nextIncompleteSince(before,j.stage,at)};const payload=JSON.stringify(saved);const r=old?await db.prepare('UPDATE jobs SET payload=?,version=version+1,updated=? WHERE id=? AND version=?').bind(payload,at,j.id,j.version).run():await db.prepare('INSERT INTO jobs (id,payload,version,updated) VALUES (?,?,1,?) ON CONFLICT DO NOTHING').bind(j.id,payload,at).run();if(!r.meta.changes)return Response.json({error:'Another update was saved first. Refresh and try again.'},{status:409});return Response.json({job:{...saved,version:j.version+1,canEdit:canEditJob(member,saved),canReassign:isOffice(member)}});
 }catch(e){return apiError(e);}}
